// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"log/slog"

	"github.com/anacrolix/torrent/metainfo"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for AuthType.
const (
	Basic  AuthType = "basic"
	Bearer AuthType = "bearer"
)

// Defines values for SettingsLogFormat.
const (
	JSON SettingsLogFormat = "json"
	Text SettingsLogFormat = "text"
)

// Defines values for TSTorrentRequestAction.
const (
	TSTorrentRequestActionAdd  TSTorrentRequestAction = "add"
	TSTorrentRequestActionDrop TSTorrentRequestAction = "drop"
	TSTorrentRequestActionGet  TSTorrentRequestAction = "get"
	TSTorrentRequestActionList TSTorrentRequestAction = "list"
	TSTorrentRequestActionRem  TSTorrentRequestAction = "rem"
)

// Defines values for TSViewedRequestAction.
const (
	TSViewedRequestActionList TSViewedRequestAction = "list"
	TSViewedRequestActionRem  TSViewedRequestAction = "rem"
	TSViewedRequestActionSet  TSViewedRequestAction = "set"
)

// Defines values for TokenRequestGrantType.
const (
	Password TokenRequestGrantType = "password"
)

// Defines values for TorrentStorage.
const (
	File   TorrentStorage = "file"
	Memory TorrentStorage = "memory"
)

// Auth Authentication settings.
type Auth struct {
	// Enabled Enable or disable authentication.
	Enabled *bool `json:"enabled,omitempty"`

	// Password Password for authentication.
	Password *string `json:"password,omitempty"`

	// Type Authentication type.
	Type *AuthType `json:"type,omitempty"`

	// Username Username for authentication.
	Username *string `json:"username,omitempty"`
}

// AuthType Authentication type.
type AuthType string

// Backup defines model for Backup.
type Backup struct {
	Posters  map[string]openapi_types.File `json:"posters"`
	Torrents []Torrent                     `json:"torrents"`
}

// Error defines model for Error.
type Error struct {
	// Code HTTP status code.
	Code int `json:"code"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// ListTorrents List of torrents retrieved successfully.
type ListTorrents struct {
	// Limit Number of torrents returned in this response.
	Limit int `json:"limit"`

	// Offset Pagination offset used.
	Offset   int       `json:"offset"`
	Torrents []Torrent `json:"torrents"`

	// Total Total number of torrents available.
	Total int `json:"total"`
}

// LogEntry defines model for LogEntry.
type LogEntry struct {
	// Data Additional structured data associated with the log entry.
	Data *map[string]interface{} `json:"data,omitempty"`

	// Level The log level (e.g., INFO, WARN, ERROR).
	Level string `json:"level"`

	// Message The log message.
	Message string `json:"message"`

	// Time The timestamp of the log entry.
	Time time.Time `json:"time"`
}

// MemoryStats Global memory usage statistics.
type MemoryStats struct {
	// ActiveTorrents Number of active torrents using memory.
	ActiveTorrents int `json:"active_torrents"`

	// MaxMemory Maximum memory allowed in bytes.
	MaxMemory int64 `json:"max_memory"`

	// TotalPieces Total number of pieces in memory.
	TotalPieces int `json:"total_pieces"`

	// UsedMemory Current memory used in bytes.
	UsedMemory int64 `json:"used_memory"`
}

// PieceInfo Information about a torrent piece that we are actively managing.
type PieceInfo struct {
	// Complete Whether the piece is marked as complete.
	Complete bool `json:"complete"`

	// InMemory Whether the piece data is currently loaded in memory.
	InMemory bool `json:"in_memory"`

	// Index Zero-based piece index within the torrent.
	Index int `json:"index"`

	// Size Piece size in bytes.
	Size int64 `json:"size"`
}

// Settings Application configuration settings.
type Settings struct {
	// Auth Authentication settings.
	Auth *Auth `json:"auth,omitempty"`

	// EnableDlna Enable DLNA media server functionality.
	EnableDlna *bool `json:"enable_dlna,omitempty"`

	// EnableDownloader Enable background downloading for torrents with file storage.
	EnableDownloader *bool `json:"enable_downloader,omitempty"`

	// FileStoragePath Path to the file storage.
	FileStoragePath *string `json:"file_storage_path,omitempty"`

	// FriendlyName DLNA friendly name displayed to clients.
	FriendlyName *string `json:"friendly_name,omitempty"`

	// HTTPServerPort TCP port for HTTP server.
	HTTPServerPort *int `json:"http_server_port,omitempty"`

	// LogFormat Log format.
	LogFormat *SettingsLogFormat `json:"log_format,omitempty"`

	// LogLevel Log level.
	LogLevel *slog.Level `json:"log_level,omitempty"`

	// LogStoreSize Number of log entries to store in memory.
	LogStoreSize *int `json:"log_store_size,omitempty"`

	// MaxMemory Maximum memory allocation for piece storage in bytes.
	MaxMemory *int64 `json:"max_memory,omitempty"`

	// ReadaheadPercentage Readahead percentage value (50-100).
	ReadaheadPercentage *int `json:"readahead_percentage,omitempty"`

	// TorrentClient Torrent client configuration.
	TorrentClient *TorrentClient `json:"torrent_client,omitempty"`
}

// SettingsLogFormat Log format.
type SettingsLogFormat string

// SystemInfo defines model for SystemInfo.
type SystemInfo struct {
	// Addresses List of listening addresses.
	Addresses []string `json:"addresses"`

	// BuildDate Date when the build was created.
	BuildDate string `json:"build_date"`

	// Commit Git commit hash.
	Commit string `json:"commit"`

	// Uptime Application uptime in seconds.
	Uptime int64 `json:"uptime"`

	// Version Application release version (semantic versioning).
	Version string `json:"version"`
}

// SystemMetrics defines model for SystemMetrics.
type SystemMetrics struct {
	// ActiveTorrents Total number of torrents loaded in the torrent client.
	ActiveTorrents int `json:"active_torrents"`

	// DownloadSpeed Global download speed in bytes per second.
	DownloadSpeed int64 `json:"download_speed"`

	// UploadSpeed Global upload speed in bytes per second.
	UploadSpeed int64 `json:"upload_speed"`
}

// TSCacheRequest TorrServer cache statistics request.
type TSCacheRequest struct {
	// Hash Torrent info hash.
	Hash string `json:"hash"`
}

// TSCacheResponse TorrServer cache statistics response.
type TSCacheResponse struct {
	// Capacity Total cache capacity in bytes.
	Capacity int64 `json:"Capacity"`

	// Pieces Map of piece indices to piece information.
	Pieces map[string]TSPieceInfo `json:"Pieces"`

	// PiecesCount Total number of pieces.
	PiecesCount int `json:"PiecesCount"`

	// PiecesLength Standard piece length in bytes.
	PiecesLength int64 `json:"PiecesLength"`

	// Readers Active read operations on the cache.
	Readers []TSReaderInfo `json:"Readers"`
}

// TSPieceInfo TorrServer piece information.
type TSPieceInfo struct {
	// Completed Whether the piece is complete.
	Completed bool `json:"Completed"`

	// ID Piece index.
	ID int `json:"Id"`

	// Length Piece size in bytes.
	Length int64 `json:"Length"`

	// Priority Piece priority (higher is more important).
	Priority *int `json:"Priority,omitempty"`
}

// TSReaderInfo TorrServer reader information.
type TSReaderInfo struct {
	// End End position in bytes.
	End int `json:"end"`

	// Reader Reader identifier.
	Reader int `json:"reader"`

	// Start Start position in bytes.
	Start int `json:"start"`
}

// TSSettings TorrServer settings.
type TSSettings struct {
	// CacheSize Maximum memory for cache in bytes.
	CacheSize *int64 `json:"CacheSize,omitempty"`
}

// TSTorrentAddFile defines model for TSTorrentAddFile.
type TSTorrentAddFile struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// File Torrent file.
	File openapi_types.File `json:"file"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// TSTorrentFileStat defines model for TSTorrentFileStat.
type TSTorrentFileStat struct {
	// ID File index.
	ID int `json:"id"`

	// Length File size in bytes.
	Length int64 `json:"length"`

	// Name Base name of the file.
	Name string `json:"name"`

	// Path Full path of the file within the torrent.
	Path string `json:"path"`

	// ViewedAt When the file was last viewed.
	ViewedAt *time.Time `json:"viewed_at"`
}

// TSTorrentRequest TorrServer torrent management request.
type TSTorrentRequest struct {
	// Action Action to perform.
	Action TSTorrentRequestAction `json:"action"`

	// Category Category for the torrent.
	Category *string `json:"category,omitempty"`

	// Data Base64-encoded torrent file data.
	Data *string                `json:"data,omitempty"`
	Hash *TSTorrentRequest_Hash `json:"hash,omitempty"`

	// Link Magnet link or URL.
	Link *string `json:"link,omitempty"`

	// Poster Poster image URL or data URI.
	Poster *string `json:"poster,omitempty"`

	// SaveToDB Save torrent to database.
	SaveToDB *bool `json:"save_to_db,omitempty"`

	// Title Display title.
	Title *string `json:"title,omitempty"`
}

// TSTorrentRequestAction Action to perform.
type TSTorrentRequestAction string

// TSTorrentRequestHash0 Empty value is allowed.
type TSTorrentRequestHash0 = string

// TSTorrentRequestHash1 Torrent info hash.
type TSTorrentRequestHash1 = string

// TSTorrentRequest_Hash defines model for TSTorrentRequest.Hash.
type TSTorrentRequest_Hash struct {
	union json.RawMessage
}

// TSTorrentResponse defines model for TSTorrentResponse.
type TSTorrentResponse struct {
	// ActivePeers Number of currently active peers.
	ActivePeers int     `json:"active_peers"`
	BitRate     *string `json:"bit_rate,omitempty"`

	// BytesHashed Total bytes hashed during verification.
	BytesHashed int64 `json:"bytes_hashed"`

	// BytesRead Total bytes read from disk.
	BytesRead int64 `json:"bytes_read"`

	// BytesReadData Bytes read that contain actual torrent data.
	BytesReadData int64 `json:"bytes_read_data"`

	// BytesReadUsefulData Useful data bytes read from peers.
	BytesReadUsefulData int64 `json:"bytes_read_useful_data"`

	// BytesReadUsefulIntendedData Useful intended data bytes read from peers.
	BytesReadUsefulIntendedData int64 `json:"bytes_read_useful_intended_data"`

	// BytesWritten Total bytes written to disk.
	BytesWritten int64 `json:"bytes_written"`

	// BytesWrittenData Torrent data bytes written to disk.
	BytesWrittenData int64   `json:"bytes_written_data"`
	Category         *string `json:"category,omitempty"`

	// ChunksRead Total chunks read from disk.
	ChunksRead int64 `json:"chunks_read"`

	// ChunksReadUseful Useful chunks read from peers.
	ChunksReadUseful int64 `json:"chunks_read_useful"`

	// ChunksReadWasted Wasted chunks read (duplicate or unneeded data).
	ChunksReadWasted int64 `json:"chunks_read_wasted"`

	// ChunksWritten Total chunks written to disk.
	ChunksWritten int64 `json:"chunks_written"`

	// CompletedSize Total size of completed pieces in bytes.
	CompletedSize int64 `json:"completed_size"`

	// ConnectedSeeders Number of connected seeders.
	ConnectedSeeders int     `json:"connected_seeders"`
	Data             *string `json:"data,omitempty"`

	// DownloadSpeed Download speed in bytes per second.
	DownloadSpeed   float64  `json:"download_speed"`
	DurationSeconds *float32 `json:"duration_seconds,omitempty"`

	// FileStats Statistics for each file in the torrent.
	FileStats *[]TSTorrentFileStat `json:"file_stats,omitempty"`

	// HalfOpenPeers Number of peers in half-open state (connecting).
	HalfOpenPeers int `json:"half_open_peers"`

	// Hash Torrent info hash.
	Hash string `json:"hash"`

	// InMemory Number of pieces currently loaded in memory.
	InMemory int `json:"in_memory"`

	// InMemorySize Total size of pieces currently in memory in bytes.
	InMemorySize int64 `json:"in_memory_size"`
	LoadedSize   int64 `json:"loaded_size"`

	// MemoryStats Global memory usage statistics.
	MemoryStats MemoryStats `json:"memory_stats"`

	// MemoryUsagePercentage Percentage of maximum memory used by this torrent (0-100).
	MemoryUsagePercentage float64 `json:"memory_usage_percentage"`

	// MetadataChunksRead Metadata chunks read.
	MetadataChunksRead int64 `json:"metadata_chunks_read"`

	// Name Torrent name.
	Name string `json:"name"`

	// PendingPeers Number of pending peer connections.
	PendingPeers int `json:"pending_peers"`

	// Pieces Array of all managed pieces with their current status.
	Pieces []PieceInfo `json:"pieces"`

	// PiecesComplete Number of completed pieces.
	PiecesComplete int `json:"pieces_complete"`

	// PiecesDirtiedBad Pieces marked as bad after verification.
	PiecesDirtiedBad int64 `json:"pieces_dirtied_bad"`

	// PiecesDirtiedGood Pieces marked as good after verification.
	PiecesDirtiedGood int64 `json:"pieces_dirtied_good"`

	// Poster Poster image URL or data URI.
	Poster         *string `json:"poster,omitempty"`
	PreloadSize    int64   `json:"preload_size"`
	PreloadedBytes int64   `json:"preloaded_bytes"`
	Stat           int     `json:"stat"`
	StatString     string  `json:"stat_string"`
	Timestamp      int64   `json:"timestamp"`

	// Title Display title.
	Title       string `json:"title"`
	TorrentSize int64  `json:"torrent_size"`

	// TotalPeers Total number of known peers.
	TotalPeers int `json:"total_peers"`

	// TotalPieces Total number of pieces in the torrent, from metadata.
	TotalPieces int `json:"total_pieces"`

	// TotalSize Total size of all managed pieces in bytes.
	TotalSize   int64   `json:"total_size"`
	UploadSpeed float32 `json:"upload_speed"`
}

// TSViewedRequest TorrServer view tag request.
type TSViewedRequest struct {
	// Action Action to perform.
	Action    TSViewedRequestAction `json:"action"`
	FileIndex int                   `json:"file_index"`
	Hash      string                `json:"hash"`
}

// TSViewedRequestAction Action to perform.
type TSViewedRequestAction string

// TSViewedResponse TorrServer view tag response.
type TSViewedResponse struct {
	FileIndex int    `json:"file_index"`
	Hash      string `json:"hash"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	// GrantType The grant type. Must be 'password'.
	GrantType TokenRequestGrantType `json:"grant_type"`

	// Password The user's password.
	Password string `json:"password"`

	// Username The user's username.
	Username string `json:"username"`
}

// TokenRequestGrantType The grant type. Must be 'password'.
type TokenRequestGrantType string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken The JWT access token.
	AccessToken string `json:"access_token"`

	// ExpiresIn The lifetime in seconds of the access token.
	ExpiresIn *int `json:"expires_in,omitempty"`

	// TokenType The type of token. Always 'Bearer'.
	TokenType string `json:"token_type"`
}

// Torrent defines model for Torrent.
type Torrent struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// CreatedAt When the torrent was added to the system.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Files List of files contained in the torrent.
	Files []TorrentFile `json:"files"`

	// Hash SHA-1 info hash of the torrent (40 hex characters).
	Hash metainfo.Hash `json:"hash"`

	// Magnet Magnet URI.
	Magnet string `json:"magnet"`

	// Name Original name of the torrent from metadata.
	Name string `json:"name"`

	// PieceCount Total number of pieces in the torrent.
	PieceCount int `json:"piece_count"`

	// PieceSize Standard piece size in bytes.
	PieceSize *int64 `json:"piece_size,omitempty"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`

	// TotalSize Total size of all files in bytes.
	TotalSize int64 `json:"total_size"`

	// UpdatedAt Last time the torrent was modified.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TorrentAdd Input for adding a new torrent.
type TorrentAdd struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// Hash SHA-1 info hash of the torrent (40 hex characters).
	Hash *metainfo.Hash `json:"hash,omitempty"`

	// Magnet Magnet URI.
	Magnet *string `json:"magnet,omitempty"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// TorrentAddFile defines model for TorrentAddFile.
type TorrentAddFile struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// File Torrent file.
	File openapi_types.File `json:"file"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// TorrentClient Torrent client configuration.
type TorrentClient struct {
	// DisableDHT Disable DHT (Distributed Hash Table).
	DisableDHT *bool `json:"disable_dht,omitempty"`

	// DisableIPv6 Disable IPv6.
	DisableIPv6 *bool `json:"disable_ipv6,omitempty"`

	// DisablePEX Disable PEX (Peer Exchange).
	DisablePEX *bool `json:"disable_pex,omitempty"`

	// DisableTCP Disable TCP connections.
	DisableTCP *bool `json:"disable_tcp,omitempty"`

	// DisableUTP Disable uTP (Micro Transport Protocol).
	DisableUTP *bool `json:"disable_utp,omitempty"`

	// DownloadRateLimit Download rate limit in bytes per second. 0 means unlimited.
	DownloadRateLimit *int `json:"download_rate_limit,omitempty"`

	// EstablishedConnsPerTorrent The maximum number of established connections per torrent.
	EstablishedConnsPerTorrent *int `json:"established_conns_per_torrent,omitempty"`

	// PreferHeaderObfuscation Request that outgoing connections' headers be obfuscated.
	PreferHeaderObfuscation *bool `json:"prefer_header_obfuscation,omitempty"`

	// Seed Whether to seed after downloading.
	Seed *bool `json:"seed,omitempty"`

	// TorrentPeersHighWater The high water mark for the number of peers per torrent.
	TorrentPeersHighWater *int `json:"torrent_peers_high_water,omitempty"`

	// UploadRateLimit Upload rate limit in bytes per second. 0 means unlimited.
	UploadRateLimit *int `json:"upload_rate_limit,omitempty"`
}

// TorrentFile File within a torrent.
type TorrentFile struct {
	// Length File size in bytes.
	Length int64 `json:"length"`

	// Name Base name of the file.
	Name string `json:"name"`

	// Path Full path of the file within the torrent.
	Path string `json:"path"`

	// ViewedAt When the file was last viewed.
	ViewedAt *time.Time `json:"viewed_at"`
}

// TorrentFileUpdate Metadata for updating a file within a torrent.
type TorrentFileUpdate struct {
	// Path The full path of the file within the torrent.
	Path string `json:"path"`

	// Viewed Set to true to mark as viewed, false to mark as unviewed.
	Viewed bool `json:"viewed"`
}

// TorrentStats Statistics about torrent activity and performance.
type TorrentStats struct {
	// ActivePeers Number of currently active peers.
	ActivePeers int `json:"active_peers"`

	// BytesHashed Total bytes hashed during verification.
	BytesHashed int64 `json:"bytes_hashed"`

	// BytesRead Total bytes read from disk.
	BytesRead int64 `json:"bytes_read"`

	// BytesReadData Bytes read that contain actual torrent data.
	BytesReadData int64 `json:"bytes_read_data"`

	// BytesReadUsefulData Useful data bytes read from peers.
	BytesReadUsefulData int64 `json:"bytes_read_useful_data"`

	// BytesReadUsefulIntendedData Useful intended data bytes read from peers.
	BytesReadUsefulIntendedData int64 `json:"bytes_read_useful_intended_data"`

	// BytesWritten Total bytes written to disk.
	BytesWritten int64 `json:"bytes_written"`

	// BytesWrittenData Torrent data bytes written to disk.
	BytesWrittenData int64 `json:"bytes_written_data"`

	// ChunksRead Total chunks read from disk.
	ChunksRead int64 `json:"chunks_read"`

	// ChunksReadUseful Useful chunks read from peers.
	ChunksReadUseful int64 `json:"chunks_read_useful"`

	// ChunksReadWasted Wasted chunks read (duplicate or unneeded data).
	ChunksReadWasted int64 `json:"chunks_read_wasted"`

	// ChunksWritten Total chunks written to disk.
	ChunksWritten int64 `json:"chunks_written"`

	// CompletedSize Total size of completed pieces in bytes.
	CompletedSize int64 `json:"completed_size"`

	// ConnectedSeeders Number of connected seeders.
	ConnectedSeeders int `json:"connected_seeders"`

	// HalfOpenPeers Number of peers in half-open state (connecting).
	HalfOpenPeers int `json:"half_open_peers"`

	// InMemory Number of pieces currently loaded in memory.
	InMemory int `json:"in_memory"`

	// InMemorySize Total size of pieces currently in memory in bytes.
	InMemorySize int64 `json:"in_memory_size"`

	// MemoryStats Global memory usage statistics.
	MemoryStats MemoryStats `json:"memory_stats"`

	// MemoryUsagePercentage Percentage of maximum memory used by this torrent (0-100).
	MemoryUsagePercentage float64 `json:"memory_usage_percentage"`

	// MetadataChunksRead Metadata chunks read.
	MetadataChunksRead int64 `json:"metadata_chunks_read"`

	// PendingPeers Number of pending peer connections.
	PendingPeers int `json:"pending_peers"`

	// Pieces Array of all managed pieces with their current status.
	Pieces []PieceInfo `json:"pieces"`

	// PiecesComplete Number of completed pieces.
	PiecesComplete int `json:"pieces_complete"`

	// PiecesDirtiedBad Pieces marked as bad after verification.
	PiecesDirtiedBad int64 `json:"pieces_dirtied_bad"`

	// PiecesDirtiedGood Pieces marked as good after verification.
	PiecesDirtiedGood int64 `json:"pieces_dirtied_good"`

	// TotalPeers Total number of known peers.
	TotalPeers int `json:"total_peers"`

	// TotalPieces Total number of pieces in the torrent, from metadata.
	TotalPieces int `json:"total_pieces"`

	// TotalSize Total size of all managed pieces in bytes.
	TotalSize int64 `json:"total_size"`
}

// TorrentStorage Use memory or file storage.
type TorrentStorage string

// TorrentUpdate Updateable torrent metadata.
type TorrentUpdate struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// Files List of files to update within the torrent.
	Files *[]TorrentFileUpdate `json:"files,omitempty"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// Hash defines model for Hash.
type Hash = metainfo.Hash

// Index defines model for Index.
type Index = int

// Limit defines model for Limit.
type Limit = int

// MediaName defines model for MediaName.
type MediaName = string

// Offset defines model for Offset.
type Offset = int

// Path defines model for Path.
type Path = string

// Range defines model for Range.
type Range = string

// TSFileName defines model for TSFileName.
type TSFileName = string

// TSIndex defines model for TSIndex.
type TSIndex = int

// TSIndexQuery defines model for TSIndexQuery.
type TSIndexQuery = int

// TSLink defines model for TSLink.
type TSLink = string

// TSPlay defines model for TSPlay.
type TSPlay = bool

// TSPreload defines model for TSPreload.
type TSPreload = bool

// TSStat defines model for TSStat.
type TSStat = bool

// TorrentCategories defines model for TorrentCategories.
type TorrentCategories = []string

// TorrentHashes defines model for TorrentHashes.
type TorrentHashes = []metainfo.Hash

// TorrentNames defines model for TorrentNames.
type TorrentNames = []string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// GatewayTimeout defines model for GatewayTimeout.
type GatewayTimeout = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetPlaylistParams defines parameters for GetPlaylist.
type GetPlaylistParams struct {
	// Name Media playlist by torrent name.
	Name *MediaName `form:"name,omitempty" json:"name,omitempty"`
}

// GetStreamParams defines parameters for GetStream.
type GetStreamParams struct {
	// Path Path to a torrent file. One of `path` or `index` must be provided.
	Path *Path `form:"path,omitempty" json:"path,omitempty"`

	// Index Index of the file within the torrent. One of `path` or `index` must be provided.
	Index *Index `form:"index,omitempty" json:"index,omitempty"`

	// Range Bytes range for partial content requests.
	Range *Range `json:"Range,omitempty"`
}

// HeadStreamParams defines parameters for HeadStream.
type HeadStreamParams struct {
	// Path Path to a torrent file. One of `path` or `index` must be provided.
	Path *Path `form:"path,omitempty" json:"path,omitempty"`

	// Index Index of the file within the torrent. One of `path` or `index` must be provided.
	Index *Index `form:"index,omitempty" json:"index,omitempty"`
}

// ListTorrentsParams defines parameters for ListTorrents.
type ListTorrentsParams struct {
	// Categories Comma-separated list of torrent categories to filter results.
	Categories *TorrentCategories `form:"categories,omitempty" json:"categories,omitempty"`

	// Hashes Comma-separated list of torrent info hashes to filter results.
	Hashes *TorrentHashes `form:"hashes,omitempty" json:"hashes,omitempty"`

	// Names Comma-separated list of torrent names to filter results. The filter performs case-insensitive matching against torrent names.
	Names *TorrentNames `form:"names,omitempty" json:"names,omitempty"`

	// Limit Maximum number of torrents to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of torrents to skip for pagination.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// RestoreTorrentsMultipartBody defines parameters for RestoreTorrents.
type RestoreTorrentsMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// QBittorrentAddTorrentMultipartBody defines parameters for QBittorrentAddTorrent.
type QBittorrentAddTorrentMultipartBody struct {
	// Category Category for the torrent.
	Category *string               `json:"category,omitempty"`
	Torrents *[]openapi_types.File `json:"torrents,omitempty"`

	// Urls A list of magnet links to add.
	Urls *string `json:"urls,omitempty"`
}

// TSStreamParams defines parameters for TSStream.
type TSStreamParams struct {
	// Link Magnet link or info hash of the torrent.
	Link TSLink `form:"link" json:"link"`

	// Index File index within the torrent.
	Index *TSIndexQuery `form:"index,omitempty" json:"index,omitempty"`

	// Play Start playback immediately.
	Play *TSPlay `form:"play,omitempty" json:"play,omitempty"`

	// Preload Preload content without playing.
	Preload *TSPreload `form:"preload,omitempty" json:"preload,omitempty"`

	// Stat Return statistics instead of streaming.
	Stat *TSStat `form:"stat,omitempty" json:"stat,omitempty"`
}

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = Settings

// AddTorrentJSONRequestBody defines body for AddTorrent for application/json ContentType.
type AddTorrentJSONRequestBody = TorrentAdd

// AddTorrentMultipartRequestBody defines body for AddTorrent for multipart/form-data ContentType.
type AddTorrentMultipartRequestBody = TorrentAddFile

// RestoreTorrentsMultipartRequestBody defines body for RestoreTorrents for multipart/form-data ContentType.
type RestoreTorrentsMultipartRequestBody RestoreTorrentsMultipartBody

// UpdateTorrentJSONRequestBody defines body for UpdateTorrent for application/json ContentType.
type UpdateTorrentJSONRequestBody = TorrentUpdate

// QBittorrentAddTorrentMultipartRequestBody defines body for QBittorrentAddTorrent for multipart/form-data ContentType.
type QBittorrentAddTorrentMultipartRequestBody QBittorrentAddTorrentMultipartBody

// TSCacheJSONRequestBody defines body for TSCache for application/json ContentType.
type TSCacheJSONRequestBody = TSCacheRequest

// GetTokenFormdataRequestBody defines body for GetToken for application/x-www-form-urlencoded ContentType.
type GetTokenFormdataRequestBody = TokenRequest

// TSSettingsJSONRequestBody defines body for TSSettings for application/json ContentType.
type TSSettingsJSONRequestBody = TSSettings

// TSTorrentUploadMultipartRequestBody defines body for TSTorrentUpload for multipart/form-data ContentType.
type TSTorrentUploadMultipartRequestBody = TSTorrentAddFile

// TSTorrentsJSONRequestBody defines body for TSTorrents for application/json ContentType.
type TSTorrentsJSONRequestBody = TSTorrentRequest

// TSViewedJSONRequestBody defines body for TSViewed for application/json ContentType.
type TSViewedJSONRequestBody = TSViewedRequest

// AsTSTorrentRequestHash0 returns the union data inside the TSTorrentRequest_Hash as a TSTorrentRequestHash0
func (t TSTorrentRequest_Hash) AsTSTorrentRequestHash0() (TSTorrentRequestHash0, error) {
	var body TSTorrentRequestHash0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTSTorrentRequestHash0 overwrites any union data inside the TSTorrentRequest_Hash as the provided TSTorrentRequestHash0
func (t *TSTorrentRequest_Hash) FromTSTorrentRequestHash0(v TSTorrentRequestHash0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTSTorrentRequestHash0 performs a merge with any union data inside the TSTorrentRequest_Hash, using the provided TSTorrentRequestHash0
func (t *TSTorrentRequest_Hash) MergeTSTorrentRequestHash0(v TSTorrentRequestHash0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTSTorrentRequestHash1 returns the union data inside the TSTorrentRequest_Hash as a TSTorrentRequestHash1
func (t TSTorrentRequest_Hash) AsTSTorrentRequestHash1() (TSTorrentRequestHash1, error) {
	var body TSTorrentRequestHash1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTSTorrentRequestHash1 overwrites any union data inside the TSTorrentRequest_Hash as the provided TSTorrentRequestHash1
func (t *TSTorrentRequest_Hash) FromTSTorrentRequestHash1(v TSTorrentRequestHash1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTSTorrentRequestHash1 performs a merge with any union data inside the TSTorrentRequest_Hash, using the provided TSTorrentRequestHash1
func (t *TSTorrentRequest_Hash) MergeTSTorrentRequestHash1(v TSTorrentRequestHash1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TSTorrentRequest_Hash) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TSTorrentRequest_Hash) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get global memory statistics.
	// (GET /api/stats/memory)
	GetMemoryStats(w http.ResponseWriter, r *http.Request)
	// Get torrent statistics.
	// (GET /api/stats/torrents/{hash})
	GetTorrentStats(w http.ResponseWriter, r *http.Request, hash Hash)
	// Health check.
	// (GET /api/system/health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Get application information.
	// (GET /api/system/info)
	GetSystemInfo(w http.ResponseWriter, r *http.Request)
	// Get recent application logs.
	// (GET /api/system/logs)
	GetLogs(w http.ResponseWriter, r *http.Request)
	// Get system metrics.
	// (GET /api/system/metrics)
	GetSystemMetrics(w http.ResponseWriter, r *http.Request)
	// Generate a playlist for streaming.
	// (GET /api/v1/playlist)
	GetPlaylist(w http.ResponseWriter, r *http.Request, params GetPlaylistParams)
	// Get application settings.
	// (GET /api/v1/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// Update application settings.
	// (PATCH /api/v1/settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)
	// Stream a torrent file.
	// (GET /api/v1/stream/{hash})
	GetStream(w http.ResponseWriter, r *http.Request, hash Hash, params GetStreamParams)
	// Serve a HEAD request for a streamable torrent file.
	// (HEAD /api/v1/stream/{hash})
	HeadStream(w http.ResponseWriter, r *http.Request, hash Hash, params HeadStreamParams)
	// List all torrents.
	// (GET /api/v1/torrents)
	ListTorrents(w http.ResponseWriter, r *http.Request, params ListTorrentsParams)
	// Add a new torrent.
	// (POST /api/v1/torrents)
	AddTorrent(w http.ResponseWriter, r *http.Request)
	// Backup torrents and posters.
	// (GET /api/v1/torrents/backup)
	BackupTorrents(w http.ResponseWriter, r *http.Request)
	// Restore torrents and posters.
	// (POST /api/v1/torrents/restore)
	RestoreTorrents(w http.ResponseWriter, r *http.Request)
	// Delete a torrent.
	// (DELETE /api/v1/torrents/{hash})
	DeleteTorrent(w http.ResponseWriter, r *http.Request, hash Hash)
	// Get torrent metadata.
	// (GET /api/v1/torrents/{hash})
	GetTorrent(w http.ResponseWriter, r *http.Request, hash Hash)
	// Update torrent metadata.
	// (PATCH /api/v1/torrents/{hash})
	UpdateTorrent(w http.ResponseWriter, r *http.Request, hash Hash)
	// Add a new torrent (qBittorrent compatible).
	// (POST /api/v2/torrents/add)
	QBittorrentAddTorrent(w http.ResponseWriter, r *http.Request)
	// Get cache statistics (TorrServer compatible).
	// (POST /cache)
	TSCache(w http.ResponseWriter, r *http.Request)
	// Server status check (TorrServer compatible).
	// (GET /echo)
	TSEcho(w http.ResponseWriter, r *http.Request)
	// Obtain a JWT token.
	// (POST /oauth/token)
	GetToken(w http.ResponseWriter, r *http.Request)
	// Stream torrent content (TorrServer compatible).
	// (GET /play/{hash}/{index})
	TSPlay(w http.ResponseWriter, r *http.Request, hash Hash, index TSIndex)
	// Update settings (TorrServer compatible).
	// (POST /settings)
	TSSettings(w http.ResponseWriter, r *http.Request)
	// Stream or preload torrent (TorrServer compatible).
	// (GET /stream/{filename})
	TSStream(w http.ResponseWriter, r *http.Request, filename TSFileName, params TSStreamParams)
	// Add a new torrent (TorrServer compatible).
	// (POST /torrent/upload)
	TSTorrentUpload(w http.ResponseWriter, r *http.Request)
	// Manage torrents (TorrServer compatible).
	// (POST /torrents)
	TSTorrents(w http.ResponseWriter, r *http.Request)
	// Manage torrent view tags (TorrServer compatible).
	// (POST /viewed)
	TSViewed(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get global memory statistics.
// (GET /api/stats/memory)
func (_ Unimplemented) GetMemoryStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get torrent statistics.
// (GET /api/stats/torrents/{hash})
func (_ Unimplemented) GetTorrentStats(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check.
// (GET /api/system/health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get application information.
// (GET /api/system/info)
func (_ Unimplemented) GetSystemInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get recent application logs.
// (GET /api/system/logs)
func (_ Unimplemented) GetLogs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get system metrics.
// (GET /api/system/metrics)
func (_ Unimplemented) GetSystemMetrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate a playlist for streaming.
// (GET /api/v1/playlist)
func (_ Unimplemented) GetPlaylist(w http.ResponseWriter, r *http.Request, params GetPlaylistParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get application settings.
// (GET /api/v1/settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update application settings.
// (PATCH /api/v1/settings)
func (_ Unimplemented) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream a torrent file.
// (GET /api/v1/stream/{hash})
func (_ Unimplemented) GetStream(w http.ResponseWriter, r *http.Request, hash Hash, params GetStreamParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Serve a HEAD request for a streamable torrent file.
// (HEAD /api/v1/stream/{hash})
func (_ Unimplemented) HeadStream(w http.ResponseWriter, r *http.Request, hash Hash, params HeadStreamParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all torrents.
// (GET /api/v1/torrents)
func (_ Unimplemented) ListTorrents(w http.ResponseWriter, r *http.Request, params ListTorrentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new torrent.
// (POST /api/v1/torrents)
func (_ Unimplemented) AddTorrent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Backup torrents and posters.
// (GET /api/v1/torrents/backup)
func (_ Unimplemented) BackupTorrents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restore torrents and posters.
// (POST /api/v1/torrents/restore)
func (_ Unimplemented) RestoreTorrents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a torrent.
// (DELETE /api/v1/torrents/{hash})
func (_ Unimplemented) DeleteTorrent(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get torrent metadata.
// (GET /api/v1/torrents/{hash})
func (_ Unimplemented) GetTorrent(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update torrent metadata.
// (PATCH /api/v1/torrents/{hash})
func (_ Unimplemented) UpdateTorrent(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new torrent (qBittorrent compatible).
// (POST /api/v2/torrents/add)
func (_ Unimplemented) QBittorrentAddTorrent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cache statistics (TorrServer compatible).
// (POST /cache)
func (_ Unimplemented) TSCache(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server status check (TorrServer compatible).
// (GET /echo)
func (_ Unimplemented) TSEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Obtain a JWT token.
// (POST /oauth/token)
func (_ Unimplemented) GetToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream torrent content (TorrServer compatible).
// (GET /play/{hash}/{index})
func (_ Unimplemented) TSPlay(w http.ResponseWriter, r *http.Request, hash Hash, index TSIndex) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update settings (TorrServer compatible).
// (POST /settings)
func (_ Unimplemented) TSSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream or preload torrent (TorrServer compatible).
// (GET /stream/{filename})
func (_ Unimplemented) TSStream(w http.ResponseWriter, r *http.Request, filename TSFileName, params TSStreamParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new torrent (TorrServer compatible).
// (POST /torrent/upload)
func (_ Unimplemented) TSTorrentUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Manage torrents (TorrServer compatible).
// (POST /torrents)
func (_ Unimplemented) TSTorrents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Manage torrent view tags (TorrServer compatible).
// (POST /viewed)
func (_ Unimplemented) TSViewed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMemoryStats operation middleware
func (siw *ServerInterfaceWrapper) GetMemoryStats(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemoryStats(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTorrentStats operation middleware
func (siw *ServerInterfaceWrapper) GetTorrentStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTorrentStats(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemInfo operation middleware
func (siw *ServerInterfaceWrapper) GetSystemInfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemInfo(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLogs operation middleware
func (siw *ServerInterfaceWrapper) GetLogs(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogs(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetSystemMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemMetrics(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylist operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlaylistParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylist(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStream operation middleware
func (siw *ServerInterfaceWrapper) GetStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStreamParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Optional query parameter "index" -------------

	err = runtime.BindQueryParameter("form", true, false, "index", r.URL.Query(), &params.Index)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Range" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Range")]; found {
		var Range Range
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Range", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Range", valueList[0], &Range, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Range", Err: err})
			return
		}

		params.Range = &Range

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStream(w, r, hash, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadStream operation middleware
func (siw *ServerInterfaceWrapper) HeadStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params HeadStreamParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Optional query parameter "index" -------------

	err = runtime.BindQueryParameter("form", true, false, "index", r.URL.Query(), &params.Index)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadStream(w, r, hash, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTorrents operation middleware
func (siw *ServerInterfaceWrapper) ListTorrents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTorrentsParams

	// ------------- Optional query parameter "categories" -------------

	err = runtime.BindQueryParameter("form", false, false, "categories", r.URL.Query(), &params.Categories)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categories", Err: err})
		return
	}

	// ------------- Optional query parameter "hashes" -------------

	err = runtime.BindQueryParameter("form", false, false, "hashes", r.URL.Query(), &params.Hashes)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hashes", Err: err})
		return
	}

	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", false, false, "names", r.URL.Query(), &params.Names)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "names", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTorrents(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTorrent operation middleware
func (siw *ServerInterfaceWrapper) AddTorrent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTorrent(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// BackupTorrents operation middleware
func (siw *ServerInterfaceWrapper) BackupTorrents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BackupTorrents(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreTorrents operation middleware
func (siw *ServerInterfaceWrapper) RestoreTorrents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreTorrents(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTorrent operation middleware
func (siw *ServerInterfaceWrapper) DeleteTorrent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTorrent(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTorrent operation middleware
func (siw *ServerInterfaceWrapper) GetTorrent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTorrent(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTorrent operation middleware
func (siw *ServerInterfaceWrapper) UpdateTorrent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTorrent(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// QBittorrentAddTorrent operation middleware
func (siw *ServerInterfaceWrapper) QBittorrentAddTorrent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QBittorrentAddTorrent(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSCache operation middleware
func (siw *ServerInterfaceWrapper) TSCache(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSCache(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSEcho operation middleware
func (siw *ServerInterfaceWrapper) TSEcho(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSEcho(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToken operation middleware
func (siw *ServerInterfaceWrapper) GetToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToken(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSPlay operation middleware
func (siw *ServerInterfaceWrapper) TSPlay(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	// ------------- Path parameter "index" -------------
	var index TSIndex

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSPlay(w, r, hash, index)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSSettings operation middleware
func (siw *ServerInterfaceWrapper) TSSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSSettings(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSStream operation middleware
func (siw *ServerInterfaceWrapper) TSStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "filename" -------------
	var filename TSFileName

	err = runtime.BindStyledParameterWithOptions("simple", "filename", chi.URLParam(r, "filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filename", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params TSStreamParams

	// ------------- Required query parameter "link" -------------

	if paramValue := r.URL.Query().Get("link"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "link"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "link", r.URL.Query(), &params.Link)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "link", Err: err})
		return
	}

	// ------------- Optional query parameter "index" -------------

	err = runtime.BindQueryParameter("form", true, false, "index", r.URL.Query(), &params.Index)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// ------------- Optional query parameter "play" -------------

	err = runtime.BindQueryParameter("form", true, false, "play", r.URL.Query(), &params.Play)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "play", Err: err})
		return
	}

	// ------------- Optional query parameter "preload" -------------

	err = runtime.BindQueryParameter("form", true, false, "preload", r.URL.Query(), &params.Preload)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preload", Err: err})
		return
	}

	// ------------- Optional query parameter "stat" -------------

	err = runtime.BindQueryParameter("form", true, false, "stat", r.URL.Query(), &params.Stat)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stat", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSStream(w, r, filename, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSTorrentUpload operation middleware
func (siw *ServerInterfaceWrapper) TSTorrentUpload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSTorrentUpload(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSTorrents operation middleware
func (siw *ServerInterfaceWrapper) TSTorrents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSTorrents(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSViewed operation middleware
func (siw *ServerInterfaceWrapper) TSViewed(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSViewed(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/stats/memory", wrapper.GetMemoryStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/stats/torrents/{hash}", wrapper.GetTorrentStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/info", wrapper.GetSystemInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/logs", wrapper.GetLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/metrics", wrapper.GetSystemMetrics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/playlist", wrapper.GetPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/settings", wrapper.UpdateSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/stream/{hash}", wrapper.GetStream)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/api/v1/stream/{hash}", wrapper.HeadStream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/torrents", wrapper.ListTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/torrents", wrapper.AddTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/torrents/backup", wrapper.BackupTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/torrents/restore", wrapper.RestoreTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/torrents/{hash}", wrapper.DeleteTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/torrents/{hash}", wrapper.GetTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/torrents/{hash}", wrapper.UpdateTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v2/torrents/add", wrapper.QBittorrentAddTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cache", wrapper.TSCache)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/echo", wrapper.TSEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/oauth/token", wrapper.GetToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/play/{hash}/{index}", wrapper.TSPlay)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/settings", wrapper.TSSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stream/{filename}", wrapper.TSStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/torrent/upload", wrapper.TSTorrentUpload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/torrents", wrapper.TSTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/viewed", wrapper.TSViewed)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9eXfbtrPoV8Hhvec0fVcLJUvy8k7Pe46TNE691ZKTtqmfCpGQhJok+CNAy2qev/s9",
	"WEiCJEhRip2kv9t/2ljEMhjMDGbD4JPlED8kAQoYtY4+WSGMoI8YisRfbyFd8v+7iDoRDhkmgXVkTUgU",
	"oYABHMwJWEK67FgtC/MvIWRLq2UF0EfWkcU/WS0rQv+KcYRc64hFMWpZ1FkiH/Jh0QP0Q483tQ+gC4dw",
	"H456B3sQoh6yD92DvZ47H+0PDtzhaGQfDmHPtlp8DoYiPtv/+2i3D2F7ftx+c/tpYD/+p9Wy2Drk41EW",
	"4WBhtayH9oK01Y8+YpDD3HkrAUu/tbEfkojJ9bOldWQtMFvGs45D/C4MoBMRDz90mVx3NxnHenx8bFmn",
	"gYseykgSPwMyB2yJwBx7CKwwW+JA/K1G6oDLAPE2f/Bp/wAkAn9g3u8P4MeUgRkCYUTusYvcFMX/ilG0",
	"znAsmltGpNoty8cB9mNf/FshAQcMLVBkcdDPsI9ZGfRz+MB7gSD2ZygSa5DwUsAIiBCLo6AKHk8MaYRn",
	"uBmgc+RieCFGKgHFP4HQg2sPc9SsE6AAn7kKHPE/M8mN+cReiWQ4GJfzOUUGxFwYEULvcAjmJAIhXOAA",
	"8rZV4BA5sA6Qi+Yw9liT7boStFkEiv/KwYApQji1PQFpKWauxl1X/q/jhwMjGq9hsDDs5Ms1QxRE/KNC",
	"W8Qw9IBDAsbB5/ICUUZTuJYIuijKAJPjmiGb8cF/sNs9u79nBGoyfoM9ZKaxyRIJasqx7QzhYAEoixD0",
	"NWTlRR1vqWitWtyZgKmQHhxGIPbLJDbMMCSioBqAlNZ6RvpS0PwsyGBHkDaKp40wnOHgziSTFgFiwMPB",
	"Hafl9OhJtmoDHLxfw6PIFzMd/Z8H9kMcBUczhpdHTY+n32Pb7o/c4Ica4TIZX3nQgN8xgxETAm4GnTuA",
	"fZ9LPIa8dSWD8nEMBDYjxEMwSGaLkEegaxAc8kPKd3xXSSxBwMGiclY13saJxwwaZOi1OD4AZZBhyrBD",
	"AQ4oQ9DlOym5rGZy3m3jzJIUTiBDCxJhRMtAnBDfh22KuLbDkAvEkZKJdeCkfblknWOPoQhEiMaeFEvo",
	"IfSIi6yjOfQoMoOajWEWVR+tc3LPv962LMyQTw0iIqUfGEVwzf+mbC2odE4i38oWyzWaXRaa8tHnrFT2",
	"r1plY9VOx8M3peQ13gV+quywCRyNJvSDiTyD+G8hivhkFDiQojYOKAooZvgeAR8yZ8mPKLiAnJXywzbd",
	"Q9G4aguVNPsMQn3kspeGJKASQS+hey2Pef6XkkD8nzAMPewIJar7J+Xo0yDhLfk6Brbdsly+QR4VqnZy",
	"GCSqzcAGS/QAnCWMoMONGYGGKCKRaH4PPexqZwiHEbKOADtd/39GaG4dWf/RzQykrvxKu6/FUEL9L2sQ",
	"Sn8BK8hlm5yLRMCBQUAEdBRF91yTeGxZJySYe9jZEQuHOhaO043nghywJabaEjEF0IsQdNcgjBBVR2WC",
	"ksSiS5qgBywUsKdCCCVx5CDT8D9ChlZwPcE+IvFOaBjaAx0NaiSwgphxruAaZoIYztMuZFBfugIAMNnv",
	"qdYs9jgCLnYB3/UIOYgzKxTzeGuQcAOYR8QHMABxKA8/1VPAcRpwIQi9sfhJzrcThnLs8gZiD7nCZPA8",
	"wo8p4COfRGupjWPkIEAZieAC5dlGApMsTfz+FOg6DgA2jQ2I48RRpDjlgrA3JA7c3TglRyIXJDOV+JCS",
	"YTibHAEX7h3CPYSGaDQbzGx3rz8czuZofjgc2b2DQxvO3QN73z40cQ/faDHgE0sS5GYsxIVKfp6xIJsa",
	"tBCHIdamabMMMCn3uPqEAyhOg6K6WgLrqmCsJXYRoLHjIErnsScVVmm0CWF/7DgoZG1httE8BAXDzagw",
	"n8ip2mcoWEgD2NC/Z/cHRoMi6Z0ao5WTA2k1dnv24GC4P6qFZSK+mAfjRjXpmo1iPsZNAGO2JBH+C+1I",
	"zb2c3I/ZEgVMdQOM3KGAi3sfU8oFoLCWxCmk06wOxJMwcR6KuZQxfO4Uko7AoBpJ0EVs8mcURqKIcTku",
	"TvAwIiGKmFLpUQBnHjIYNq/FBz65i6n4J8yNKXUihVWlExXtiJYVQkpXJDIZTuqLkJc1Q2dDtCxf+tSs",
	"o17/QHP0DFpVmtQGtPBGYrKAD/PRmkGKHatlzRCMUMRVNY261bfSTDHlUtfkCblRXzYuEbo+DvT1jQa1",
	"y8s0RTL7EzmMg/ESOndxKBTz3AaHhCaOaOi6mE8Ovatck40SzDBd4rvj/VN9to7olXwva7mPukfhYzZw",
	"KwX91jB/eo7nVyuZu7gRbyeTK2EsxxTwFjnsi3Mtxfzw8FBHvW1wIrYsH1EKTV65t7EPgzbXzwTHyBNY",
	"tc5veem4M0pKHTHJpC25SBNSzjBlE21j8sCd5S0mCiLEIozuDedOHqme2cNtcORKtzbiZoHUnRMNLbf4",
	"oRGppMJffJU6hIFsAmIqXYi6k7483tNRKB+LQc8Uw2HQM3n44T3EHieBHJi9odklXUH+SRQg9XdLKIwb",
	"TxavAyYdjvm945p6Ne9LB15BRqYtuV4SOyyOkAv4OABSShwszG9lHiHgkQVAfO6OZQDMQ/fIM/uIeUfx",
	"GbxAnUWnBU4v3ly2wIfj64sWeH19fXn9fcckiiqZLxlU47eyHMNVLmv+hTLoh4kzNLewVES6kKG2GGUT",
	"v6pGEgMZ2KbtOxeWw5hBE9v+6JEZ9BLrIuaDaI6/MrdCh+F7NGWVciDjW9k0I9tY6DpypjzHahjAAafF",
	"uiiLEKdTOUx1YEwtiJtPKykxhAKZ5xh7f29/0DvgaqkOwGiwEQTBLFNhiNHNnCvbcSAMq+9zvt1q/VxC",
	"VSLgJE4MabWjVasf7o0O9u3DXn/LxRcIsUgQue0pICoPuolWr3jD02BOTNFaCSYX1XBGYqaF06RFzJaQ",
	"gRUCMEKK+Lw18GHARfyiTMpcSHuIGTj2wxKxJYoEo8qhuYoMozvkAsgPedkxh04p7Mo6Kg4qt6o8jZCD",
	"mAJHbqK3Bh6BrtxBA+lUz2mMWP2GItKeQU4RalU1oSL9+NuKOin+y4DSK+mzwH+hKl4UFt3n0WK6ozra",
	"W1mEi0NmorqxMmAMKn1m7XF7eo4XcbTJ6IHKZqrTBoRd9dhSBtLU9QJYaSS9Ors4BiLSlPhe5nHgyEMU",
	"s3UzUymZiKwCQVJR5XQz6NwtIuF0SVoXnHRUns8i9Kp7oTYCwXtMVY9pWBsqT2O7pgksEQJQsbXSKTyP",
	"MApcbz01200CnUkbGUt2MeWDSY+b42G+xrJCfSXn8+FD4uboDQV5Jn/uGYBZMhZO5bZNk9hG4bA4uQL8",
	"i8CwtCWUe1ED4MA+tHULbjjcG2qs0TMxokcW04SbSto6WaQu9cxCFf6MlsXQA8ubp+IXw+r4FBVK2Fmi",
	"gOURydWwDeEh6pFF50wpNjWxIY8surytEAMcEk4qaGqWP5lakmheKnIoOlXI156tI71n2/YTqyaJK6bo",
	"1DXLyNF+zz44GBm1lQTIfm+wPzjYGw10F8be3nA4GOz1TRALc3KJoDsNUeSggBm13+ukFchagXvoxQi8",
	"GNrtnm1/nwP1sIA4DZhhnT01ldzX0Jg6kY2NHovxmjLkJ6qE5qGDrhshKoJcHwV7HnW7vf5+x+7YnZ5g",
	"NKuV/n7Y7/RGB51ep2fb8ttty5rF2HOnXFe3jqy+bY/adq9t94Xt7Atj1oK9Wd/Z42Z3HEqr4GAkzP17",
	"FFGJ0h6fUXix8qdHBl6Vie1hylAg4olJ4xzyd1xW88ChjoCSeIUMgdUSSYVCtBQecSdC3LTLS4Mc8krT",
	"Jtgs2SyYAfktTW3UvF0p5su+tNBsoOmHvGzD+Y8ihwRuHrNqE0vsV6bndJ/rJouQhyBFQDUGLyjyYcCw",
	"k/yCg0WerxTVbLIOMyLKbVaK0hQXGaC3lTx0jliEHVq2/jfagpUejEyr1bROdfIWJLAJuYleMqUhMnmX",
	"lVGbNAOiWSpTuQhTu5ufq783GI72G21vHDaYXzbaavYGk2+0vwrYKQBr2ufJ+AQ6S6SF+8vZxDLACRze",
	"UE8NUgGwshq8bJ6Y/OxJxkWkCdhqMSEdi9uiInNH5nFxAkPoYLauYhE5lKNa7eCtKFPoVeqbqHLM1x6w",
	"48wSLwWSzmGYejW4DYkdqUolP6R2utFpJwE7IXHAmnpOykpZ1XqzAGQpcy9wYZQYvp5otq0lWp70Ooug",
	"FqS89H1FImkuRNJmpIBIgSe2W+TPNfIcj+U0yWbUBjhSSkspII/xAqKyJZi5ocYfo3GCceMLHKBMc7eh",
	"t2UrH8upW+VwEKZ/0Z1Rr8JXkdDzeDBa1lWESZTKhizT3DR7qNqCF0u84DjDFPjCfhHGEQxYXl3obeU+",
	"OeWHRUoY2Y6ZSUMjyjraiESzeuJAgTFE7IKQUCG6NmC8HsESArNNwyFzUcDwHBcsbnEeG/1bDJrMeJUb",
	"XAuwvdV2RElOvZyxJdBk3otqB5a2E9UeK3HmjY12c8FonZPk3PsMj3q6bwYEGBanVIZj132DpQlX8OPK",
	"LF6TL1x9EWCTaAED/Bc3mxJlKa97qFxfk0dJzWtWZcRdjtxIL2SoO3fb43s9zlMdCpdRaUO0//pMZEtA",
	"BsHN9ak4bkVTgP2Se4ybefSo21W/iPRZ2brzZ7gwR66YaYmvpGMMiM/SBVjhJc7u6uj+MZHxo3nIepsU",
	"M4Hp2zoy4DSQpK1Dz7ucW0cfGzkLBPE8torUg926exSfwb7YxKy3+lKa6NtpXiQM4AL52uUbc2zOaHI6",
	"Ku0oSVHWfX7Q5VLfjUhotayFiAR7mDJxE8PPewFl07KZ3oz/Kimnmu+S8HLhchKkaDRoo8AhrnDZZkwG",
	"0tTRdPTfXi1Gv34YxrO99/Gv/Zu/LiZh77e3x6Oz9aHt+G/+hP336zP/cPXbhyGGv1zbs713698+DO0z",
	"/+J+NiGD85ODH0ywJeYNCZCiwcLx5YdsrVxkIrNXBCI7eQaxywN/IwYTJ1SvyTWfm+uzPETPejmnWkBe",
	"adIQFKTl50pHCoWFPXVnOSXNlN8whlnIm3McB2EGqZ4voCmuTcRuHvjX8l9AMM1mP5CUCLUCVbd1txKo",
	"MqPATLF10qvKSJ5hNo2UT7FWyFTKifKHDY6iV1t6iOz+wLbtjp6w4JJ45iGzli/tWAGIChtOlVdRgzZr",
	"pMJjxjyNceZm4MIUQUcF4AyX/JoZlcXz1ODnfW4XjiGeBF3kpiGcBha4OcY3Kdw73nyl+OsIFnVRb5sF",
	"qy7Incp07Ga9qNKYzF+mCiKj7z/JXGo40/YirXpLkqDQFugpOmYLTFaQjyVXqaqHoNNhK7mhntus8ka0",
	"0puPGkZ1/CW4Kaxro39W6ozvMVoht4nKeI/RCjC4eGJFUWYJcqVQaYi3FZbSNE0/KW9PIlEaHVvpdmij",
	"mo+yBDkNvLYadqoOoqdZREPYyR0KtF3NQ7KIYMCm5mzzyRIB8V0mmoNzdbHuuySl/Tt999I8d9OuVefR",
	"80liiqLvKEgaVebPp9yp/bZFPrs2VdLInMdej3YNZdpsLRMCSruQkU+RXxxE6VTc2zAD/u7DBMhW8nZH",
	"HnK0frec/ejgS/zu9Oav094FPqWnwfXQOTkdnd6Fv7w/eXfYQet3Paf/fj3z37DfxqejU//N3eyDF5/i",
	"FYYf3tinf5KHi8nr/vmf58PzV6fr+c+d8dz76WF1/W58jn766U3/58lgvgrP0bv53ujq8m60fvd+Ct2f",
	"KV0NjXcL0EOII0SnuGJRHp6jQjQ0SV+tXOveyK6I79+hoIaS+RcZIuQjgmNvBdcUfPdS3JX4Lo9O+WMD",
	"5VfbtRwEZhKQ+dnbasHHrit04AZNb0IRhS37IFRsfGrK1PmQhNLTq6OQAuhKy1d8oCJKWwys9wdtu9fu",
	"DSc9+2jPPrLt3xomGkuRVZN+ID6L22UQB6UobnMNNOeWaah7jt8et3uVpSXAi9Kt4u+/iLn8Be63m4Xm",
	"ZYQXOIBeriZK6hGJiJ+/UNtEDcbIQVNnm/AcqMke7Q16B0Y1VkxjztUqBOuqQy79Ub83aBYOlXnI5vnk",
	"qsQ0ZA6g5ykSN865t9/rHQ7tg8FBw0QBt5K1zyBl4mZAib994uI5LmfLZEzdOxoMt2Bqs24iXTWZhisZ",
	"P4esPEFUKKeZJDRkbYexTG2ErsgjhSDgClhGKl/amf+PYMkLFkUEVX6+kpX7tP49DRlq4N9/zw394qNE",
	"kN0+FDj6/x9h+6/j9m/99v7tp73+4/ffUBRFZW/u4EmT/R5vW5l30Urz10v3PpNoHIkKOdJfOZJTpVT9",
	"E7r7MkS3Dan9HWJ+uSzfyk2UaYP56xnlg0XdM5+6S2Zcs7xq8XYCXrzCHNBZzJALuKAFE/7t+wZXHJRE",
	"VvV61Iyv3k6EB1jNj8P7UTUAp1f3o80pL8Z5eFd9otB0BSiZ5+r1L+DFFUIReP3gLGGw2H19V69/0adl",
	"Tlg97eTkiu9TgISDh+465eTkSp8yZjVTxpMr8OIcOxEBkwgGVFy1uIoIIw7xdl70zeQqF1+IIEPTipvM",
	"aZCBNwKikTHSAGzgIxhQEAeiUfkacn2eC6IMzjxMl8idciTTaYiiJDHUbHX7pTKi2iD6Tgk4TTIgVzHU",
	"nK0bRmiOoqmsNjIls3lMZf6zKSVH1mUSN/lIzBaEy3wNju+AKloCZggkQxUQVXn9iKLa9DMCeAMA51w0",
	"a1efmg2e+HRDhCI6XeLFcrqCxvOAI55/B+K7uFeYilnNtOLj1KBdx/vIrnGF15HmTfgEhLnXGwz3cyUz",
	"7IapPZoHwJyDoa4mwmp7wavI1hPda5L1+of9QW9/2N86Xc9sh7+EtFyX1HRYmiuxtizzbbg3secB/mlT",
	"lWLDTN36Ce+Fy7ze5SRngxR43FKVPXY3SYPYE1ULCodahVbgJXmIqf+WLeu0BL7hysFmKEwsfSCCzYRF",
	"Li3ReTMaM++NqPy3xf5U7IDBFEUic4Ajif9fyAdIFfpbQEgg/UMcZDtjqLWpI1VVo1Uz12BzvDEKLa9g",
	"J2qyuIWA2RrAwE2CRzBwUGUBASHe6q7pZVegVR0B0aNjdLII/p6KGpdulXtHSjXZBrgx3wRwjyI812rm",
	"NPDnyKkiBDdMJDK/hQPOxfRu68GnFalP2djiiFROWI6iGHrpbiT+vu2mjCmax17FzDfiozRiiitMd2an",
	"+fjHwEVu/cRJq6eCYBVhxozRHG0TVSORx7PtLqq+FauaaDv1WZM5yzi4qydI2WQ3itSGV/tVuUOlabbZ",
	"FH2eFaTmewLi99w8L9xY3qYTpcTiIEAooZHvt5t5Az2oSXfcoySTvpH/OW2tedcN1Tv6g/7BgfEyYr3+",
	"opRpDgxH1gYhnDQGqrFZ/i6hN5+SEAWbxbpUa3EAeJ827yNuUCHwItHy1ZXH8iw1lTQuihGJhgU0+tuW",
	"nklhaLSVJWBSKOriGTtsagJTcmrXOYL0ckBZV1H5p/YK+FV28ZvMU8tRLzMzW8uyXKnT3HAxvN/JBWyy",
	"7DnzZXFTLl0S0ZrWyr5U59PkRUN+DVHA7b4mxCwaCqIu+jUqQl6mu2JRBNdJ5ElmSqa8nxTCwlFCRarS",
	"XOMwa+4eXzHIKmeZVlfC0UVBXizVrXHqYq7vudMZrLqZpdfTmcHE6t5BISvMuCCkyZS82e5zqqJGZvIo",
	"xkjvArIK6rTXXWtJafZFqybW27O3reCzXay0QLF1N7W2lmzmu84S8QW1P6eal1XpSk13s0paVBmNGl5e",
	"EzMqTkYtp6SAmE7o8glbIQWLsqvM4UYWNXNRns5LakyxxlLuYCwcSdXHTCoWS6XCNCqsNVTT6EfzMFmW",
	"FpfCnwQhtDhnWsKsaLjn03kMTjX+u3A+m6qaf40I2MZsHkakX6TKebFtRk+a6iRuMV4G3rrg9cmOoOeK",
	"mgVo1f43jJwVGEG4tZ04wmw95vCqqxSQYiep3SzWYSgyzJEm7FWRTpe0ln+9SaT0uw+T5MkJMUQh9S4Z",
	"wyHkDqNkDPF6hfxJexcGUSqzehMSCPFPaC0rVWN1jVg4NORbC8iH2OP94jAkEfu/2t5mgyZ1ucAEQf5z",
	"HHkaOWhJEGnBsHJZ7JRL06dtgFbkW6pgUhi0c2edLk887CCVOqogOz+dlODhAlwWie+QaNFVnWiXt+Vb",
	"iyKfXs7HKLrHThVZi0bdNJlcQ8Hx1allLDDEp4Uhto6sPVU9JoRsKQilC0PcFTK6m9lWC1T5KFBqzOQr",
	"hsLAlfEDCqATESruu2XlXpQ8SYpbZQmLaWmEU9c6sn5ETDdOCu+R9G27QSn2ZjXSczZQuVK6/Jwv7WEu",
	"ZvzYsgZ2r2q6FP5urqD8Y8saysXUdzK9LSEYPvZ9yLeKYwwschVc87VbGVyIMlfZr9YtH0Hb9mSTup+4",
	"IvVYt/8CAxTIuvYcFUVvMAQ0RA7XpjPFFAeOF7tZ5VdJMS2lLrYE6QSIrUh0l3qRjaSR80y3cq9gVmTZ",
	"ZE26ImHq8fYZSSp/Kc7wWATJzLcmRNWAPrQXer48HfK+g819C4/HlMmXlfCymXCF/OguEfTkeWMk2JMl",
	"cu4AVvnqmkDHFERxIOunBW6+mnae6t6KGcRAFdKourYXpkACuO7kTmnr6OOtjgM5B3D4JPrKZe2t8qqT",
	"k7JWSKcsiktFcwvYMLKaVjvvGTlGm8XAL+OUJbKHeMRRLPGQLyiyK/kP+odPtpzqZ2IIAecwWAPFrBS0",
	"wXUWcUcPjvBad574XMiRfKEm0wYa84gsJVJLYzB7JG2JgE+ofEIpYHqFTSN5nfHhP5OwGhkkaeH6ctUk",
	"gxqYLCcH/jdwwCus6vvJN6jJRvpZ6b7avYwQ9ESYPuEu1RF4+A6Zg7zJmS1uLdIaMZKUD3x2SZJMZBIm",
	"+VV9w9pcHv+1e3zf6yZvLW9m1gD4e3H2NjM3TjNzJy3AKDfDuJlXyVTbql7Zg9Fb6l8PbT9Ei5vrs6pX",
	"nP7j9S+T872b3wP+j9OLN0ftXksa1r8HTR7KymFkgQIk3378asrYoIlClT6y9pR0J5cOYAWB6GR438uT",
	"INVKT9UaDqnlCCtrqnO5olepKkuUZLLnFCbJHCY5or59yxJER6+OzNwGCheAs6xyXlbvUQeMCT8mEkT4",
	"cA2Uix5ArqmJMmiMAAbvEEDzOXIM8kTOkttNwTovibv+Iht5gVbZGkSRHoGj/OPTjyUqGxizteQo6qbX",
	"39GWy9GQgQIqyUiXA0JYbPIiyJcQCw/hg9kaYKY/hcoFgfgic+siVYxLaNA4QlTWyRfvBaZv0ZseqjcL",
	"EfnM4m4uhNbGdleQNWonn5Vv0FA+i2g4PEebt1ut9Vs+xAa90fPbYJJULggDY8gwnWNp8H8tD0jmC/iU",
	"c51/vH3MOQeM7GIQ5ktjCoSAFkDw9vXxq/TJY3EVUx3tuRjVVpxocpW43xZj3Tbx2LzHLiLZ063y1eNW",
	"Gq8DVBY6Sm4dNH81dbs3UmseRS0/Y2p6sPTfUEX9Euy1NYPUnYB6HfwNnpNQvjqoPTSfi5dkCWNJwEmk",
	"VqWREzCWMTGqnp7nNtwsu7N4+sqgPedeb9yWRZObeDIkjRFtwoeqE2fvrTrIJ/obtD8Tl1oaNLyUbxw+",
	"q/8/h1+jf6m86Vko/++nJor8AZ1qTTYGMZWqOnZd7URTRUzSOokZbftZoUnayo4kRMWhpHOlgdyPXTep",
	"6LKtdaEcDLlHDLJ1c+jvMdRLBQTe2mpZworI+mxTESBNRNCSTlR0VyUK5C/ql6HRcKWDknR56kv7Kmdj",
	"823lbVY2XWG2FNlU0zjCtesUgYA0NUSB03TdrnvQHw6R4zr7DhwO5zN7Npsf9Pb6e+7Bvj3qu7PefOT2",
	"nHTdL/Hiv17Gzt1/vYyDYK2vn4NwJPJRumGw+N8zUZm2hd+/vLxe2T/9uCDHx8fHF+Ob5eubBf/na/6f",
	"lyfHPx8fH5/03h6vTvgPJ7b3+uf314O+f3H3K//h+Nfj4z9PXtonB+Kv8c37y+ufhie/np7+oCHwJV4A",
	"DhaQYD0+Nn4iXC9d9NiqfYm+qEav8vpi8sb8C/6XuP9GlyT2XDATF+8SJeYVpmlldKk/iazgbZ65b1l+",
	"7DHMDbwub91OLlZsu2RZcKg6QCvIihEAXbcDTpaEUARIgACZH/0etMG78eWFygnJF8JNBQJvdZ7AKl5Z",
	"U2m8OuK4CCOhegk3UTeF23KTD6L31CHrOmTIQlPFB5w1FfiMVN3lFQlcMjgUoJW3Tl6A0hOiDATAWb/1",
	"lXXcw82dTkgw97BMRfy6QXR5nBaK6mzSUbuz9EF3o6oq33vPa6VQPsjANSrBH4DiYOFlV13zB7AcQdM4",
	"t9C8ikKoGTmrN+oN1KxWIwH9ynqTgsWE1UYbFyHxYmHy+L7JypBPGhr3TaSJQzDTEVLcOTVAbuuq9KeN",
	"MrlcWbOpuC8mOj42cscq4P/+bti6bWxEKJkn1kXmyx3XyCfC/s0VjNPtzMkSU7DCngegRwmYR4ifXOvy",
	"rZ8Uzu+odj8kT1evBBiZVv40GVyDmsuVSF5YeZoQzdeKzkm05e+nF+ys+rhbTTJQOWGv5AGsy8X7dtPw",
	"6nSabyDt7u/hRjPm6elXGbYKKfp6EQYYSF+rln3QAZeBt1alD4XjbY6R51LgwICbEyq+VhVMfAKSfPoQ",
	"ZKHwazVNpshJL2I0CUd+Ubb56vHNryWAFf1uZID0EO5nhzCUNTHNmtoJ8UPI8Ax7mK0BCtyQ4KC+WGae",
	"8n9+iRlLDdsm/q4t9bXdnvapquNPc4l7DSrqFe8KxZFnuj+b+lN1j2Fiwu+qWxZ5i6EH1g09iIOqdKTL",
	"u06TrKM60/p/TOZ3yWgFL/6VEbO4bMw5Q5XdS9hMa6L4TbxFtxOH1Tzk2gHpZZf0S0yTwFBBYSpzpXpD",
	"9pmyWgpv9RoI7KTmid4veKIUXtJtBuj/JM2spGKVHhR+oROpmSWyFoojkLOsvh/QjB8UvYsrCThYZOzw",
	"u3X50+8WwHNAZcvsKoWJDV5zUJ5CsP7URK6OyyB9ZRPegM6dtpRw6Lrp6xNmUXc5k5WgxFMUoi2IqVCv",
	"lwhcJwkOl6sAReBKvYUBTiIkXj+FHgU/RrAiYWqiXlBoJs4e2qvVqi3Uizjy1Ct922ii2oMohm2+oRxz",
	"GtzierRYvNSY0jcpvqT2rD8fYjzz+X5IKP++vqmKG0xlytOpmQOg6Dj04Fq5pbqfRB7R4y6SqjJvHbg4",
	"Qg7z1iZhdOXB9bOlJk3GlUlH/yTpbZmkFxAG6N8wSa9IjLtIej2Z/nM0WppPSqYmhnjm7GttggojyPAs",
	"9ZcT2Y2y/P/NUrpTqtiJNFV+dxLo/0zRTSKgHtAzCXIRL7+HESYxVWFyMw3vlnE6GZ/h4G4Lwf5zjMQt",
	"wgbtr2SRiSYt5fqbNVZPdDZo+QZ7aJfrVtuyd/H5WJFJEruYdP9Xfpgmwb577KIdOpZZV8piEhXMyjgK",
	"/vH3P/GBl7Fw5sTZQbAkj9LIcuWf5y0tpuoW5UXqjxdTfZajtBFz1KQbbc4R+tLZQAaO/icv6Fv2mO7O",
	"bJ+tYBoe9n4BXbcFIpFT0BIu+e9rWPD51M6UiitdCBPTq+TP5CIlAWryDlSZ91qftnzIW+taCJzcGnBw",
	"mWyLVtjzn+OxGSueC7rJMnN2YcSs+P/nsGHymLFROZaPIj8bn+UfpDaZ88ljLoRbHlIktLjWECV5Rwn4",
	"T892DVmn8G50gzIhDfnm69l6eeLMKGR7Ki2qhFpRwY+3XD7phQOljqgGKkVor04BXywKWHKlOKFoQbmq",
	"ZJ5wFfKBm7CCdPzqQcPjq1NtMD1WWB5TVXjTL5JoBoMJOK0SlQnECPH5C9CVT0ltwPvelmvV9i+/VG3b",
	"yiOODeWS0p6qpsjj7eN/BwAA//8ScAlGZcAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
