// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"log/slog"

	"github.com/anacrolix/torrent/metainfo"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for AuthType.
const (
	Basic  AuthType = "basic"
	Bearer AuthType = "bearer"
)

// Defines values for SettingsLogFormat.
const (
	JSON SettingsLogFormat = "json"
	Text SettingsLogFormat = "text"
)

// Defines values for TSTorrentRequestAction.
const (
	TSTorrentRequestActionAdd  TSTorrentRequestAction = "add"
	TSTorrentRequestActionDrop TSTorrentRequestAction = "drop"
	TSTorrentRequestActionGet  TSTorrentRequestAction = "get"
	TSTorrentRequestActionList TSTorrentRequestAction = "list"
	TSTorrentRequestActionRem  TSTorrentRequestAction = "rem"
)

// Defines values for TSViewedRequestAction.
const (
	TSViewedRequestActionList TSViewedRequestAction = "list"
	TSViewedRequestActionRem  TSViewedRequestAction = "rem"
	TSViewedRequestActionSet  TSViewedRequestAction = "set"
)

// Defines values for TokenRequestGrantType.
const (
	Password TokenRequestGrantType = "password"
)

// Defines values for TorrentStorage.
const (
	File   TorrentStorage = "file"
	Memory TorrentStorage = "memory"
)

// Auth Authentication settings.
type Auth struct {
	// Enabled Enable or disable authentication.
	Enabled *bool `json:"enabled,omitempty"`

	// Password Password for authentication.
	Password *string `json:"password,omitempty"`

	// Type Authentication type.
	Type *AuthType `json:"type,omitempty"`

	// Username Username for authentication.
	Username *string `json:"username,omitempty"`
}

// AuthType Authentication type.
type AuthType string

// Backup defines model for Backup.
type Backup struct {
	Posters  map[string]openapi_types.File `json:"posters"`
	Torrents []Torrent                     `json:"torrents"`
}

// Error defines model for Error.
type Error struct {
	// Code HTTP status code.
	Code int `json:"code"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// ListTorrents List of torrents retrieved successfully.
type ListTorrents struct {
	// Limit Number of torrents returned in this response.
	Limit int `json:"limit"`

	// Offset Pagination offset used.
	Offset   int       `json:"offset"`
	Torrents []Torrent `json:"torrents"`

	// Total Total number of torrents available.
	Total int `json:"total"`
}

// LogEntry defines model for LogEntry.
type LogEntry struct {
	// Data Additional structured data associated with the log entry.
	Data *map[string]interface{} `json:"data,omitempty"`

	// Level The log level (e.g., INFO, WARN, ERROR).
	Level string `json:"level"`

	// Message The log message.
	Message string `json:"message"`

	// Time The timestamp of the log entry.
	Time time.Time `json:"time"`
}

// MemoryStats Global memory usage statistics.
type MemoryStats struct {
	// ActiveTorrents Number of active torrents using memory.
	ActiveTorrents int `json:"active_torrents"`

	// MaxMemory Maximum memory allowed in bytes.
	MaxMemory int64 `json:"max_memory"`

	// TotalPieces Total number of pieces in memory.
	TotalPieces int `json:"total_pieces"`

	// UsedMemory Current memory used in bytes.
	UsedMemory int64 `json:"used_memory"`
}

// PieceInfo Information about a torrent piece that we are actively managing.
type PieceInfo struct {
	// Complete Whether the piece is marked as complete.
	Complete bool `json:"complete"`

	// InMemory Whether the piece data is currently loaded in memory.
	InMemory bool `json:"in_memory"`

	// Index Zero-based piece index within the torrent.
	Index int `json:"index"`

	// Size Piece size in bytes.
	Size int64 `json:"size"`
}

// ReaderInfo Active reader information.
type ReaderInfo struct {
	// End End piece index.
	End int `json:"end"`

	// Reader Reader piece index.
	Reader int `json:"reader"`

	// Start Start piece index.
	Start int `json:"start"`
}

// Settings Application configuration settings.
type Settings struct {
	// Auth Authentication settings.
	Auth *Auth `json:"auth,omitempty"`

	// EnableDlna Enable DLNA media server functionality.
	EnableDlna *bool `json:"enable_dlna,omitempty"`

	// EnableDownloader Enable background downloading for torrents with file storage.
	EnableDownloader *bool `json:"enable_downloader,omitempty"`

	// FileStoragePath Path to the file storage.
	FileStoragePath *string `json:"file_storage_path,omitempty"`

	// FriendlyName DLNA friendly name displayed to clients.
	FriendlyName *string `json:"friendly_name,omitempty"`

	// HTTPServerPort TCP port for HTTP server.
	HTTPServerPort *int `json:"http_server_port,omitempty"`

	// LogFormat Log format.
	LogFormat *SettingsLogFormat `json:"log_format,omitempty"`

	// LogLevel Log level.
	LogLevel *slog.Level `json:"log_level,omitempty"`

	// LogStoreSize Number of log entries to store in memory.
	LogStoreSize *int `json:"log_store_size,omitempty"`

	// MaxMemory Maximum memory allocation for piece storage in bytes.
	MaxMemory *int64 `json:"max_memory,omitempty"`

	// ReadaheadPercentage Readahead percentage value (50-100).
	ReadaheadPercentage *int `json:"readahead_percentage,omitempty"`

	// TorrentClient Torrent client configuration.
	TorrentClient *TorrentClient `json:"torrent_client,omitempty"`

	// TorrentTrackers Torrent trackers used by the torrent client. Each array item is
	// one tracker tier; to include multiple trackers in the same tier,
	// separate them with commas within a single item.
	TorrentTrackers *[]string `json:"torrent_trackers,omitempty"`
}

// SettingsLogFormat Log format.
type SettingsLogFormat string

// SystemInfo defines model for SystemInfo.
type SystemInfo struct {
	// Addresses List of listening addresses.
	Addresses []string `json:"addresses"`

	// BuildDate Date when the build was created.
	BuildDate string `json:"build_date"`

	// Commit Git commit hash.
	Commit string `json:"commit"`

	// Uptime Application uptime in seconds.
	Uptime int64 `json:"uptime"`

	// Version Application release version (semantic versioning).
	Version string `json:"version"`
}

// SystemMetrics defines model for SystemMetrics.
type SystemMetrics struct {
	// ActiveTorrents Total number of torrents loaded in the torrent client.
	ActiveTorrents int `json:"active_torrents"`

	// DownloadSpeed Global download speed in bytes per second.
	DownloadSpeed int64 `json:"download_speed"`

	// UploadSpeed Global upload speed in bytes per second.
	UploadSpeed int64 `json:"upload_speed"`
}

// TSCacheRequest TorrServer cache statistics request.
type TSCacheRequest struct {
	// Hash Torrent info hash.
	Hash string `json:"hash"`
}

// TSCacheResponse TorrServer cache statistics response.
type TSCacheResponse struct {
	// Capacity Total cache capacity in bytes.
	Capacity int64 `json:"Capacity"`

	// Pieces Map of piece indices to piece information.
	Pieces map[string]TSPieceInfo `json:"Pieces"`

	// PiecesCount Total number of pieces.
	PiecesCount int `json:"PiecesCount"`

	// PiecesLength Standard piece length in bytes.
	PiecesLength int64 `json:"PiecesLength"`

	// Readers Active read operations on the cache.
	Readers []ReaderInfo `json:"Readers"`
}

// TSPieceInfo TorrServer piece information.
type TSPieceInfo struct {
	// Completed Whether the piece is complete.
	Completed bool `json:"Completed"`

	// ID Piece index.
	ID int `json:"Id"`

	// Length Piece size in bytes.
	Length int64 `json:"Length"`

	// Priority Piece priority (higher is more important).
	Priority *int `json:"Priority,omitempty"`
}

// TSSettings TorrServer settings.
type TSSettings struct {
	// CacheSize Maximum memory for cache in bytes.
	CacheSize *int64 `json:"CacheSize,omitempty"`
}

// TSTorrentAddFile defines model for TSTorrentAddFile.
type TSTorrentAddFile struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// File Torrent file.
	File openapi_types.File `json:"file"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// TSTorrentFileStat defines model for TSTorrentFileStat.
type TSTorrentFileStat struct {
	// ID File index.
	ID int `json:"id"`

	// Length File size in bytes.
	Length int64 `json:"length"`

	// Name Base name of the file.
	Name string `json:"name"`

	// Path Full path of the file within the torrent.
	Path string `json:"path"`

	// ViewedAt When the file was last viewed.
	ViewedAt *time.Time `json:"viewed_at"`
}

// TSTorrentRequest TorrServer torrent management request.
type TSTorrentRequest struct {
	// Action Action to perform.
	Action TSTorrentRequestAction `json:"action"`

	// Category Category for the torrent.
	Category *string `json:"category,omitempty"`

	// Data Base64-encoded torrent file data.
	Data *string                `json:"data,omitempty"`
	Hash *TSTorrentRequest_Hash `json:"hash,omitempty"`

	// Link Magnet link or URL.
	Link *string `json:"link,omitempty"`

	// Poster Poster image URL or data URI.
	Poster *string `json:"poster,omitempty"`

	// SaveToDB Save torrent to database.
	SaveToDB *bool `json:"save_to_db,omitempty"`

	// Title Display title.
	Title *string `json:"title,omitempty"`
}

// TSTorrentRequestAction Action to perform.
type TSTorrentRequestAction string

// TSTorrentRequestHash0 Empty value is allowed.
type TSTorrentRequestHash0 = string

// TSTorrentRequestHash1 Torrent info hash.
type TSTorrentRequestHash1 = string

// TSTorrentRequest_Hash defines model for TSTorrentRequest.Hash.
type TSTorrentRequest_Hash struct {
	union json.RawMessage
}

// TSTorrentResponse defines model for TSTorrentResponse.
type TSTorrentResponse struct {
	// ActivePeers Number of currently active peers.
	ActivePeers int     `json:"active_peers"`
	BitRate     *string `json:"bit_rate,omitempty"`

	// BytesHashed Total bytes hashed during verification.
	BytesHashed int64 `json:"bytes_hashed"`

	// BytesRead Total bytes read from disk.
	BytesRead int64 `json:"bytes_read"`

	// BytesReadData Bytes read that contain actual torrent data.
	BytesReadData int64 `json:"bytes_read_data"`

	// BytesReadUsefulData Useful data bytes read from peers.
	BytesReadUsefulData int64 `json:"bytes_read_useful_data"`

	// BytesReadUsefulIntendedData Useful intended data bytes read from peers.
	BytesReadUsefulIntendedData int64 `json:"bytes_read_useful_intended_data"`

	// BytesWritten Total bytes written to disk.
	BytesWritten int64 `json:"bytes_written"`

	// BytesWrittenData Torrent data bytes written to disk.
	BytesWrittenData int64   `json:"bytes_written_data"`
	Category         *string `json:"category,omitempty"`

	// ChunksRead Total chunks read from disk.
	ChunksRead int64 `json:"chunks_read"`

	// ChunksReadUseful Useful chunks read from peers.
	ChunksReadUseful int64 `json:"chunks_read_useful"`

	// ChunksReadWasted Wasted chunks read (duplicate or unneeded data).
	ChunksReadWasted int64 `json:"chunks_read_wasted"`

	// ChunksWritten Total chunks written to disk.
	ChunksWritten int64 `json:"chunks_written"`

	// CompletedSize Total size of completed pieces in bytes.
	CompletedSize int64 `json:"completed_size"`

	// ConnectedSeeders Number of connected seeders.
	ConnectedSeeders int     `json:"connected_seeders"`
	Data             *string `json:"data,omitempty"`

	// DownloadSpeed Download speed in bytes per second.
	DownloadSpeed   float64  `json:"download_speed"`
	DurationSeconds *float32 `json:"duration_seconds,omitempty"`

	// FileStats Statistics for each file in the torrent.
	FileStats *[]TSTorrentFileStat `json:"file_stats,omitempty"`

	// HalfOpenPeers Number of peers in half-open state (connecting).
	HalfOpenPeers int `json:"half_open_peers"`

	// Hash Torrent info hash.
	Hash string `json:"hash"`

	// InMemory Number of pieces currently loaded in memory.
	InMemory int `json:"in_memory"`

	// InMemorySize Total size of pieces currently in memory in bytes.
	InMemorySize int64 `json:"in_memory_size"`
	LoadedSize   int64 `json:"loaded_size"`

	// MemoryStats Global memory usage statistics.
	MemoryStats MemoryStats `json:"memory_stats"`

	// MemoryUsagePercentage Percentage of maximum memory used by this torrent (0-100).
	MemoryUsagePercentage float64 `json:"memory_usage_percentage"`

	// MetadataChunksRead Metadata chunks read.
	MetadataChunksRead int64 `json:"metadata_chunks_read"`

	// Name Torrent name.
	Name string `json:"name"`

	// PendingPeers Number of pending peer connections.
	PendingPeers int `json:"pending_peers"`

	// Pieces Array of all managed pieces with their current status.
	Pieces []PieceInfo `json:"pieces"`

	// PiecesComplete Number of completed pieces.
	PiecesComplete int `json:"pieces_complete"`

	// PiecesDirtiedBad Pieces marked as bad after verification.
	PiecesDirtiedBad int64 `json:"pieces_dirtied_bad"`

	// PiecesDirtiedGood Pieces marked as good after verification.
	PiecesDirtiedGood int64 `json:"pieces_dirtied_good"`

	// Poster Poster image URL or data URI.
	Poster         *string `json:"poster,omitempty"`
	PreloadSize    int64   `json:"preload_size"`
	PreloadedBytes int64   `json:"preloaded_bytes"`

	// Readers Active read stream positions for this torrent.
	Readers    *[]ReaderInfo `json:"readers,omitempty"`
	Stat       int           `json:"stat"`
	StatString string        `json:"stat_string"`
	Timestamp  int64         `json:"timestamp"`

	// Title Display title.
	Title       string `json:"title"`
	TorrentSize int64  `json:"torrent_size"`

	// TotalPeers Total number of known peers.
	TotalPeers int `json:"total_peers"`

	// TotalPieces Total number of pieces in the torrent, from metadata.
	TotalPieces int `json:"total_pieces"`

	// TotalSize Total size of all managed pieces in bytes.
	TotalSize   int64   `json:"total_size"`
	UploadSpeed float32 `json:"upload_speed"`
}

// TSViewedRequest TorrServer view tag request.
type TSViewedRequest struct {
	// Action Action to perform.
	Action    TSViewedRequestAction `json:"action"`
	FileIndex int                   `json:"file_index"`
	Hash      string                `json:"hash"`
}

// TSViewedRequestAction Action to perform.
type TSViewedRequestAction string

// TSViewedResponse TorrServer view tag response.
type TSViewedResponse struct {
	FileIndex int    `json:"file_index"`
	Hash      string `json:"hash"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	// GrantType The grant type. Must be 'password'.
	GrantType TokenRequestGrantType `json:"grant_type"`

	// Password The user's password.
	Password string `json:"password"`

	// Username The user's username.
	Username string `json:"username"`
}

// TokenRequestGrantType The grant type. Must be 'password'.
type TokenRequestGrantType string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken The JWT access token.
	AccessToken string `json:"access_token"`

	// ExpiresIn The lifetime in seconds of the access token.
	ExpiresIn *int `json:"expires_in,omitempty"`

	// TokenType The type of token. Always 'Bearer'.
	TokenType string `json:"token_type"`
}

// Torrent defines model for Torrent.
type Torrent struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// CreatedAt When the torrent was added to the system.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Files List of files contained in the torrent.
	Files []TorrentFile `json:"files"`

	// Hash SHA-1 info hash of the torrent (40 hex characters).
	Hash metainfo.Hash `json:"hash"`

	// Magnet Magnet URI.
	Magnet string `json:"magnet"`

	// Name Original name of the torrent from metadata.
	Name string `json:"name"`

	// PieceCount Total number of pieces in the torrent.
	PieceCount int `json:"piece_count"`

	// PieceSize Standard piece size in bytes.
	PieceSize *int64 `json:"piece_size,omitempty"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`

	// TotalSize Total size of all files in bytes.
	TotalSize int64 `json:"total_size"`

	// UpdatedAt Last time the torrent was modified.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TorrentAdd Input for adding a new torrent.
type TorrentAdd struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// Hash SHA-1 info hash of the torrent (40 hex characters).
	Hash *metainfo.Hash `json:"hash,omitempty"`

	// Magnet Magnet URI.
	Magnet *string `json:"magnet,omitempty"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// TorrentAddFile defines model for TorrentAddFile.
type TorrentAddFile struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// File Torrent file.
	File openapi_types.File `json:"file"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// TorrentClient Torrent client configuration.
type TorrentClient struct {
	// DisableDHT Disable DHT (Distributed Hash Table).
	DisableDHT *bool `json:"disable_dht,omitempty"`

	// DisableIPv6 Disable IPv6.
	DisableIPv6 *bool `json:"disable_ipv6,omitempty"`

	// DisablePEX Disable PEX (Peer Exchange).
	DisablePEX *bool `json:"disable_pex,omitempty"`

	// DisableTCP Disable TCP connections.
	DisableTCP *bool `json:"disable_tcp,omitempty"`

	// DisableUTP Disable uTP (Micro Transport Protocol).
	DisableUTP *bool `json:"disable_utp,omitempty"`

	// DownloadRateLimit Download rate limit in bytes per second. 0 means unlimited.
	DownloadRateLimit *int `json:"download_rate_limit,omitempty"`

	// EstablishedConnsPerTorrent The maximum number of established connections per torrent.
	EstablishedConnsPerTorrent *int `json:"established_conns_per_torrent,omitempty"`

	// PreferHeaderObfuscation Request that outgoing connections' headers be obfuscated.
	PreferHeaderObfuscation *bool `json:"prefer_header_obfuscation,omitempty"`

	// Seed Whether to seed after downloading.
	Seed *bool `json:"seed,omitempty"`

	// TorrentPeersHighWater The high water mark for the number of peers per torrent.
	TorrentPeersHighWater *int `json:"torrent_peers_high_water,omitempty"`

	// UploadRateLimit Upload rate limit in bytes per second. 0 means unlimited.
	UploadRateLimit *int `json:"upload_rate_limit,omitempty"`
}

// TorrentFile File within a torrent.
type TorrentFile struct {
	// Length File size in bytes.
	Length int64 `json:"length"`

	// Name Base name of the file.
	Name string `json:"name"`

	// Path Full path of the file within the torrent.
	Path string `json:"path"`

	// ViewedAt When the file was last viewed.
	ViewedAt *time.Time `json:"viewed_at"`
}

// TorrentFileUpdate Metadata for updating a file within a torrent.
type TorrentFileUpdate struct {
	// Path The full path of the file within the torrent.
	Path string `json:"path"`

	// Viewed Set to true to mark as viewed, false to mark as unviewed.
	Viewed bool `json:"viewed"`
}

// TorrentStats Statistics about torrent activity and performance.
type TorrentStats struct {
	// ActivePeers Number of currently active peers.
	ActivePeers int `json:"active_peers"`

	// BytesHashed Total bytes hashed during verification.
	BytesHashed int64 `json:"bytes_hashed"`

	// BytesRead Total bytes read from disk.
	BytesRead int64 `json:"bytes_read"`

	// BytesReadData Bytes read that contain actual torrent data.
	BytesReadData int64 `json:"bytes_read_data"`

	// BytesReadUsefulData Useful data bytes read from peers.
	BytesReadUsefulData int64 `json:"bytes_read_useful_data"`

	// BytesReadUsefulIntendedData Useful intended data bytes read from peers.
	BytesReadUsefulIntendedData int64 `json:"bytes_read_useful_intended_data"`

	// BytesWritten Total bytes written to disk.
	BytesWritten int64 `json:"bytes_written"`

	// BytesWrittenData Torrent data bytes written to disk.
	BytesWrittenData int64 `json:"bytes_written_data"`

	// ChunksRead Total chunks read from disk.
	ChunksRead int64 `json:"chunks_read"`

	// ChunksReadUseful Useful chunks read from peers.
	ChunksReadUseful int64 `json:"chunks_read_useful"`

	// ChunksReadWasted Wasted chunks read (duplicate or unneeded data).
	ChunksReadWasted int64 `json:"chunks_read_wasted"`

	// ChunksWritten Total chunks written to disk.
	ChunksWritten int64 `json:"chunks_written"`

	// CompletedSize Total size of completed pieces in bytes.
	CompletedSize int64 `json:"completed_size"`

	// ConnectedSeeders Number of connected seeders.
	ConnectedSeeders int `json:"connected_seeders"`

	// HalfOpenPeers Number of peers in half-open state (connecting).
	HalfOpenPeers int `json:"half_open_peers"`

	// InMemory Number of pieces currently loaded in memory.
	InMemory int `json:"in_memory"`

	// InMemorySize Total size of pieces currently in memory in bytes.
	InMemorySize int64 `json:"in_memory_size"`

	// MemoryStats Global memory usage statistics.
	MemoryStats MemoryStats `json:"memory_stats"`

	// MemoryUsagePercentage Percentage of maximum memory used by this torrent (0-100).
	MemoryUsagePercentage float64 `json:"memory_usage_percentage"`

	// MetadataChunksRead Metadata chunks read.
	MetadataChunksRead int64 `json:"metadata_chunks_read"`

	// PendingPeers Number of pending peer connections.
	PendingPeers int `json:"pending_peers"`

	// Pieces Array of all managed pieces with their current status.
	Pieces []PieceInfo `json:"pieces"`

	// PiecesComplete Number of completed pieces.
	PiecesComplete int `json:"pieces_complete"`

	// PiecesDirtiedBad Pieces marked as bad after verification.
	PiecesDirtiedBad int64 `json:"pieces_dirtied_bad"`

	// PiecesDirtiedGood Pieces marked as good after verification.
	PiecesDirtiedGood int64 `json:"pieces_dirtied_good"`

	// Readers Active read stream positions for this torrent.
	Readers *[]ReaderInfo `json:"readers,omitempty"`

	// TotalPeers Total number of known peers.
	TotalPeers int `json:"total_peers"`

	// TotalPieces Total number of pieces in the torrent, from metadata.
	TotalPieces int `json:"total_pieces"`

	// TotalSize Total size of all managed pieces in bytes.
	TotalSize int64 `json:"total_size"`
}

// TorrentStorage Use memory or file storage.
type TorrentStorage string

// TorrentUpdate Updateable torrent metadata.
type TorrentUpdate struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// Files List of files to update within the torrent.
	Files *[]TorrentFileUpdate `json:"files,omitempty"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// Hash defines model for Hash.
type Hash = metainfo.Hash

// Index defines model for Index.
type Index = int

// Limit defines model for Limit.
type Limit = int

// MediaName defines model for MediaName.
type MediaName = string

// Offset defines model for Offset.
type Offset = int

// Path defines model for Path.
type Path = string

// Range defines model for Range.
type Range = string

// TSFileName defines model for TSFileName.
type TSFileName = string

// TSIndex defines model for TSIndex.
type TSIndex = int

// TSIndexQuery defines model for TSIndexQuery.
type TSIndexQuery = int

// TSLink defines model for TSLink.
type TSLink = string

// TSPlay defines model for TSPlay.
type TSPlay = bool

// TSPreload defines model for TSPreload.
type TSPreload = bool

// TSStat defines model for TSStat.
type TSStat = bool

// TorrentCategories defines model for TorrentCategories.
type TorrentCategories = []string

// TorrentHashes defines model for TorrentHashes.
type TorrentHashes = []metainfo.Hash

// TorrentNames defines model for TorrentNames.
type TorrentNames = []string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// GatewayTimeout defines model for GatewayTimeout.
type GatewayTimeout = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetPlaylistParams defines parameters for GetPlaylist.
type GetPlaylistParams struct {
	// Name Media playlist by torrent name.
	Name *MediaName `form:"name,omitempty" json:"name,omitempty"`
}

// GetStreamParams defines parameters for GetStream.
type GetStreamParams struct {
	// Path Path to a torrent file. One of `path` or `index` must be provided.
	Path *Path `form:"path,omitempty" json:"path,omitempty"`

	// Index Index of the file within the torrent. One of `path` or `index` must be provided.
	Index *Index `form:"index,omitempty" json:"index,omitempty"`

	// Range Bytes range for partial content requests.
	Range *Range `json:"Range,omitempty"`
}

// HeadStreamParams defines parameters for HeadStream.
type HeadStreamParams struct {
	// Path Path to a torrent file. One of `path` or `index` must be provided.
	Path *Path `form:"path,omitempty" json:"path,omitempty"`

	// Index Index of the file within the torrent. One of `path` or `index` must be provided.
	Index *Index `form:"index,omitempty" json:"index,omitempty"`
}

// ListTorrentsParams defines parameters for ListTorrents.
type ListTorrentsParams struct {
	// Categories Comma-separated list of torrent categories to filter results.
	Categories *TorrentCategories `form:"categories,omitempty" json:"categories,omitempty"`

	// Hashes Comma-separated list of torrent info hashes to filter results.
	Hashes *TorrentHashes `form:"hashes,omitempty" json:"hashes,omitempty"`

	// Names Comma-separated list of torrent names to filter results. The filter performs case-insensitive matching against torrent names.
	Names *TorrentNames `form:"names,omitempty" json:"names,omitempty"`

	// Limit Maximum number of torrents to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of torrents to skip for pagination.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// RestoreTorrentsMultipartBody defines parameters for RestoreTorrents.
type RestoreTorrentsMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// QBittorrentAddTorrentMultipartBody defines parameters for QBittorrentAddTorrent.
type QBittorrentAddTorrentMultipartBody struct {
	// Category Category for the torrent.
	Category *string               `json:"category,omitempty"`
	Torrents *[]openapi_types.File `json:"torrents,omitempty"`

	// Urls A list of magnet links to add.
	Urls *string `json:"urls,omitempty"`
}

// TSStreamParams defines parameters for TSStream.
type TSStreamParams struct {
	// Link Magnet link or info hash of the torrent.
	Link TSLink `form:"link" json:"link"`

	// Index File index within the torrent.
	Index *TSIndexQuery `form:"index,omitempty" json:"index,omitempty"`

	// Play Start playback immediately.
	Play *TSPlay `form:"play,omitempty" json:"play,omitempty"`

	// Preload Preload content without playing.
	Preload *TSPreload `form:"preload,omitempty" json:"preload,omitempty"`

	// Stat Return statistics instead of streaming.
	Stat *TSStat `form:"stat,omitempty" json:"stat,omitempty"`
}

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = Settings

// AddTorrentJSONRequestBody defines body for AddTorrent for application/json ContentType.
type AddTorrentJSONRequestBody = TorrentAdd

// AddTorrentMultipartRequestBody defines body for AddTorrent for multipart/form-data ContentType.
type AddTorrentMultipartRequestBody = TorrentAddFile

// RestoreTorrentsMultipartRequestBody defines body for RestoreTorrents for multipart/form-data ContentType.
type RestoreTorrentsMultipartRequestBody RestoreTorrentsMultipartBody

// UpdateTorrentJSONRequestBody defines body for UpdateTorrent for application/json ContentType.
type UpdateTorrentJSONRequestBody = TorrentUpdate

// QBittorrentAddTorrentMultipartRequestBody defines body for QBittorrentAddTorrent for multipart/form-data ContentType.
type QBittorrentAddTorrentMultipartRequestBody QBittorrentAddTorrentMultipartBody

// TSCacheJSONRequestBody defines body for TSCache for application/json ContentType.
type TSCacheJSONRequestBody = TSCacheRequest

// GetTokenFormdataRequestBody defines body for GetToken for application/x-www-form-urlencoded ContentType.
type GetTokenFormdataRequestBody = TokenRequest

// TSSettingsJSONRequestBody defines body for TSSettings for application/json ContentType.
type TSSettingsJSONRequestBody = TSSettings

// TSTorrentUploadMultipartRequestBody defines body for TSTorrentUpload for multipart/form-data ContentType.
type TSTorrentUploadMultipartRequestBody = TSTorrentAddFile

// TSTorrentsJSONRequestBody defines body for TSTorrents for application/json ContentType.
type TSTorrentsJSONRequestBody = TSTorrentRequest

// TSViewedJSONRequestBody defines body for TSViewed for application/json ContentType.
type TSViewedJSONRequestBody = TSViewedRequest

// AsTSTorrentRequestHash0 returns the union data inside the TSTorrentRequest_Hash as a TSTorrentRequestHash0
func (t TSTorrentRequest_Hash) AsTSTorrentRequestHash0() (TSTorrentRequestHash0, error) {
	var body TSTorrentRequestHash0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTSTorrentRequestHash0 overwrites any union data inside the TSTorrentRequest_Hash as the provided TSTorrentRequestHash0
func (t *TSTorrentRequest_Hash) FromTSTorrentRequestHash0(v TSTorrentRequestHash0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTSTorrentRequestHash0 performs a merge with any union data inside the TSTorrentRequest_Hash, using the provided TSTorrentRequestHash0
func (t *TSTorrentRequest_Hash) MergeTSTorrentRequestHash0(v TSTorrentRequestHash0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTSTorrentRequestHash1 returns the union data inside the TSTorrentRequest_Hash as a TSTorrentRequestHash1
func (t TSTorrentRequest_Hash) AsTSTorrentRequestHash1() (TSTorrentRequestHash1, error) {
	var body TSTorrentRequestHash1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTSTorrentRequestHash1 overwrites any union data inside the TSTorrentRequest_Hash as the provided TSTorrentRequestHash1
func (t *TSTorrentRequest_Hash) FromTSTorrentRequestHash1(v TSTorrentRequestHash1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTSTorrentRequestHash1 performs a merge with any union data inside the TSTorrentRequest_Hash, using the provided TSTorrentRequestHash1
func (t *TSTorrentRequest_Hash) MergeTSTorrentRequestHash1(v TSTorrentRequestHash1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TSTorrentRequest_Hash) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TSTorrentRequest_Hash) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get global memory statistics.
	// (GET /api/stats/memory)
	GetMemoryStats(w http.ResponseWriter, r *http.Request)
	// Get torrent statistics.
	// (GET /api/stats/torrents/{hash})
	GetTorrentStats(w http.ResponseWriter, r *http.Request, hash Hash)
	// Health check.
	// (GET /api/system/health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Get application information.
	// (GET /api/system/info)
	GetSystemInfo(w http.ResponseWriter, r *http.Request)
	// Get recent application logs.
	// (GET /api/system/logs)
	GetLogs(w http.ResponseWriter, r *http.Request)
	// Get system metrics.
	// (GET /api/system/metrics)
	GetSystemMetrics(w http.ResponseWriter, r *http.Request)
	// Generate a playlist for streaming.
	// (GET /api/v1/playlist)
	GetPlaylist(w http.ResponseWriter, r *http.Request, params GetPlaylistParams)
	// Get application settings.
	// (GET /api/v1/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// Update application settings.
	// (PATCH /api/v1/settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)
	// Stream a torrent file.
	// (GET /api/v1/stream/{hash})
	GetStream(w http.ResponseWriter, r *http.Request, hash Hash, params GetStreamParams)
	// Serve a HEAD request for a streamable torrent file.
	// (HEAD /api/v1/stream/{hash})
	HeadStream(w http.ResponseWriter, r *http.Request, hash Hash, params HeadStreamParams)
	// List all torrents.
	// (GET /api/v1/torrents)
	ListTorrents(w http.ResponseWriter, r *http.Request, params ListTorrentsParams)
	// Add a new torrent.
	// (POST /api/v1/torrents)
	AddTorrent(w http.ResponseWriter, r *http.Request)
	// Backup torrents and posters.
	// (GET /api/v1/torrents/backup)
	BackupTorrents(w http.ResponseWriter, r *http.Request)
	// Restore torrents and posters.
	// (POST /api/v1/torrents/restore)
	RestoreTorrents(w http.ResponseWriter, r *http.Request)
	// Delete a torrent.
	// (DELETE /api/v1/torrents/{hash})
	DeleteTorrent(w http.ResponseWriter, r *http.Request, hash Hash)
	// Get torrent metadata.
	// (GET /api/v1/torrents/{hash})
	GetTorrent(w http.ResponseWriter, r *http.Request, hash Hash)
	// Update torrent metadata.
	// (PATCH /api/v1/torrents/{hash})
	UpdateTorrent(w http.ResponseWriter, r *http.Request, hash Hash)
	// Add a new torrent (qBittorrent compatible).
	// (POST /api/v2/torrents/add)
	QBittorrentAddTorrent(w http.ResponseWriter, r *http.Request)
	// Get cache statistics (TorrServer compatible).
	// (POST /cache)
	TSCache(w http.ResponseWriter, r *http.Request)
	// Server status check (TorrServer compatible).
	// (GET /echo)
	TSEcho(w http.ResponseWriter, r *http.Request)
	// Obtain a JWT token.
	// (POST /oauth/token)
	GetToken(w http.ResponseWriter, r *http.Request)
	// Stream torrent content (TorrServer compatible).
	// (GET /play/{hash}/{index})
	TSPlay(w http.ResponseWriter, r *http.Request, hash Hash, index TSIndex)
	// Update settings (TorrServer compatible).
	// (POST /settings)
	TSSettings(w http.ResponseWriter, r *http.Request)
	// Stream or preload torrent (TorrServer compatible).
	// (GET /stream/{filename})
	TSStream(w http.ResponseWriter, r *http.Request, filename TSFileName, params TSStreamParams)
	// Add a new torrent (TorrServer compatible).
	// (POST /torrent/upload)
	TSTorrentUpload(w http.ResponseWriter, r *http.Request)
	// Manage torrents (TorrServer compatible).
	// (POST /torrents)
	TSTorrents(w http.ResponseWriter, r *http.Request)
	// Manage torrent view tags (TorrServer compatible).
	// (POST /viewed)
	TSViewed(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get global memory statistics.
// (GET /api/stats/memory)
func (_ Unimplemented) GetMemoryStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get torrent statistics.
// (GET /api/stats/torrents/{hash})
func (_ Unimplemented) GetTorrentStats(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check.
// (GET /api/system/health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get application information.
// (GET /api/system/info)
func (_ Unimplemented) GetSystemInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get recent application logs.
// (GET /api/system/logs)
func (_ Unimplemented) GetLogs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get system metrics.
// (GET /api/system/metrics)
func (_ Unimplemented) GetSystemMetrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate a playlist for streaming.
// (GET /api/v1/playlist)
func (_ Unimplemented) GetPlaylist(w http.ResponseWriter, r *http.Request, params GetPlaylistParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get application settings.
// (GET /api/v1/settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update application settings.
// (PATCH /api/v1/settings)
func (_ Unimplemented) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream a torrent file.
// (GET /api/v1/stream/{hash})
func (_ Unimplemented) GetStream(w http.ResponseWriter, r *http.Request, hash Hash, params GetStreamParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Serve a HEAD request for a streamable torrent file.
// (HEAD /api/v1/stream/{hash})
func (_ Unimplemented) HeadStream(w http.ResponseWriter, r *http.Request, hash Hash, params HeadStreamParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all torrents.
// (GET /api/v1/torrents)
func (_ Unimplemented) ListTorrents(w http.ResponseWriter, r *http.Request, params ListTorrentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new torrent.
// (POST /api/v1/torrents)
func (_ Unimplemented) AddTorrent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Backup torrents and posters.
// (GET /api/v1/torrents/backup)
func (_ Unimplemented) BackupTorrents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restore torrents and posters.
// (POST /api/v1/torrents/restore)
func (_ Unimplemented) RestoreTorrents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a torrent.
// (DELETE /api/v1/torrents/{hash})
func (_ Unimplemented) DeleteTorrent(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get torrent metadata.
// (GET /api/v1/torrents/{hash})
func (_ Unimplemented) GetTorrent(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update torrent metadata.
// (PATCH /api/v1/torrents/{hash})
func (_ Unimplemented) UpdateTorrent(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new torrent (qBittorrent compatible).
// (POST /api/v2/torrents/add)
func (_ Unimplemented) QBittorrentAddTorrent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cache statistics (TorrServer compatible).
// (POST /cache)
func (_ Unimplemented) TSCache(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server status check (TorrServer compatible).
// (GET /echo)
func (_ Unimplemented) TSEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Obtain a JWT token.
// (POST /oauth/token)
func (_ Unimplemented) GetToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream torrent content (TorrServer compatible).
// (GET /play/{hash}/{index})
func (_ Unimplemented) TSPlay(w http.ResponseWriter, r *http.Request, hash Hash, index TSIndex) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update settings (TorrServer compatible).
// (POST /settings)
func (_ Unimplemented) TSSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream or preload torrent (TorrServer compatible).
// (GET /stream/{filename})
func (_ Unimplemented) TSStream(w http.ResponseWriter, r *http.Request, filename TSFileName, params TSStreamParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new torrent (TorrServer compatible).
// (POST /torrent/upload)
func (_ Unimplemented) TSTorrentUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Manage torrents (TorrServer compatible).
// (POST /torrents)
func (_ Unimplemented) TSTorrents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Manage torrent view tags (TorrServer compatible).
// (POST /viewed)
func (_ Unimplemented) TSViewed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMemoryStats operation middleware
func (siw *ServerInterfaceWrapper) GetMemoryStats(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemoryStats(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTorrentStats operation middleware
func (siw *ServerInterfaceWrapper) GetTorrentStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTorrentStats(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemInfo operation middleware
func (siw *ServerInterfaceWrapper) GetSystemInfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemInfo(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLogs operation middleware
func (siw *ServerInterfaceWrapper) GetLogs(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogs(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetSystemMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemMetrics(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylist operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlaylistParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylist(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStream operation middleware
func (siw *ServerInterfaceWrapper) GetStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStreamParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Optional query parameter "index" -------------

	err = runtime.BindQueryParameter("form", true, false, "index", r.URL.Query(), &params.Index)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Range" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Range")]; found {
		var Range Range
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Range", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Range", valueList[0], &Range, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Range", Err: err})
			return
		}

		params.Range = &Range

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStream(w, r, hash, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadStream operation middleware
func (siw *ServerInterfaceWrapper) HeadStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params HeadStreamParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Optional query parameter "index" -------------

	err = runtime.BindQueryParameter("form", true, false, "index", r.URL.Query(), &params.Index)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadStream(w, r, hash, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTorrents operation middleware
func (siw *ServerInterfaceWrapper) ListTorrents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTorrentsParams

	// ------------- Optional query parameter "categories" -------------

	err = runtime.BindQueryParameter("form", false, false, "categories", r.URL.Query(), &params.Categories)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categories", Err: err})
		return
	}

	// ------------- Optional query parameter "hashes" -------------

	err = runtime.BindQueryParameter("form", false, false, "hashes", r.URL.Query(), &params.Hashes)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hashes", Err: err})
		return
	}

	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", false, false, "names", r.URL.Query(), &params.Names)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "names", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTorrents(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTorrent operation middleware
func (siw *ServerInterfaceWrapper) AddTorrent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTorrent(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// BackupTorrents operation middleware
func (siw *ServerInterfaceWrapper) BackupTorrents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BackupTorrents(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreTorrents operation middleware
func (siw *ServerInterfaceWrapper) RestoreTorrents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreTorrents(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTorrent operation middleware
func (siw *ServerInterfaceWrapper) DeleteTorrent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTorrent(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTorrent operation middleware
func (siw *ServerInterfaceWrapper) GetTorrent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTorrent(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTorrent operation middleware
func (siw *ServerInterfaceWrapper) UpdateTorrent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTorrent(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// QBittorrentAddTorrent operation middleware
func (siw *ServerInterfaceWrapper) QBittorrentAddTorrent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QBittorrentAddTorrent(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSCache operation middleware
func (siw *ServerInterfaceWrapper) TSCache(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSCache(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSEcho operation middleware
func (siw *ServerInterfaceWrapper) TSEcho(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSEcho(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToken operation middleware
func (siw *ServerInterfaceWrapper) GetToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToken(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSPlay operation middleware
func (siw *ServerInterfaceWrapper) TSPlay(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	// ------------- Path parameter "index" -------------
	var index TSIndex

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSPlay(w, r, hash, index)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSSettings operation middleware
func (siw *ServerInterfaceWrapper) TSSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSSettings(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSStream operation middleware
func (siw *ServerInterfaceWrapper) TSStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "filename" -------------
	var filename TSFileName

	err = runtime.BindStyledParameterWithOptions("simple", "filename", chi.URLParam(r, "filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filename", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params TSStreamParams

	// ------------- Required query parameter "link" -------------

	if paramValue := r.URL.Query().Get("link"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "link"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "link", r.URL.Query(), &params.Link)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "link", Err: err})
		return
	}

	// ------------- Optional query parameter "index" -------------

	err = runtime.BindQueryParameter("form", true, false, "index", r.URL.Query(), &params.Index)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// ------------- Optional query parameter "play" -------------

	err = runtime.BindQueryParameter("form", true, false, "play", r.URL.Query(), &params.Play)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "play", Err: err})
		return
	}

	// ------------- Optional query parameter "preload" -------------

	err = runtime.BindQueryParameter("form", true, false, "preload", r.URL.Query(), &params.Preload)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preload", Err: err})
		return
	}

	// ------------- Optional query parameter "stat" -------------

	err = runtime.BindQueryParameter("form", true, false, "stat", r.URL.Query(), &params.Stat)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stat", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSStream(w, r, filename, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSTorrentUpload operation middleware
func (siw *ServerInterfaceWrapper) TSTorrentUpload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSTorrentUpload(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSTorrents operation middleware
func (siw *ServerInterfaceWrapper) TSTorrents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSTorrents(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSViewed operation middleware
func (siw *ServerInterfaceWrapper) TSViewed(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSViewed(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/stats/memory", wrapper.GetMemoryStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/stats/torrents/{hash}", wrapper.GetTorrentStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/info", wrapper.GetSystemInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/logs", wrapper.GetLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/metrics", wrapper.GetSystemMetrics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/playlist", wrapper.GetPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/settings", wrapper.UpdateSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/stream/{hash}", wrapper.GetStream)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/api/v1/stream/{hash}", wrapper.HeadStream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/torrents", wrapper.ListTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/torrents", wrapper.AddTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/torrents/backup", wrapper.BackupTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/torrents/restore", wrapper.RestoreTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/torrents/{hash}", wrapper.DeleteTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/torrents/{hash}", wrapper.GetTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/torrents/{hash}", wrapper.UpdateTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v2/torrents/add", wrapper.QBittorrentAddTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cache", wrapper.TSCache)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/echo", wrapper.TSEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/oauth/token", wrapper.GetToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/play/{hash}/{index}", wrapper.TSPlay)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/settings", wrapper.TSSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stream/{filename}", wrapper.TSStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/torrent/upload", wrapper.TSTorrentUpload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/torrents", wrapper.TSTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/viewed", wrapper.TSViewed)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9eXfbtrL4V8Hhe+fUudVCyZK8vNPTn+MkjVNvtZWkbeKrC5GQhJokeAnQstr6u/8O",
	"FpIgCVKUYifpvf2njUUsg8HMYDYM/rAc4ockQAGj1uEfVggj6COGIvHXa0gX/P8uok6EQ4ZJYB1aYxJF",
	"KGAABzMCFpAuOlbLwvxLCNnCalkB9JF1aPFPVsuK0L9jHCHXOmRRjFoWdRbIh3xYdA/90ONN7X3owiHc",
	"g6Pe/i6EqIfsA3d/t+fORnuDfXc4GtkHQ9izrRafg6GIz/bPD3b7ALZnR+1XN38M7If/tVoWW4V8PMoi",
	"HMytlnXfnpO2+tFHDHKYO68lYOm3NvZDEjG5frawDq05Zot42nGI34UBdCLi4fsuk+vuJuNYDw8PLesk",
	"cNF9GUniZ0BmgC0QmGEPgSVmCxyIv9VIHXARIN7mX3zafwESgX9h3u9fwI8pA1MEwojcYRe5KYr/HaNo",
	"leFYNLeMSLVblo8D7Me++LdCAg4YmqPI4qCfYh+zMuhn8J73AkHsT1Ek1iDhpYARECEWR0EVPJ4Y0gjP",
	"cD1AZ8jF8FyMVAKKfwKhB1ce5qhZJUABPnMVOOJ/ZpK75hN7JZLhYFzMZhQZEHNuRAi9xSGYkQiEcI4D",
	"yNtWgUPkwDpALprB2GNNtutS0GYRKP4rBwOmCOHU9gikpZi5Gndd+b+OHw6MaLyCwdywk89XDFEQ8Y8K",
	"bRHD0AMOCRgHn8sLRBlN4Vog6KIoA0yOa4Zsygf/zm737P6uEajx9SvsITONjRdIUFOObacIB3NAWYSg",
	"ryErL+p4S0Vr1eLOBEyF9OAwArFfJrFhhiERBdUApLTWM9KXguYnQQZbgrRWPK2F4RQHtyaZNA8QAx4O",
	"bjktp0dPslVr4OD9Gh5Fvpjp8Pt79l0cBYdThheHTY+nj7Ft90du8F2NcBlfX3rQgN9rBiMmBNwUOrcA",
	"+z6XeAx5q0oG5eMYCGxKiIdgkMwWIY9A1yA45IeU7/iukliCgIN55axqvLUTXzNokKFX4vgAlEGGKcMO",
	"BTigDEGX76TksprJebe1M0tSOIYMzUmEES0DcUx8H7Yp4toOQy4QR0om1oGT9uWSdYY9hiIQIRp7Uiyh",
	"+9AjLrIOZ9CjyAxqNoZZVH2wzsgd/3rTsjBDPjWIiJR+YBTBFf+bspWg0hmJfCtbLNdotlloykefslLZ",
	"v2qVjVU7HQ9flZLXeBf4qbLFJnA0mtAPxvIM4r+FKOKTUeBAito4oCigmOE7BHzInAU/ouAcclbKD9t0",
	"D0Xjqi1U0uwTCPWBy14akoBKBD2H7pU85vlfSgLxf8Iw9LAjlKjub5SjT4OEt+TrGNh2y3L5BnlUqNrJ",
	"YZCoNgMbLNA9cBYwgg43ZgQaoohEovkd9LCrnSEcRsg6Aux0/f8boZl1aP1PNzOQuvIr7b4UQwn1v6xB",
	"KP0FLCGXbXIuEgEHBgER0FEU3XFN4qFlHZNg5mFnSywc6Fg4SjeeC3LAFphqS8QUQC9C0F2BMEJUHZUJ",
	"ShKLLmmC7rFQwB4LIZTEkYNMw/8AGVrC1Rj7iMRboWFoD3Q0qJHAEmLGuYJrmAliOE+7kEF96QoAwGS/",
	"x1qz2OMIuNgFfNcj5CDOrFDM461Awg1gFhEfwADEoTz8VE8Bx0nAhSD0rsVPcr6tMJRjl1cQe8gVJoPn",
	"EX5MAR/5JFpJbRwjBwHKSATnKM82EphkaeL3x0DXUQCwaWxAHCeOIsUp54S9InHgbscpORI5J5mpxIeU",
	"DMPZ5BC4cPcA7iI0RKPpYGq7u/3hcDpDs4PhyO7tH9hw5u7be/aBiXv4RosBH1mSIDdjIS5U8vNcC7Kp",
	"QQtxGGJtmjbLAJNyj6tPOIDiNCiqqyWwLgvGWmIXARo7DqJ0FntSYZVGmxD2R46DQtYWZhvNQ1Aw3IwK",
	"87Gcqn2Kgrk0gA39e3Z/YDQokt6pMVo5OZBWY7dnD/aHe6NaWMbii3kwblSTrtko5mO8DWDMFiTCv6Mt",
	"qbmXk/sxW6CAqW6AkVsUcHHvY0q5ABTWkjiFdJrVgXgUJs5DMZMyhs+dQtIRGFQjCbqITf6MwkgUMS7H",
	"xQkeRiREEVMqPQrg1EMGw+al+MAndzEV/4S5MaVOpLCqdKKiHdGyQkjpkkQmw0l9EfKyZuhsiJblS5+a",
	"ddjr72uOnkGrSpNagxbeSEwW8GE+WFNIsWO1rCmCEYq4qqZRt/pWmimmXOqaPCFv1Ze1S4SujwN9faNB",
	"7fIyTZFMf0MO42A8h85tHArFPLfBIaGJIxq6LuaTQ+8y12StBDNMl/jueP9Un60jeiXfy1rug+5R+JAN",
	"3EpBvzHMn57j+dVK5i5uxOvx+FIYyzEFvEUO++JcSzE/PDjQUW8bnIgty0eUQpNX7nXsw6DN9TPBMfIE",
	"Vq3zW1467oySUkdMMmlLLtKElFNM2VjbmDxwp3mLiYIIsQijO8O5k0eqZ/ZwGxy50q2NuFkgdedEQ8st",
	"fmhEKqnwF1+mDmEgm4CYShei7qQvj/d4FMrHYtAzxXAY9EwefngHscdJIAdmb2h2SVeQfxIFSP3dEgrj",
	"xpP5y4BJh2N+77imXs370oFXkJFpS66XxA6LI+QCPg6AlBIHC/NbmUcIeGQOEJ+7YxkA89Ad8sw+Yt5R",
	"fAY7qDPvtMDJ+auLFnh/dHXeAi+vri6unnVMoqiS+ZJBNX4ryzFc5bLmXyiDfpg4Q3MLS0WkCxlqi1HW",
	"8atqJDGQgW3avjNhOVwzaGLbHzwyhV5iXcR8EM3xV+ZW6DB8hyasUg5kfCubZmQbC11HzpTnWA0DOOC0",
	"WBdlEeJ0IoepDoypBXHzaSklhlAg8xxj7+3uDXr7XC3VARgN1oIgmGUiDDG6nnNlOw6EYfV9zrcbrZ9L",
	"qEoEHMeJIa12tGr1w93R/p590OtvuPgCIRYJIrc9BUTlQTfR6iVveBLMiClaK8HkohpOScy0cJq0iNkC",
	"MrBEAEZIEZ+3Aj4MuIifl0mZC2kPMQPHvl8gtkCRYFQ5NFeRYXSLXAD5IS875tAphV1ZR8VB5VaVpxFy",
	"EFPgyE30VsAj0JU7aCCd6jmNEatfUUTaU8gpQq2qJlSkH38bUSfFvxtQeil9Fvh3VMWLwqL7NFpMd1RH",
	"eyuLcHHITFR3JQxhM9kdSSkWiSbCW6eI0GTtGC2dHLbzrG+vQ6ac1hSiEeBUDcyZes0uMRixyghX1bD2",
	"RtsRJUFhOVlLIMiE/2tlQBqwn1nbwCHBDM/jaJ3RCZXNWqeNCbv2oaUM1InrBbDSSH1xen4ERKQv8X3N",
	"4sCRSgxmq2amajIRWQaCpaPK6abQuZ1HwumVtC44SanUj0ToW/cCrgWC95ioHpOwNlUhja2bJrBECEbF",
	"Nkta0CzCKHC91cRstwp0Jm1kLN/FlA8mPZ6Oh/kaywbNpZzPh/eJm6k3FPSY/LlrAGbBWDiR2zZJYkuF",
	"w/r4EvAvAsPSllPuXQ2AffvA1i3o4XB3qPFCz8RiHplPEmlWspbIPA1pZB4C4U9qWQzds7x7QPxiWB2f",
	"okIJPk0U4DwiuRq8JjxHPTLvnCrFsiY255F5l7cVfM8h4aSCJmb5n6mFiearIreiU8X51rN1pPds235k",
	"1TBxhRWd6uYzarTXs/f3R0ZtMQGy3xvsDfZ3RwPdhbS7OxwOBrv9KgkPFwi6kxBFDgqY0fq4SlqBrBW4",
	"g16MwM7Qbvds+1kO1IMC4jRghnX27ERyX0Nj9lg21rqzCDq3yiFkzkhMWkjNdLrS9Q7F+x3wEjoLIOxj",
	"wI1rgOnHgAQo6QwYRtH/cerBgePFLgJ+7DEceigbXmk0lMsX3rz1MUjCu/yDL2WoQ3wf0kQFgoCbKB4S",
	"k3Y+BjpGP1ixGx52uzJSi1GHRPPD0cHogGu14ouauuMh5CxQRNt8NhfTrGkr35CEnA+gcxuJFr3d3b2q",
	"CPvOTuyGfy4p/f5PLtHo988Ou92djx8/ZKH3w5tvP368+fPDP1uH3Y8f6c23z3YO+debb599v9P98M+W",
	"/PH7Zzv8X/94zBGf/cMc8k9OibbwbQtea9+iFRdoRXoxOe7KesKKMuQneprmdYeuGyEqAtcfhMg/7HZ7",
	"/b2O3bE7PSG8rVb6+0G/0xvtd3qdnm3Lbzctaxpjz51w+9s6tPq2PWrbvbbdF/4wXzioLNib9p1dl+93",
	"KC39/ZFw4d2hiEoi7/EZhWc6r5Fk4FW5zTxMGQpEjkDSuJMnv62W1TwZQEdA6cjmTLNcIMlSoqWIcjkR",
	"gqzgLcsjrzRtgs2SHwIzIL+l6cqaBzvFfNk/HpqdLrriKNtwiUCRQwI3j1m1iSWRXpaR6T7XTRYhD0GK",
	"gGoMdijyYcCwk/yCg3leViuqWefxyYgot1kpSlNcZIDeVPLQGWIRdmjZo7fWv1PplcwsVYNEL1oRZeQm",
	"uu6EhsgUMVKOqqQZEM3Sc5ofi2p3C4bQ7mA42mu0vXHYYH7ZaKPZG0y+1qdSwE4BWNM+j6+PobNAWgpP",
	"+TyWSQvA4Q31dD8V1C6bVovmlw2e/OJAEWkCtlpMyGDBpqjIQgx5XBzDEDqYrapYRA7lqFZbeCDLFHqZ",
	"+hurgm21Stt15l0rBYfPYJh6Krnljx2pnic/5NweZrcdPSZxwJp6Q8uKftV6s6SCkq8icGGUuFc80WxT",
	"71J50qssK6LSEwQ4zgU6KCBS4IntFjmxTaJBmsdpXcgypbN0//P4LqApW4CZF2o8rBofGLe9QP/K2eY2",
	"9J9u5DU9catciGWv1FqjsIqAnsYn2bIuI0yiVDJkd0dMs4eqLdhZ4DnHGabAFxaxMLdhwPLKQm8jD9wJ",
	"PypSwsh2zEwa1W44jTKq/W5Cyl4brf+C6T0jiaT9hLhMujsGHBgWpw6pI9d9haXRUIgGyFxwU0RFfRFg",
	"k2gOA/w7V9ST4zl/2qmMcZNfTM1rPjzFjaDcSDsyYSJ3Z+iZHi2sTqiQuQ2GnJGrU5FzAxkEb69OhIAX",
	"TQH2S04+YRYKi1f8IpKwZevOb+HcHP9kpiW+kO49ID5LR2ZFrCG78aV7+UTemObn661TBQSmb+rIgNNA",
	"cvkBet7FzDr80MjlIYjnoVWkHuzW3cbZRFwVloJNzHqjL6WJhpdm18IAzpGvXeEyR3iNRo6jkteSRHfd",
	"cwldLmnciIRWy5qLfAJu0Yr7PH7elymblg3DZvxXSTnVfJckKRSuuEGKRoM2ChziCsdzxmQgTUBOR//1",
	"xXz0y/thPN19F//Sf/v7+Tjs/fr6aHS6OrAd/9VvsP9udeofLH99P8Tw5yt7uvtm9ev7oX3qn99Nx2Rw",
	"drz/nQm2RKEmAVI0WIgJ+CFbKUefyA8X4exOnkHs8sBfiYrOCdVrclns7dVpHqInveJVLSAvNWkICtLy",
	"U6UjhcKmm7jTnGJgypK5hlniBOc4DsIUUj3rRFOWmojdPPAv5b+AYJr1ngcpEWoFqm5dbSRQZV6KmWLr",
	"pFeVWTbFbBIpL1atkKmUE+UPa1wTLzb0Sdj9gW3bHT3txSXx1ENmzVJaTgIQFfycKD+WBm3WSAX5jNk+",
	"15lhy4Upgo4KIxquijZKaiudpwbP4lM7DQxRMegiNw1ENbD5zJHKceH2+vqL6V9GsKjrnpssWHVB7kQm",
	"9TfrRZXGZP4yURAZvc1J/lvDmTYXadVbksQaNkBP0RVYYLKCfCw551RVDZ0OW0mdg9xmlTeild6f1TCq",
	"4y/BTWFdaz2CUmd8h9ESuU1UxjuMloDB+SMrijLXlCuFSkO8qbCUJmkSU3l7EonS6NhKt0Mb1XyUJchp",
	"4CfUsFN1ED3OIhrCTm5RoO1qHpJ5BAM2Md9ZGC8QEN/ldQVwpq5nfpNcjPhG3730toRp16pvY/BJYoqi",
	"byhIGlXewki5U/ttg1sR2lRJI/NtiHq0ayjTZmuZEFDahYx8ivziIEon4vaPGfA378dAtpJ3hPKQo9Wb",
	"xfQHB1/gNydvfz/pneMTehJcDZ3jk9HJbfjzu+M3Bx20etNz+u9WU/8V+/X6ZHTiv7qdvvfiE7zE8P0r",
	"++Q3cn8+ftk/++1sePbiZDX7qXM98368X169uT5DP/74qv/TeDBbhmfozWx3dHlxO1q9eTeB7k+ULofG",
	"GyroPsQRohNcsSgPz1Ah/pYkQVeudXdkV2Qp3KKghpL5FxmU4iOCI28JVxR881zcuPkmj075YwPlV9u1",
	"HARmEpBZ/ptqwUeuK3TgBk3fhiLuV/ZBqGjsxJRv9D4J3qYXkCEF0JWWr0yUEHHBYii3P2jbvXZvOO7Z",
	"h7v2oW3/2jBdXYqsmoC3+CzuKEIclOKGzTXQnFumoe55/fqo3assUAJ2SnfTn30Wc/kzVEkwC82LCM9x",
	"AL1cZZ3UIxIRP38tu4kajJGDJs4mASFQk4PcG/T2jWqsmMaccVYID1W7+fujfm/QLAAns9nN88lViWnI",
	"DEDPUyRunHN3r9c7GNr7g/2GoWm3krVPIWXifkmJv33i4hku52dkTN07HAw3YGqzbiJdNZmGKxk/h6w8",
	"QVQop5kkNOT+h7FM0ISuyIaFIOAKWEYqn9uZ/7dgyQsWRQRVfr6Slfu4/j0NGWrgjx9zQ+98kAiy2wcC",
	"R39+gO3fj9q/9tt7N3/s9h+efUVRFJWDuoUnTfZ7uGll3kUrvQVRuj2cRONIVMj0/sKRnCql6u/Q3ech",
	"uk1I7a8Q88vlKlduokxUy18yKR8sqlrBxF0w45rlhZHXY7DzAnNApzFDLuCCFoz5t2cNLmooiayqPqkZ",
	"X7weCw+wmh+Hd6NqAE4u70br0yyM8/Cu+kSh6SJZMs/ly5/BziVCEXh57yxgMN9+fZcvf9anZU5YPe34",
	"+JLvU4CEg4duO+X4+FKfMmY1U8bjS7Bzhp2IgHEEAyoujFxGhBGHeFsv+u34MhdfiCBDk4r78GmQQWSw",
	"i0bGSAOwgY9gQEEciEbly+z1ySuIMjj1MF0gd8KRTCchipJURLPV7ZeK0WqD6Dsl4DTJgFzdWXN+aBih",
	"GYomsmbNhExnMZUZt6bLErK6l7gPSmI2J1zma3B8A1TpGzBFIBmqgKjKS1QU1aY8EcAbADjjolm7wNVs",
	"8MSnGyIU0ckCzxeTJTSeBxzx/DsQ38Xt1FTMaqYVH6cG7TreR3aNK7yONN+Gj0CYu73BcC9XeMVumNqj",
	"eQDMORjp7Y5Ke8GryBAT3WsSxPoH/UFvb9jfOEXMbIc/h7Rc3dZ0WJrr+bYs852+V7HnAf5pXa1rw0zd",
	"+gnvhMu83uUkZ4MUeNxSlT22N0mD2BO1LwqHWoVW4CW5b6n/li3qtAS+4crBZihvLX0ggs2ERS4t0Vkz",
	"GjPvjagfucH+VOyAwRRFInOAI4n/X8gHSBX6W0BIIP1DHGQ7Y6jYqiNV1TRWM9dg83ptFFpe5E/UZJH3",
	"jtkKwMBNgkcwcFBlGQoh3uouG2YX6VU1CtGjY3SyCP6eiEqpbpV7R0o12Qa4Md8EcIciPNMqLzXw58ip",
	"IgTXTCRyjYUDzsX0duPBJxWpT9nY4ohUTliOohh66W4k/r7NpowpmsVexcxvxUdpxBRXmO7MVvPxj4GL",
	"3PqJk1aPBcEywowZoznaJqpGIo9n011UfStWNdZ26pMmcxZxcFtPkLLJdhSpDa/2q3KHStNssin6PEtI",
	"zbnp4vfcPDtuLO9viYJ0cRAglNDIs81mXkMPatIt9yjJ3m7kf05ba951Qw2Y/qC/v2+8/lavvyhlmgPD",
	"kbVGCCeNgWpslr8L6M0mJETBerEu1VocAN6nzfuIOzsI7CRavrpkV56lph7LeTEi0bAMS3/TAkYpDI22",
	"sgRMCkVdPGOLTU1gSk7tOkeQXlQq6yrqR9VeZL/Mrq+TWWo56sWKxJVwTDOnueF6e7+TC9hk2XPmK++m",
	"XLokojWplX2pzqfJi4b8GqKA231NiFk0FERd9GtUhLxMt5PEbXkVeZKZkinvJ+XUcJRQkapX2DjMmrs5",
	"Vgyyylkm1fWUdFGQF0t1a5y4mOt77mQKq24D6VWZpjCxurdQyAozzglpMiVvtv2cUZOLZqridEgoli4U",
	"aeNn/PEoV87SOl2oonZDPmB7G5BlUKdKb1seTTN2WjWB5569aVGqzQK3Bfapuxy2sZg1X/WViC/YIDk7",
	"oazXV6rd6/Xjov5qVDfzaqFRizOqXCVtyKQulI/7CpFcFKRlcWOUF2aWztN5Sacqlg3LndKF87H6zEtl",
	"dKn6nUaFtVZzGoppHrPLcvRS+JOIiBZ0TavyFb0I+dwig4eP/y484aZC/V8iHLc2tYgR6aSp8qRsml6U",
	"5l0JwX0ReKuCCyo7D58qhBegZfs/MIxXYAThY3fiCLPVNYdX3euAFDtJOXKxDkPdbI40YTyL3L6ktfzr",
	"VSKl37wfJ6+oiCEKeYDJGA4htxglY4gHWeRP2lNHiFKZYpyQQIh/RCtZfB2rO9bCuyKfD0E+xB7vF4ch",
	"idj/0/Y2GzQpdQbGCPKf48jTyEHLyEhrsJUrvadcmr7WBLS69VIflMKgnTvrdHniYQepPFYF2dnJuAQP",
	"F+Dy3YMOieZd1Yl2eVu+tSjy6cXsGkV32Kkia9Gom2a2ayg4ujyxjPV1+LQwxNahtauKp4SQLQShdGGI",
	"u0JGdzNDb44q37lKLat8EVwYuDKYQQF0IkLF5bus2klSXkrVC8uyJ9PKACeudWj9gJhuKRWe2OnbdoPX",
	"BZqV/c8ZZOXi//JzvrKFuT73Q8sa2L2q6VL4u7k3Eh5a1lAupr6T6bkUwfCx70O+VRxjYJ4rSpwvR8zg",
	"XFR5yn61bvgI2rYnm9T9gytSD3X7LzBAgXyqgaOi6JqGgIbI4ap9ppjKomNZMWNJMS2lLrYE6QSILUl0",
	"m7q0jaSRc5O3cg+7VqT8ZE26Invr4eYJSSp/Q8/w/gnJbMkmRNWAPrRHpz4/HfK+g/V9C+8hlcmXlfCy",
	"nnCF/OguEPTkeWMk2OMFcm4BVsnzmkDHFERxIMuHBW6+QHye6l6LGcRAFdKourQVpkACuOrkTmnr8MON",
	"jgM5B3D4JPrKZemp8qqTk7JWSKcsikt1oAvYMLKaVjruCTlGm8XAL9cpS2RvS4mjWOIhX25lW/If9A8e",
	"bTnVLx8RAs5gsAKKWSlog6ss/I/uHeFC7zzyuZAj+UJJojU05hFZ16SWxmD27t8CAZ9Q+SpYwPSipUby",
	"OuXDfyJhNTJI0rcYymWDDGpgspwc+F/BAa+wqu8n36AmG+lnletq9zJC0BM5Awl3qY7Aw7fIHHFOzmxx",
	"hZLWiJGket6TS5JkIpMwya/qK9bm8viv3eO7Xjd5Pnw9swbA342z58a5cZqZO2n9QbkZxs28TKbaVPXK",
	"3kDfUP+6b/shmr+9Oq16mOx/Xv48Ptt9+zHg/zg5f3XY7rWkYf0xaPL2Ww4jcxQg+ZzpF1PGBk0UqvTd",
	"wMekO7l0ACsIRCfDu16eBKlWB6vWcEgtR1hZpp7LFb1kVlmiJJM9pTBJ5jDJEfXta5YgOnp1ZOY2ULgA",
	"nEWV87J6jzrgmvBjIkGED1dAuegB5JqaeBOBEcDgLQJoNkOOQZ7IWXK7KVjnOXFXn2Ujz9EyW4OoGCRw",
	"lH9P/aFEZQNj6pgcRV07+yvacjkaMlBAJRnpckAIi3VeBPm4p/YYjXDMT1cAM/11Xy4IxBeZ6BepymBC",
	"g8YRovLpAfEEZlJyQQb7wvxznmYhIl8O3c6F0Frb7hKyRu1ORIGCBg3lS5+Gw3O0frvVWr/mQ2zQGz29",
	"DSZJ5ZwwcA0ZpjMsDf4v5QHJfAF/5FznH24ecs4BI7sYhPnCmI8hoAUQvH559CJ9xVvcC1VHey5GtREn",
	"mlwl7tfFWDdNPDbvsItI9hqxfMi7lcbrAJVVl5IrEM0fAt7s2d+ad37LL/Oa3uD9D1RRPwd7bcwgdSeg",
	"XgZ+jecklA9pIjd1OuTiJVn2WhJwUk9/qMgJuJYxMcphYkgkVk+zC5QnLwzac+5B0k1ZNLkWKEPSGNEm",
	"fKg6cfbeqAO3FRu1PxU3bBo0vJDPdj6p/z+HX6N/qbzpWSj/r6cmivwBnWpNNgYx1c06cl3tRFMVVdKi",
	"jRlt+1nVS9rKjiRExaGkc6WB3I9cNykvs6l1oRwMuRr+2bo59HcY6nULAm9ltSxhRWR9NilPkCYiaEkn",
	"KrqrEgXyVQPK0Gi40kFJujx2BQGVs7H+6vQmK5ssMVuIbKpJHOHadYpAQJoaosBpum7X3e8Ph8hxnT0H",
	"DoezqT2dzvZ7u/1dd3/PHvXdaW82cntOuu7neP7t89i5/fZ5HAQrff0chEORj9INg/n/TUWZ3BZ+9/zi",
	"amn/+MOcHB0dHZ1fv128fDvn/3zJ//P8+Oino6Oj497ro+Ux/+HY9l7+9O5q0PfPb3/hPxz9cnT02/Fz",
	"+3hf/HX99t3F1Y/D419OTr7TEPgczwEHC0iwHh4av3qv11F6aOWYgDgMsbY8/QwnGFzm9UXFSmCH/yUu",
	"49EFiT0XTMUtwESJeYFpkpSpVCmRopxBu/auP6cS8WwVjFiXt24ntzw2XbKsflQdoBVkxQiArtsBxwtC",
	"KAIkQIDMDj8GbfDm+uJc5YTkq/KmAoG3OktgFQ/XqZxiHXFchJFQPe6cqJvCbbnOB9F77JB1HTJk1avi",
	"m+SaCnxKqi4WiwQuGRwK0NJbJQ8g6QlRBgLgrN/6wjruwfpOxySYeVimIn7ZILo8TgsVftbpqN0pdG7j",
	"sFJVfS4+57VScc9QSD6RL5i+/5boxfkDWI6gaZwbaF5FIdSMnOWMJmpWq5GAfmG9ScFiwmqjjYuQeARS",
	"XJI1qldXsoF530SaOARTHSHFnVMD5LauSn9aK5PLZT6bivtiouNDI3esAv6v74at28ZGhJJ5Yl1kvmly",
	"hXwi7N9c9TrdzhwvMAVL7HkAepSAWYT4ybUqX0FK4fyGapdV8nT1QoCRaeWPk8E1qLnpieTtmccJ0Xyp",
	"6JxEW/6yfMHOqo+71SQDlRP2Sh7Auly8rzcNr06n+QrS7v4abjRjnp5+lWGjkKKvV4SAgfS1atkHHXAR",
	"eCtVh1E43mYYeS4FDgy4OaHia1XBxEcgyccPQRaq0FbTZIqc9CJGk3DkZ2WbLx7f/FICWNHvWgZID+F+",
	"dghDWaDTrKkdEz+EDE+xh9kKoMANCQ7qK3fmKf+n55ix1LBt4u/aUF/b7p2hqkcFaC5xr0F5v+JdoTjy",
	"TDdAU3+q7jFMTPhtdcsibzF0z7qhB3FQlY50cdtpknVUZ1r/12R+l4xWsPPvjJjFzWfOGaoGYMJmWhPF",
	"b+JhvK04rOYd0w5IL7ukX2KaBIYKClOZK9UTqk+U1VJ4qtZAYMc1L9R+xhOl8JBsM0D/mzSzkopVek93",
	"RydSM0tkLRRHIGdRfT+gGT8oehdXEnAwz9jho3Xx40cL4BmgsmV2lcLEBi85KI8hWH9sIlevyyB9YRPe",
	"gM6ttpRw6LrpUxhmUXcxlWWpxLsYoi2IqVCvFwhcJQkOF8sAReBSPcwBjiPkooBh6FHwQwQrEqbG6jmH",
	"ZuLsvr1cLttCvYgjTz0ZuIkmqr3OYtjmt5RjToNbXI8Wi5caU/pAxufUnvW3TIxnPt8PCeVf1zdVcYOp",
	"THk6NXMAFB2HHlwpt1T3D5FH9LCNpKrMWwcujpDDvJVJGF16cPVkqUnj68qko7+T9DZM0gsIA/QvmKRX",
	"JMZtJL2eTP8pGi3NJyVTE0M8cfa1NkGFEWR4I/vziexGWf7/YSndKVVsRZoqvzsJ9H+i6CYRUK/5mQS5",
	"iJffwQiTmKowuZmGt8s4HV+f4uB2A8H+U4zELcIG7S9lkYkmLeX6mzVW74U2aPkKe2ib61absnfxLVuR",
	"SRK7mHT/kR+mSbDvDrtoi45l1pWymEQFszKOgr/9/Y984GUsnDlxthAsyQs5snb6p3lLi6m6RXmR+uPF",
	"VJ/kKG3EHDXpRutzhD53NpCBo//OC/qaPabbM9snK5iGV8Z3oOu2QCRyClrCJf+shgWfTu1MqbjShTA2",
	"PZH+RC5SEqAmj1KVea/1x4avimtdC4GTGwMOLpJt0aqM/n08NmPFM0E3WWbONoyYvUTwKWyYvKxsVI7l",
	"C81Pxmf517FN5nzysgzhlocUCS2uNURJ3lEC/uOzXUPWKTxi3aBMSEO++XK2Xp44MwrZnEqLKqFWVPDD",
	"DZdPeuFAqSOqgUoR2ssTwBeLApZcKU4oWlCuKpknXIV84CasIB2/etDw6PJEG0yPFZbHVBXe9IskmsFg",
	"Ak6rRGUCMUJ8/gJ05VNSG/Cut+Fatf3LL1XbtvKI14ZySWlPVVPk4ebh/wcAAP//T18SrzjDAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
