// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"log/slog"

	"github.com/anacrolix/torrent/metainfo"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for AuthType.
const (
	Basic  AuthType = "basic"
	Bearer AuthType = "bearer"
)

// Defines values for SettingsLogFormat.
const (
	JSON SettingsLogFormat = "json"
	Text SettingsLogFormat = "text"
)

// Defines values for TSTorrentRequestAction.
const (
	TSTorrentRequestActionAdd  TSTorrentRequestAction = "add"
	TSTorrentRequestActionDrop TSTorrentRequestAction = "drop"
	TSTorrentRequestActionGet  TSTorrentRequestAction = "get"
	TSTorrentRequestActionList TSTorrentRequestAction = "list"
	TSTorrentRequestActionRem  TSTorrentRequestAction = "rem"
)

// Defines values for TSViewedRequestAction.
const (
	TSViewedRequestActionList TSViewedRequestAction = "list"
	TSViewedRequestActionRem  TSViewedRequestAction = "rem"
	TSViewedRequestActionSet  TSViewedRequestAction = "set"
)

// Defines values for TokenRequestGrantType.
const (
	Password TokenRequestGrantType = "password"
)

// Defines values for TorrentStorage.
const (
	File   TorrentStorage = "file"
	Memory TorrentStorage = "memory"
)

// Auth Authentication settings.
type Auth struct {
	// Enabled Enable or disable authentication.
	Enabled *bool `json:"enabled,omitempty"`

	// Password Password for authentication.
	Password *string `json:"password,omitempty"`

	// Type Authentication type.
	Type *AuthType `json:"type,omitempty"`

	// Username Username for authentication.
	Username *string `json:"username,omitempty"`
}

// AuthType Authentication type.
type AuthType string

// Backup defines model for Backup.
type Backup struct {
	Posters  map[string]openapi_types.File `json:"posters"`
	Torrents []Torrent                     `json:"torrents"`
}

// Error defines model for Error.
type Error struct {
	// Code HTTP status code.
	Code int `json:"code"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// ListTorrents List of torrents retrieved successfully.
type ListTorrents struct {
	// Limit Number of torrents returned in this response.
	Limit int `json:"limit"`

	// Offset Pagination offset used.
	Offset   int       `json:"offset"`
	Torrents []Torrent `json:"torrents"`

	// Total Total number of torrents available.
	Total int `json:"total"`
}

// LogEntry defines model for LogEntry.
type LogEntry struct {
	// Data Additional structured data associated with the log entry.
	Data *map[string]interface{} `json:"data,omitempty"`

	// Level The log level (e.g., INFO, WARN, ERROR).
	Level string `json:"level"`

	// Message The log message.
	Message string `json:"message"`

	// Time The timestamp of the log entry.
	Time time.Time `json:"time"`
}

// MemoryStats Global memory usage statistics.
type MemoryStats struct {
	// ActiveTorrents Number of active torrents using memory.
	ActiveTorrents int `json:"active_torrents"`

	// MaxMemory Maximum memory allowed in bytes.
	MaxMemory int64 `json:"max_memory"`

	// TotalPieces Total number of pieces in memory.
	TotalPieces int `json:"total_pieces"`

	// UsedMemory Current memory used in bytes.
	UsedMemory int64 `json:"used_memory"`
}

// PieceInfo Information about a torrent piece that we are actively managing.
type PieceInfo struct {
	// Complete Whether the piece is marked as complete.
	Complete bool `json:"complete"`

	// InMemory Whether the piece data is currently loaded in memory.
	InMemory bool `json:"in_memory"`

	// Index Zero-based piece index within the torrent.
	Index int `json:"index"`

	// Size Piece size in bytes.
	Size int64 `json:"size"`
}

// ReaderInfo Active reader information.
type ReaderInfo struct {
	// End End piece index of the read window.
	End int `json:"end"`

	// Position Current reader piece index position.
	Position int `json:"position"`

	// Start Start piece index of the read window.
	Start int `json:"start"`
}

// Settings Application configuration settings.
type Settings struct {
	// Auth Authentication settings.
	Auth *Auth `json:"auth,omitempty"`

	// EnableDlna Enable DLNA media server functionality.
	EnableDlna *bool `json:"enable_dlna,omitempty"`

	// EnableDownloader Enable background downloading for torrents with file storage.
	EnableDownloader *bool `json:"enable_downloader,omitempty"`

	// EnableStremio Enable Stremio addon protocol support.
	EnableStremio *bool `json:"enable_stremio,omitempty"`

	// FileStoragePath Path to the file storage.
	FileStoragePath *string `json:"file_storage_path,omitempty"`

	// FriendlyName DLNA friendly name displayed to clients.
	FriendlyName *string `json:"friendly_name,omitempty"`

	// HTTPServerPort TCP port for HTTP server.
	HTTPServerPort *int `json:"http_server_port,omitempty"`

	// LogFormat Log format.
	LogFormat *SettingsLogFormat `json:"log_format,omitempty"`

	// LogLevel Log level.
	LogLevel *slog.Level `json:"log_level,omitempty"`

	// LogStoreSize Number of log entries to store in memory.
	LogStoreSize *int `json:"log_store_size,omitempty"`

	// MaxMemory Maximum memory allocation for piece storage in bytes.
	MaxMemory *int64 `json:"max_memory,omitempty"`

	// StremioToken Stable scoped token used in Stremio addon URLs when authentication is enabled.
	StremioToken *string `json:"stremio_token,omitempty"`

	// TorrentClient Torrent client configuration.
	TorrentClient *TorrentClient `json:"torrent_client,omitempty"`

	// TorrentTrackers Torrent trackers used by the torrent client. Each array item is
	// one tracker tier; to include multiple trackers in the same tier,
	// separate them with commas within a single item.
	TorrentTrackers *[]string `json:"torrent_trackers,omitempty"`
}

// SettingsLogFormat Log format.
type SettingsLogFormat string

// SystemInfo defines model for SystemInfo.
type SystemInfo struct {
	// Addresses List of listening addresses.
	Addresses []string `json:"addresses"`

	// BuildDate Date when the build was created.
	BuildDate string `json:"build_date"`

	// Commit Git commit hash.
	Commit string `json:"commit"`

	// Uptime Application uptime in seconds.
	Uptime int64 `json:"uptime"`

	// Version Application release version (semantic versioning).
	Version string `json:"version"`
}

// SystemMetrics defines model for SystemMetrics.
type SystemMetrics struct {
	// ActiveTorrents Total number of torrents loaded in the torrent client.
	ActiveTorrents int `json:"active_torrents"`

	// DownloadSpeed Global download speed in bytes per second.
	DownloadSpeed int64 `json:"download_speed"`

	// UploadSpeed Global upload speed in bytes per second.
	UploadSpeed int64 `json:"upload_speed"`
}

// TSCacheRequest TorrServer cache statistics request.
type TSCacheRequest struct {
	// Hash Torrent info hash.
	Hash string `json:"hash"`
}

// TSCacheResponse TorrServer cache statistics response.
type TSCacheResponse struct {
	// Capacity Total cache capacity in bytes.
	Capacity int64 `json:"Capacity"`

	// Pieces Map of piece indices to piece information.
	Pieces map[string]TSPieceInfo `json:"Pieces"`

	// PiecesCount Total number of pieces.
	PiecesCount int `json:"PiecesCount"`

	// PiecesLength Standard piece length in bytes.
	PiecesLength int64 `json:"PiecesLength"`

	// Readers Active read operations on the cache.
	Readers []TSReaderInfo `json:"Readers"`
}

// TSPieceInfo TorrServer piece information.
type TSPieceInfo struct {
	// Completed Whether the piece is complete.
	Completed bool `json:"Completed"`

	// ID Piece index.
	ID int `json:"Id"`

	// Length Piece size in bytes.
	Length int64 `json:"Length"`

	// Priority Piece priority (higher is more important).
	Priority *int `json:"Priority,omitempty"`
}

// TSReaderInfo TorrServer reader information.
type TSReaderInfo struct {
	// End End piece index of the read window.
	End int `json:"end"`

	// Reader Current reader piece index position.
	Reader int `json:"reader"`

	// Start Start piece index of the read window.
	Start int `json:"start"`
}

// TSSettings TorrServer settings.
type TSSettings struct {
	// CacheSize Maximum memory for cache in bytes.
	CacheSize *int64 `json:"CacheSize,omitempty"`
}

// TSTorrentAddFile defines model for TSTorrentAddFile.
type TSTorrentAddFile struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// File Torrent file.
	File openapi_types.File `json:"file"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// TSTorrentFileStat defines model for TSTorrentFileStat.
type TSTorrentFileStat struct {
	// ID File index.
	ID int `json:"id"`

	// Length File size in bytes.
	Length int64 `json:"length"`

	// Name Base name of the file.
	Name string `json:"name"`

	// Path Full path of the file within the torrent.
	Path string `json:"path"`

	// ViewedAt When the file was last viewed.
	ViewedAt *time.Time `json:"viewed_at"`
}

// TSTorrentRequest TorrServer torrent management request.
type TSTorrentRequest struct {
	// Action Action to perform.
	Action TSTorrentRequestAction `json:"action"`

	// Category Category for the torrent.
	Category *string `json:"category,omitempty"`

	// Data Base64-encoded torrent file data.
	Data *string                `json:"data,omitempty"`
	Hash *TSTorrentRequest_Hash `json:"hash,omitempty"`

	// Link Magnet link or URL.
	Link *string `json:"link,omitempty"`

	// Poster Poster image URL or data URI.
	Poster *string `json:"poster,omitempty"`

	// SaveToDB Save torrent to database.
	SaveToDB *bool `json:"save_to_db,omitempty"`

	// Title Display title.
	Title *string `json:"title,omitempty"`
}

// TSTorrentRequestAction Action to perform.
type TSTorrentRequestAction string

// TSTorrentRequestHash0 Empty value is allowed.
type TSTorrentRequestHash0 = string

// TSTorrentRequestHash1 Torrent info hash.
type TSTorrentRequestHash1 = string

// TSTorrentRequest_Hash defines model for TSTorrentRequest.Hash.
type TSTorrentRequest_Hash struct {
	union json.RawMessage
}

// TSTorrentResponse defines model for TSTorrentResponse.
type TSTorrentResponse struct {
	// ActivePeers Number of currently active peers.
	ActivePeers int     `json:"active_peers"`
	BitRate     *string `json:"bit_rate,omitempty"`

	// BytesHashed Total bytes hashed during verification.
	BytesHashed int64 `json:"bytes_hashed"`

	// BytesRead Total bytes read from disk.
	BytesRead int64 `json:"bytes_read"`

	// BytesReadData Bytes read that contain actual torrent data.
	BytesReadData int64 `json:"bytes_read_data"`

	// BytesReadUsefulData Useful data bytes read from peers.
	BytesReadUsefulData int64 `json:"bytes_read_useful_data"`

	// BytesReadUsefulIntendedData Useful intended data bytes read from peers.
	BytesReadUsefulIntendedData int64 `json:"bytes_read_useful_intended_data"`

	// BytesWritten Total bytes written to disk.
	BytesWritten int64 `json:"bytes_written"`

	// BytesWrittenData Torrent data bytes written to disk.
	BytesWrittenData int64   `json:"bytes_written_data"`
	Category         *string `json:"category,omitempty"`

	// ChunksRead Total chunks read from disk.
	ChunksRead int64 `json:"chunks_read"`

	// ChunksReadUseful Useful chunks read from peers.
	ChunksReadUseful int64 `json:"chunks_read_useful"`

	// ChunksReadWasted Wasted chunks read (duplicate or unneeded data).
	ChunksReadWasted int64 `json:"chunks_read_wasted"`

	// ChunksWritten Total chunks written to disk.
	ChunksWritten int64 `json:"chunks_written"`

	// CompletedSize Total size of completed pieces in bytes.
	CompletedSize int64 `json:"completed_size"`

	// ConnectedSeeders Number of connected seeders.
	ConnectedSeeders int     `json:"connected_seeders"`
	Data             *string `json:"data,omitempty"`

	// DownloadSpeed Download speed in bytes per second.
	DownloadSpeed   float64  `json:"download_speed"`
	DurationSeconds *float32 `json:"duration_seconds,omitempty"`

	// FileStats Statistics for each file in the torrent.
	FileStats *[]TSTorrentFileStat `json:"file_stats,omitempty"`

	// HalfOpenPeers Number of peers in half-open state (connecting).
	HalfOpenPeers int `json:"half_open_peers"`

	// Hash Torrent info hash.
	Hash string `json:"hash"`

	// InMemory Number of pieces currently loaded in memory.
	InMemory int `json:"in_memory"`

	// InMemorySize Total size of pieces currently in memory in bytes.
	InMemorySize int64 `json:"in_memory_size"`
	LoadedSize   int64 `json:"loaded_size"`

	// MemoryStats Global memory usage statistics.
	MemoryStats MemoryStats `json:"memory_stats"`

	// MemoryUsagePercentage Percentage of maximum memory used by this torrent (0-100).
	MemoryUsagePercentage float64 `json:"memory_usage_percentage"`

	// MetadataChunksRead Metadata chunks read.
	MetadataChunksRead int64 `json:"metadata_chunks_read"`

	// Name Torrent name.
	Name string `json:"name"`

	// PendingPeers Number of pending peer connections.
	PendingPeers int `json:"pending_peers"`

	// Pieces Array of all managed pieces with their current status.
	Pieces []PieceInfo `json:"pieces"`

	// PiecesComplete Number of completed pieces.
	PiecesComplete int `json:"pieces_complete"`

	// PiecesDirtiedBad Pieces marked as bad after verification.
	PiecesDirtiedBad int64 `json:"pieces_dirtied_bad"`

	// PiecesDirtiedGood Pieces marked as good after verification.
	PiecesDirtiedGood int64 `json:"pieces_dirtied_good"`

	// Poster Poster image URL or data URI.
	Poster         *string `json:"poster,omitempty"`
	PreloadSize    int64   `json:"preload_size"`
	PreloadedBytes int64   `json:"preloaded_bytes"`

	// Readers Active read stream positions for this torrent.
	Readers    *[]ReaderInfo `json:"readers,omitempty"`
	Stat       int           `json:"stat"`
	StatString string        `json:"stat_string"`
	Timestamp  int64         `json:"timestamp"`

	// Title Display title.
	Title       string `json:"title"`
	TorrentSize int64  `json:"torrent_size"`

	// TotalPeers Total number of known peers.
	TotalPeers int `json:"total_peers"`

	// TotalPieces Total number of pieces in the torrent, from metadata.
	TotalPieces int `json:"total_pieces"`

	// TotalSize Total size of all managed pieces in bytes.
	TotalSize   int64   `json:"total_size"`
	UploadSpeed float32 `json:"upload_speed"`
}

// TSViewedRequest TorrServer view tag request.
type TSViewedRequest struct {
	// Action Action to perform.
	Action    TSViewedRequestAction `json:"action"`
	FileIndex int                   `json:"file_index"`
	Hash      string                `json:"hash"`
}

// TSViewedRequestAction Action to perform.
type TSViewedRequestAction string

// TSViewedResponse TorrServer view tag response.
type TSViewedResponse struct {
	FileIndex int    `json:"file_index"`
	Hash      string `json:"hash"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	// GrantType The grant type. Must be 'password'.
	GrantType TokenRequestGrantType `json:"grant_type"`

	// Password The user's password.
	Password string `json:"password"`

	// Username The user's username.
	Username string `json:"username"`
}

// TokenRequestGrantType The grant type. Must be 'password'.
type TokenRequestGrantType string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken The JWT access token.
	AccessToken string `json:"access_token"`

	// ExpiresIn The lifetime in seconds of the access token.
	ExpiresIn *int `json:"expires_in,omitempty"`

	// TokenType The type of token. Always 'Bearer'.
	TokenType string `json:"token_type"`
}

// Torrent defines model for Torrent.
type Torrent struct {
	// Active Whether the torrent is actively streaming or downloading.
	Active *bool `json:"active,omitempty"`

	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// CreatedAt When the torrent was added to the system.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Files List of files contained in the torrent.
	Files []TorrentFile `json:"files"`

	// Hash SHA-1 info hash of the torrent (40 hex characters).
	Hash metainfo.Hash `json:"hash"`

	// Magnet Magnet URI.
	Magnet string `json:"magnet"`

	// Name Original name of the torrent from metadata.
	Name string `json:"name"`

	// PieceCount Total number of pieces in the torrent.
	PieceCount int `json:"piece_count"`

	// PieceSize Standard piece size in bytes.
	PieceSize *int64 `json:"piece_size,omitempty"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`

	// TotalSize Total size of all files in bytes.
	TotalSize int64 `json:"total_size"`

	// UpdatedAt Last time the torrent was modified.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TorrentAdd Input for adding a new torrent.
type TorrentAdd struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// Hash SHA-1 info hash of the torrent (40 hex characters).
	Hash *metainfo.Hash `json:"hash,omitempty"`

	// Magnet Magnet URI.
	Magnet *string `json:"magnet,omitempty"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// TorrentAddFile defines model for TorrentAddFile.
type TorrentAddFile struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// File Torrent file.
	File openapi_types.File `json:"file"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// TorrentClient Torrent client configuration.
type TorrentClient struct {
	// DisableDHT Disable DHT (Distributed Hash Table).
	DisableDHT *bool `json:"disable_dht,omitempty"`

	// DisableIPv6 Disable IPv6.
	DisableIPv6 *bool `json:"disable_ipv6,omitempty"`

	// DisablePEX Disable PEX (Peer Exchange).
	DisablePEX *bool `json:"disable_pex,omitempty"`

	// DisableTCP Disable TCP connections.
	DisableTCP *bool `json:"disable_tcp,omitempty"`

	// DisableUTP Disable uTP (Micro Transport Protocol).
	DisableUTP *bool `json:"disable_utp,omitempty"`

	// DownloadRateLimit Download rate limit in bytes per second. 0 means unlimited.
	DownloadRateLimit *int `json:"download_rate_limit,omitempty"`

	// EstablishedConnsPerTorrent The maximum number of established connections per torrent.
	EstablishedConnsPerTorrent *int `json:"established_conns_per_torrent,omitempty"`

	// HalfOpenConnsPerTorrent The maximum number of half-open (connecting) connections per torrent.
	HalfOpenConnsPerTorrent *int `json:"half_open_conns_per_torrent,omitempty"`

	// MaxAllocPeerRequestDataPerConn Maximum bytes to buffer per peer connection for peer request data before it is sent (in bytes). Reduces memory usage per connection.
	MaxAllocPeerRequestDataPerConn *int `json:"max_alloc_peer_request_data_per_conn,omitempty"`

	// PreferHeaderObfuscation Request that outgoing connections' headers be obfuscated.
	PreferHeaderObfuscation *bool `json:"prefer_header_obfuscation,omitempty"`

	// Seed Whether to seed after downloading.
	Seed *bool `json:"seed,omitempty"`

	// TorrentPeersHighWater The high water mark for the number of peers per torrent.
	TorrentPeersHighWater *int `json:"torrent_peers_high_water,omitempty"`

	// TorrentPeersLowWater The minimum number of peers before effort is made to obtain more peers.
	TorrentPeersLowWater *int `json:"torrent_peers_low_water,omitempty"`

	// TotalHalfOpenConns The maximum total number of half-open (connecting) connections across all torrents.
	TotalHalfOpenConns *int `json:"total_half_open_conns,omitempty"`

	// UploadRateLimit Upload rate limit in bytes per second. 0 means unlimited.
	UploadRateLimit *int `json:"upload_rate_limit,omitempty"`
}

// TorrentFile File within a torrent.
type TorrentFile struct {
	// Length File size in bytes.
	Length int64 `json:"length"`

	// Name Base name of the file.
	Name string `json:"name"`

	// Path Full path of the file within the torrent.
	Path string `json:"path"`

	// ViewedAt When the file was last viewed.
	ViewedAt *time.Time `json:"viewed_at"`
}

// TorrentFileUpdate Metadata for updating a file within a torrent.
type TorrentFileUpdate struct {
	// Path The full path of the file within the torrent.
	Path string `json:"path"`

	// Viewed Set to true to mark as viewed, false to mark as unviewed.
	Viewed bool `json:"viewed"`
}

// TorrentStats Statistics about torrent activity and performance.
type TorrentStats struct {
	// ActivePeers Number of currently active peers.
	ActivePeers int `json:"active_peers"`

	// BytesHashed Total bytes hashed during verification.
	BytesHashed int64 `json:"bytes_hashed"`

	// BytesRead Total bytes read from disk.
	BytesRead int64 `json:"bytes_read"`

	// BytesReadData Bytes read that contain actual torrent data.
	BytesReadData int64 `json:"bytes_read_data"`

	// BytesReadUsefulData Useful data bytes read from peers.
	BytesReadUsefulData int64 `json:"bytes_read_useful_data"`

	// BytesReadUsefulIntendedData Useful intended data bytes read from peers.
	BytesReadUsefulIntendedData int64 `json:"bytes_read_useful_intended_data"`

	// BytesWritten Total bytes written to disk.
	BytesWritten int64 `json:"bytes_written"`

	// BytesWrittenData Torrent data bytes written to disk.
	BytesWrittenData int64 `json:"bytes_written_data"`

	// ChunksRead Total chunks read from disk.
	ChunksRead int64 `json:"chunks_read"`

	// ChunksReadUseful Useful chunks read from peers.
	ChunksReadUseful int64 `json:"chunks_read_useful"`

	// ChunksReadWasted Wasted chunks read (duplicate or unneeded data).
	ChunksReadWasted int64 `json:"chunks_read_wasted"`

	// ChunksWritten Total chunks written to disk.
	ChunksWritten int64 `json:"chunks_written"`

	// CompletedSize Total size of completed pieces in bytes.
	CompletedSize int64 `json:"completed_size"`

	// ConnectedSeeders Number of connected seeders.
	ConnectedSeeders int `json:"connected_seeders"`

	// HalfOpenPeers Number of peers in half-open state (connecting).
	HalfOpenPeers int `json:"half_open_peers"`

	// InMemory Number of pieces currently loaded in memory.
	InMemory int `json:"in_memory"`

	// InMemorySize Total size of pieces currently in memory in bytes.
	InMemorySize int64 `json:"in_memory_size"`

	// MemoryStats Global memory usage statistics.
	MemoryStats MemoryStats `json:"memory_stats"`

	// MemoryUsagePercentage Percentage of maximum memory used by this torrent (0-100).
	MemoryUsagePercentage float64 `json:"memory_usage_percentage"`

	// MetadataChunksRead Metadata chunks read.
	MetadataChunksRead int64 `json:"metadata_chunks_read"`

	// PendingPeers Number of pending peer connections.
	PendingPeers int `json:"pending_peers"`

	// Pieces Array of all managed pieces with their current status.
	Pieces []PieceInfo `json:"pieces"`

	// PiecesComplete Number of completed pieces.
	PiecesComplete int `json:"pieces_complete"`

	// PiecesDirtiedBad Pieces marked as bad after verification.
	PiecesDirtiedBad int64 `json:"pieces_dirtied_bad"`

	// PiecesDirtiedGood Pieces marked as good after verification.
	PiecesDirtiedGood int64 `json:"pieces_dirtied_good"`

	// Readers Active read stream positions for this torrent.
	Readers *[]ReaderInfo `json:"readers,omitempty"`

	// TotalPeers Total number of known peers.
	TotalPeers int `json:"total_peers"`

	// TotalPieces Total number of pieces in the torrent, from metadata.
	TotalPieces int `json:"total_pieces"`

	// TotalSize Total size of all managed pieces in bytes.
	TotalSize int64 `json:"total_size"`
}

// TorrentStorage Use memory or file storage.
type TorrentStorage string

// TorrentUpdate Updateable torrent metadata.
type TorrentUpdate struct {
	// Category Category for organizing torrents.
	Category *string `json:"category,omitempty"`

	// Files List of files to update within the torrent.
	Files *[]TorrentFileUpdate `json:"files,omitempty"`

	// Poster URL or data URI to poster image.
	Poster *string `json:"poster,omitempty"`

	// Storage Use memory or file storage.
	Storage *TorrentStorage `json:"storage,omitempty"`

	// Title Display title for the torrent.
	Title *string `json:"title,omitempty"`
}

// Hash defines model for Hash.
type Hash = metainfo.Hash

// Index defines model for Index.
type Index = int

// Limit defines model for Limit.
type Limit = int

// MediaName defines model for MediaName.
type MediaName = string

// Offset defines model for Offset.
type Offset = int

// Path defines model for Path.
type Path = string

// Range defines model for Range.
type Range = string

// TSFileName defines model for TSFileName.
type TSFileName = string

// TSIndex defines model for TSIndex.
type TSIndex = int

// TSIndexQuery defines model for TSIndexQuery.
type TSIndexQuery = int

// TSLink defines model for TSLink.
type TSLink = string

// TSPlay defines model for TSPlay.
type TSPlay = bool

// TSPreload defines model for TSPreload.
type TSPreload = bool

// TSStat defines model for TSStat.
type TSStat = bool

// TorrentCategories defines model for TorrentCategories.
type TorrentCategories = []string

// TorrentHashes defines model for TorrentHashes.
type TorrentHashes = []metainfo.Hash

// TorrentNames defines model for TorrentNames.
type TorrentNames = []string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// GatewayTimeout defines model for GatewayTimeout.
type GatewayTimeout = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetPlaylistParams defines parameters for GetPlaylist.
type GetPlaylistParams struct {
	// Name Media playlist by torrent name.
	Name *MediaName `form:"name,omitempty" json:"name,omitempty"`
}

// GetStreamParams defines parameters for GetStream.
type GetStreamParams struct {
	// Path Path to a torrent file. One of `path` or `index` must be provided.
	Path *Path `form:"path,omitempty" json:"path,omitempty"`

	// Index Index of the file within the torrent. One of `path` or `index` must be provided.
	Index *Index `form:"index,omitempty" json:"index,omitempty"`

	// Range Bytes range for partial content requests.
	Range *Range `json:"Range,omitempty"`
}

// HeadStreamParams defines parameters for HeadStream.
type HeadStreamParams struct {
	// Path Path to a torrent file. One of `path` or `index` must be provided.
	Path *Path `form:"path,omitempty" json:"path,omitempty"`

	// Index Index of the file within the torrent. One of `path` or `index` must be provided.
	Index *Index `form:"index,omitempty" json:"index,omitempty"`
}

// ListTorrentsParams defines parameters for ListTorrents.
type ListTorrentsParams struct {
	// Categories Comma-separated list of torrent categories to filter results.
	Categories *TorrentCategories `form:"categories,omitempty" json:"categories,omitempty"`

	// Hashes Comma-separated list of torrent info hashes to filter results.
	Hashes *TorrentHashes `form:"hashes,omitempty" json:"hashes,omitempty"`

	// Names Comma-separated list of torrent names to filter results. The filter performs case-insensitive matching against torrent names.
	Names *TorrentNames `form:"names,omitempty" json:"names,omitempty"`

	// Limit Maximum number of torrents to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of torrents to skip for pagination.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// RestoreTorrentsMultipartBody defines parameters for RestoreTorrents.
type RestoreTorrentsMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// QBittorrentAddTorrentMultipartBody defines parameters for QBittorrentAddTorrent.
type QBittorrentAddTorrentMultipartBody struct {
	// Category Category for the torrent.
	Category *string               `json:"category,omitempty"`
	Torrents *[]openapi_types.File `json:"torrents,omitempty"`

	// Urls A list of magnet links to add.
	Urls *string `json:"urls,omitempty"`
}

// TSStreamParams defines parameters for TSStream.
type TSStreamParams struct {
	// Link Magnet link or info hash of the torrent.
	Link TSLink `form:"link" json:"link"`

	// Index File index within the torrent.
	Index *TSIndexQuery `form:"index,omitempty" json:"index,omitempty"`

	// Play Start playback immediately.
	Play *TSPlay `form:"play,omitempty" json:"play,omitempty"`

	// Preload Preload content without playing.
	Preload *TSPreload `form:"preload,omitempty" json:"preload,omitempty"`

	// Stat Return statistics instead of streaming.
	Stat *TSStat `form:"stat,omitempty" json:"stat,omitempty"`
}

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = Settings

// AddTorrentJSONRequestBody defines body for AddTorrent for application/json ContentType.
type AddTorrentJSONRequestBody = TorrentAdd

// AddTorrentMultipartRequestBody defines body for AddTorrent for multipart/form-data ContentType.
type AddTorrentMultipartRequestBody = TorrentAddFile

// RestoreTorrentsMultipartRequestBody defines body for RestoreTorrents for multipart/form-data ContentType.
type RestoreTorrentsMultipartRequestBody RestoreTorrentsMultipartBody

// UpdateTorrentJSONRequestBody defines body for UpdateTorrent for application/json ContentType.
type UpdateTorrentJSONRequestBody = TorrentUpdate

// QBittorrentAddTorrentMultipartRequestBody defines body for QBittorrentAddTorrent for multipart/form-data ContentType.
type QBittorrentAddTorrentMultipartRequestBody QBittorrentAddTorrentMultipartBody

// TSCacheJSONRequestBody defines body for TSCache for application/json ContentType.
type TSCacheJSONRequestBody = TSCacheRequest

// GetTokenFormdataRequestBody defines body for GetToken for application/x-www-form-urlencoded ContentType.
type GetTokenFormdataRequestBody = TokenRequest

// TSSettingsJSONRequestBody defines body for TSSettings for application/json ContentType.
type TSSettingsJSONRequestBody = TSSettings

// TSTorrentUploadMultipartRequestBody defines body for TSTorrentUpload for multipart/form-data ContentType.
type TSTorrentUploadMultipartRequestBody = TSTorrentAddFile

// TSTorrentsJSONRequestBody defines body for TSTorrents for application/json ContentType.
type TSTorrentsJSONRequestBody = TSTorrentRequest

// TSViewedJSONRequestBody defines body for TSViewed for application/json ContentType.
type TSViewedJSONRequestBody = TSViewedRequest

// AsTSTorrentRequestHash0 returns the union data inside the TSTorrentRequest_Hash as a TSTorrentRequestHash0
func (t TSTorrentRequest_Hash) AsTSTorrentRequestHash0() (TSTorrentRequestHash0, error) {
	var body TSTorrentRequestHash0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTSTorrentRequestHash0 overwrites any union data inside the TSTorrentRequest_Hash as the provided TSTorrentRequestHash0
func (t *TSTorrentRequest_Hash) FromTSTorrentRequestHash0(v TSTorrentRequestHash0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTSTorrentRequestHash0 performs a merge with any union data inside the TSTorrentRequest_Hash, using the provided TSTorrentRequestHash0
func (t *TSTorrentRequest_Hash) MergeTSTorrentRequestHash0(v TSTorrentRequestHash0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTSTorrentRequestHash1 returns the union data inside the TSTorrentRequest_Hash as a TSTorrentRequestHash1
func (t TSTorrentRequest_Hash) AsTSTorrentRequestHash1() (TSTorrentRequestHash1, error) {
	var body TSTorrentRequestHash1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTSTorrentRequestHash1 overwrites any union data inside the TSTorrentRequest_Hash as the provided TSTorrentRequestHash1
func (t *TSTorrentRequest_Hash) FromTSTorrentRequestHash1(v TSTorrentRequestHash1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTSTorrentRequestHash1 performs a merge with any union data inside the TSTorrentRequest_Hash, using the provided TSTorrentRequestHash1
func (t *TSTorrentRequest_Hash) MergeTSTorrentRequestHash1(v TSTorrentRequestHash1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TSTorrentRequest_Hash) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TSTorrentRequest_Hash) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get global memory statistics.
	// (GET /api/stats/memory)
	GetMemoryStats(w http.ResponseWriter, r *http.Request)
	// Get torrent statistics.
	// (GET /api/stats/torrents/{hash})
	GetTorrentStats(w http.ResponseWriter, r *http.Request, hash Hash)
	// Health check.
	// (GET /api/system/health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Get application information.
	// (GET /api/system/info)
	GetSystemInfo(w http.ResponseWriter, r *http.Request)
	// Get recent application logs.
	// (GET /api/system/logs)
	GetLogs(w http.ResponseWriter, r *http.Request)
	// Get system metrics.
	// (GET /api/system/metrics)
	GetSystemMetrics(w http.ResponseWriter, r *http.Request)
	// Generate a playlist for streaming.
	// (GET /api/v1/playlist)
	GetPlaylist(w http.ResponseWriter, r *http.Request, params GetPlaylistParams)
	// Get application settings.
	// (GET /api/v1/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// Update application settings.
	// (PATCH /api/v1/settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)
	// Stream a torrent file.
	// (GET /api/v1/stream/{hash})
	GetStream(w http.ResponseWriter, r *http.Request, hash Hash, params GetStreamParams)
	// Serve a HEAD request for a streamable torrent file.
	// (HEAD /api/v1/stream/{hash})
	HeadStream(w http.ResponseWriter, r *http.Request, hash Hash, params HeadStreamParams)
	// List all torrents.
	// (GET /api/v1/torrents)
	ListTorrents(w http.ResponseWriter, r *http.Request, params ListTorrentsParams)
	// Add a new torrent.
	// (POST /api/v1/torrents)
	AddTorrent(w http.ResponseWriter, r *http.Request)
	// Backup torrents and posters.
	// (GET /api/v1/torrents/backup)
	BackupTorrents(w http.ResponseWriter, r *http.Request)
	// Restore torrents and posters.
	// (POST /api/v1/torrents/restore)
	RestoreTorrents(w http.ResponseWriter, r *http.Request)
	// Delete a torrent.
	// (DELETE /api/v1/torrents/{hash})
	DeleteTorrent(w http.ResponseWriter, r *http.Request, hash Hash)
	// Get torrent metadata.
	// (GET /api/v1/torrents/{hash})
	GetTorrent(w http.ResponseWriter, r *http.Request, hash Hash)
	// Update torrent metadata.
	// (PATCH /api/v1/torrents/{hash})
	UpdateTorrent(w http.ResponseWriter, r *http.Request, hash Hash)
	// Add a new torrent (qBittorrent compatible).
	// (POST /api/v2/torrents/add)
	QBittorrentAddTorrent(w http.ResponseWriter, r *http.Request)
	// Get cache statistics (TorrServer compatible).
	// (POST /cache)
	TSCache(w http.ResponseWriter, r *http.Request)
	// Server status check (TorrServer compatible).
	// (GET /echo)
	TSEcho(w http.ResponseWriter, r *http.Request)
	// Obtain a JWT token.
	// (POST /oauth/token)
	GetToken(w http.ResponseWriter, r *http.Request)
	// Stream torrent content (TorrServer compatible).
	// (GET /play/{hash}/{index})
	TSPlay(w http.ResponseWriter, r *http.Request, hash Hash, index TSIndex)
	// Update settings (TorrServer compatible).
	// (POST /settings)
	TSSettings(w http.ResponseWriter, r *http.Request)
	// Stream or preload torrent (TorrServer compatible).
	// (GET /stream/{filename})
	TSStream(w http.ResponseWriter, r *http.Request, filename TSFileName, params TSStreamParams)
	// Add a new torrent (TorrServer compatible).
	// (POST /torrent/upload)
	TSTorrentUpload(w http.ResponseWriter, r *http.Request)
	// Manage torrents (TorrServer compatible).
	// (POST /torrents)
	TSTorrents(w http.ResponseWriter, r *http.Request)
	// Manage torrent view tags (TorrServer compatible).
	// (POST /viewed)
	TSViewed(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get global memory statistics.
// (GET /api/stats/memory)
func (_ Unimplemented) GetMemoryStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get torrent statistics.
// (GET /api/stats/torrents/{hash})
func (_ Unimplemented) GetTorrentStats(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check.
// (GET /api/system/health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get application information.
// (GET /api/system/info)
func (_ Unimplemented) GetSystemInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get recent application logs.
// (GET /api/system/logs)
func (_ Unimplemented) GetLogs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get system metrics.
// (GET /api/system/metrics)
func (_ Unimplemented) GetSystemMetrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate a playlist for streaming.
// (GET /api/v1/playlist)
func (_ Unimplemented) GetPlaylist(w http.ResponseWriter, r *http.Request, params GetPlaylistParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get application settings.
// (GET /api/v1/settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update application settings.
// (PATCH /api/v1/settings)
func (_ Unimplemented) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream a torrent file.
// (GET /api/v1/stream/{hash})
func (_ Unimplemented) GetStream(w http.ResponseWriter, r *http.Request, hash Hash, params GetStreamParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Serve a HEAD request for a streamable torrent file.
// (HEAD /api/v1/stream/{hash})
func (_ Unimplemented) HeadStream(w http.ResponseWriter, r *http.Request, hash Hash, params HeadStreamParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all torrents.
// (GET /api/v1/torrents)
func (_ Unimplemented) ListTorrents(w http.ResponseWriter, r *http.Request, params ListTorrentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new torrent.
// (POST /api/v1/torrents)
func (_ Unimplemented) AddTorrent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Backup torrents and posters.
// (GET /api/v1/torrents/backup)
func (_ Unimplemented) BackupTorrents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restore torrents and posters.
// (POST /api/v1/torrents/restore)
func (_ Unimplemented) RestoreTorrents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a torrent.
// (DELETE /api/v1/torrents/{hash})
func (_ Unimplemented) DeleteTorrent(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get torrent metadata.
// (GET /api/v1/torrents/{hash})
func (_ Unimplemented) GetTorrent(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update torrent metadata.
// (PATCH /api/v1/torrents/{hash})
func (_ Unimplemented) UpdateTorrent(w http.ResponseWriter, r *http.Request, hash Hash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new torrent (qBittorrent compatible).
// (POST /api/v2/torrents/add)
func (_ Unimplemented) QBittorrentAddTorrent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cache statistics (TorrServer compatible).
// (POST /cache)
func (_ Unimplemented) TSCache(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server status check (TorrServer compatible).
// (GET /echo)
func (_ Unimplemented) TSEcho(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Obtain a JWT token.
// (POST /oauth/token)
func (_ Unimplemented) GetToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream torrent content (TorrServer compatible).
// (GET /play/{hash}/{index})
func (_ Unimplemented) TSPlay(w http.ResponseWriter, r *http.Request, hash Hash, index TSIndex) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update settings (TorrServer compatible).
// (POST /settings)
func (_ Unimplemented) TSSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream or preload torrent (TorrServer compatible).
// (GET /stream/{filename})
func (_ Unimplemented) TSStream(w http.ResponseWriter, r *http.Request, filename TSFileName, params TSStreamParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new torrent (TorrServer compatible).
// (POST /torrent/upload)
func (_ Unimplemented) TSTorrentUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Manage torrents (TorrServer compatible).
// (POST /torrents)
func (_ Unimplemented) TSTorrents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Manage torrent view tags (TorrServer compatible).
// (POST /viewed)
func (_ Unimplemented) TSViewed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMemoryStats operation middleware
func (siw *ServerInterfaceWrapper) GetMemoryStats(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemoryStats(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTorrentStats operation middleware
func (siw *ServerInterfaceWrapper) GetTorrentStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTorrentStats(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemInfo operation middleware
func (siw *ServerInterfaceWrapper) GetSystemInfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemInfo(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLogs operation middleware
func (siw *ServerInterfaceWrapper) GetLogs(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogs(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetSystemMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemMetrics(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylist operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlaylistParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylist(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStream operation middleware
func (siw *ServerInterfaceWrapper) GetStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStreamParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Optional query parameter "index" -------------

	err = runtime.BindQueryParameter("form", true, false, "index", r.URL.Query(), &params.Index)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "Range" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Range")]; found {
		var Range Range
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Range", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Range", valueList[0], &Range, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Range", Err: err})
			return
		}

		params.Range = &Range

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStream(w, r, hash, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadStream operation middleware
func (siw *ServerInterfaceWrapper) HeadStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params HeadStreamParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Optional query parameter "index" -------------

	err = runtime.BindQueryParameter("form", true, false, "index", r.URL.Query(), &params.Index)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadStream(w, r, hash, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTorrents operation middleware
func (siw *ServerInterfaceWrapper) ListTorrents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTorrentsParams

	// ------------- Optional query parameter "categories" -------------

	err = runtime.BindQueryParameter("form", false, false, "categories", r.URL.Query(), &params.Categories)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categories", Err: err})
		return
	}

	// ------------- Optional query parameter "hashes" -------------

	err = runtime.BindQueryParameter("form", false, false, "hashes", r.URL.Query(), &params.Hashes)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hashes", Err: err})
		return
	}

	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", false, false, "names", r.URL.Query(), &params.Names)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "names", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTorrents(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTorrent operation middleware
func (siw *ServerInterfaceWrapper) AddTorrent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTorrent(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// BackupTorrents operation middleware
func (siw *ServerInterfaceWrapper) BackupTorrents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BackupTorrents(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreTorrents operation middleware
func (siw *ServerInterfaceWrapper) RestoreTorrents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreTorrents(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTorrent operation middleware
func (siw *ServerInterfaceWrapper) DeleteTorrent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTorrent(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTorrent operation middleware
func (siw *ServerInterfaceWrapper) GetTorrent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTorrent(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTorrent operation middleware
func (siw *ServerInterfaceWrapper) UpdateTorrent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTorrent(w, r, hash)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// QBittorrentAddTorrent operation middleware
func (siw *ServerInterfaceWrapper) QBittorrentAddTorrent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QBittorrentAddTorrent(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSCache operation middleware
func (siw *ServerInterfaceWrapper) TSCache(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSCache(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSEcho operation middleware
func (siw *ServerInterfaceWrapper) TSEcho(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSEcho(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToken operation middleware
func (siw *ServerInterfaceWrapper) GetToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToken(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSPlay operation middleware
func (siw *ServerInterfaceWrapper) TSPlay(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "hash" -------------
	var hash Hash

	err = runtime.BindStyledParameterWithOptions("simple", "hash", chi.URLParam(r, "hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	// ------------- Path parameter "index" -------------
	var index TSIndex

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSPlay(w, r, hash, index)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSSettings operation middleware
func (siw *ServerInterfaceWrapper) TSSettings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSSettings(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSStream operation middleware
func (siw *ServerInterfaceWrapper) TSStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "filename" -------------
	var filename TSFileName

	err = runtime.BindStyledParameterWithOptions("simple", "filename", chi.URLParam(r, "filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filename", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params TSStreamParams

	// ------------- Required query parameter "link" -------------

	if paramValue := r.URL.Query().Get("link"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "link"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "link", r.URL.Query(), &params.Link)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "link", Err: err})
		return
	}

	// ------------- Optional query parameter "index" -------------

	err = runtime.BindQueryParameter("form", true, false, "index", r.URL.Query(), &params.Index)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// ------------- Optional query parameter "play" -------------

	err = runtime.BindQueryParameter("form", true, false, "play", r.URL.Query(), &params.Play)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "play", Err: err})
		return
	}

	// ------------- Optional query parameter "preload" -------------

	err = runtime.BindQueryParameter("form", true, false, "preload", r.URL.Query(), &params.Preload)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preload", Err: err})
		return
	}

	// ------------- Optional query parameter "stat" -------------

	err = runtime.BindQueryParameter("form", true, false, "stat", r.URL.Query(), &params.Stat)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stat", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSStream(w, r, filename, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSTorrentUpload operation middleware
func (siw *ServerInterfaceWrapper) TSTorrentUpload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSTorrentUpload(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSTorrents operation middleware
func (siw *ServerInterfaceWrapper) TSTorrents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSTorrents(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// TSViewed operation middleware
func (siw *ServerInterfaceWrapper) TSViewed(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TSViewed(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/stats/memory", wrapper.GetMemoryStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/stats/torrents/{hash}", wrapper.GetTorrentStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/info", wrapper.GetSystemInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/logs", wrapper.GetLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/system/metrics", wrapper.GetSystemMetrics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/playlist", wrapper.GetPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/settings", wrapper.UpdateSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/stream/{hash}", wrapper.GetStream)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/api/v1/stream/{hash}", wrapper.HeadStream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/torrents", wrapper.ListTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/torrents", wrapper.AddTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/torrents/backup", wrapper.BackupTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/torrents/restore", wrapper.RestoreTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/torrents/{hash}", wrapper.DeleteTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/torrents/{hash}", wrapper.GetTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/torrents/{hash}", wrapper.UpdateTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v2/torrents/add", wrapper.QBittorrentAddTorrent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cache", wrapper.TSCache)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/echo", wrapper.TSEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/oauth/token", wrapper.GetToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/play/{hash}/{index}", wrapper.TSPlay)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/settings", wrapper.TSSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stream/{filename}", wrapper.TSStream)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/torrent/upload", wrapper.TSTorrentUpload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/torrents", wrapper.TSTorrents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/viewed", wrapper.TSViewed)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9eXfbtrL4V8Hhe+fUudVCyZK8vNPTn+MkjVNvteWkbeKrC5GQhJokeAnQstrr7/47",
	"WEiCJEhRirO0t/+0sQACg8HMYDYM/rAc4ockQAGj1uEfVggj6COGIvHXa0gX/P8uok6EQ4ZJYB1aYxJF",
	"KGAABzMCFpAuOlbLwrwlhGxhtawA+sg6tHiT1bIi9O8YR8i1DlkUo5ZFnQXyIR8WPUA/9HhXex+6cAj3",
	"4Ki3vwsh6iH7wN3f7bmz0d5g3x2ORvbBEPZsq8XnYCjis/3zvd0+gO3ZUfvV7R8D+/F/rZbFViEfj7II",
	"B3OrZT2056StfvQRgxzmzmsJWNrWxn5IIibXzxbWoTXHbBFPOw7xuzCATkQ8/NBlct3dZBzr8fGxZZ0E",
	"LnooI0n8DMgMsAUCM+whsMRsgQPxtxqpAy4CxPv8i0/7L0Ai8C/Mv/sX8GPKwBSBMCL32EVuiuJ/xyha",
	"ZTgW3S0jUu2W5eMA+7Ev/q2QgAOG5iiyOOin2MesDPoZfOBfgSD2pygSa5DwUsAIiBCLo6AKHk8MaYRn",
	"uB6gM+RieC5GKgHFm0DowZWHOWpWCVCAz1wFjvifmeSu+cReiWQ4GBezGUUGxJwbEULvcAhmJAIhnOMA",
	"8r5V4BA5sA6Qi2Yw9liT7boUtFkEiv/KwYApQji1PQFpKWauxl1X/q/jhwMjGq9gMDfs5PMVQxREvFGh",
	"LWIYesAhAePgc3mBKKMpXAsEXRRlgMlxzZBN+eDf2e2e3d81AjW+foU9ZKax8QIJasqx7RThYA4oixD0",
	"NWTlRR3vqWitWtyZgKmQHhxGIPbLJDbMMCSioBqAlNZ6RvpS0PwkyGBLkNaKp7UwnOLgziST5gFiwMPB",
	"Hafl9OhJtmoNHPy7hkeRL2Y6/P6BfRdHweGU4cVh0+PpQ2zb/ZEbfFcjXMbXlx404PeawYgJATeFzh3A",
	"vs8lHkPeqpJB+TgGApsS4iEYJLNFyCPQNQgO2ZDyHd9VEksQcDCvnFWNt3biawYNMvRKHB+AMsgwZdih",
	"AAeUIejynZRcVjM5/2ztzJIUjiFDcxJhRMtAHBPfh22KuLbDkAvEkZKJdeCk33LJOsMeQxGIEI09KZbQ",
	"Q+gRF1mHM+hRZAY1G8Msqt5bZ+Set962LMyQTw0iIqUfGEVwxf+mbCWodEYi38oWyzWabRaa8tHHrFR+",
	"X7XKxqqdjoevSslrvAv8VNliEzgaTegHY3kG8d9CFPHJKHAgRW0cUBRQzPA9Aj5kzoIfUXAOOSvlh226",
	"h6Jz1RYqafYRhPrIZS8NSUAlgp5D90oe8/wvJYH4P2EYetgRSlT3N8rRp0HCe/J1DGy7Zbl8gzwqVO3k",
	"MEhUm4ENFugBOAsYQYcbMwINUUQi0f0eetjVzhAOI2QdAXa6/v+N0Mw6tP6nmxlIXdlKuy/FUEL9L2sQ",
	"Sn8BS8hlm5yLRMCBQUAEdBRF91yTeGxZxySYedjZEgsHOhaO0o3nghywBabaEjEF0IsQdFcgjBBVR2WC",
	"ksSiS7qgBywUsKdCCCVx5CDT8D9AhpZwNcY+IvFWaBjaAx0NaiSwhJhxruAaZoIYztMuZFBfugIAMPnd",
	"U61Z7HEEXOwCvusRchBnVijm8VYg4QYwi4gPYADiUB5+6ksBx0nAhSD0rsVPcr6tMJRjl1cQe8gVJoPn",
	"EX5MAR/5JFpJbRwjBwHKSATnKM82EphkaeL3p0DXUQCwaWxAHCeOIsUp54S9InHgbscpORI5J5mpxIeU",
	"DMPZ5BC4cPcA7iI0RKPpYGq7u/3hcDpDs4PhyO7tH9hw5u7be/aBiXv4RosBn1iSIDdjIS5U8vNcC7Kp",
	"QQtxGGJtmnbLAJNyj6tPOIDiNCiqqyWwLgvGWmIXARo7DqJ0FntSYZVGmxD2R46DQtYWZhvNQ1Aw3IwK",
	"87Gcqn2Kgrk0gA3f9+z+wGhQJF+nxmjl5EBajd2ePdgf7o1qYRmLFvNg3KgmXbNRzMe4CWDMFiTCv6Mt",
	"qbmXk/sxW6CAqc8AI3co4OLex5RyASisJXEK6TSrA/EkTJyHYiZlDJ87haQjMKhGEnQRm/wZhZEoYlyO",
	"ixM8jEiIIqZUehTAqYcMhs1L0cAndzEV/4S5MaVOpLCqdKKiHdGyQkjpkkQmw0m1CHlZM3Q2RMvypU/N",
	"Ouz19zVHz6BVpUmtQQvvJCYL+DDvrSmk2LFa1hTBCEVcVdOoW7WVZoopl7omT8iNalm7ROj6ONDXNxrU",
	"Li/TFMn0N+QwDsZz6NzFoVDMcxscEpo4oqHrYj459C5zXdZKMMN0ie+Of5/qs3VEr+R7Wct91D0K77OB",
	"Wynot4b503M8v1rJ3MWNeD0eXwpjOaaA98hhX5xrKeaHBwc66m2DE7Fl+YhSaPLKvY59GLS5fiY4Rp7A",
	"qnd+y0vHnVFS6ohJJm3JRZqQcoopG2sbkwfuNG8xURAhFmF0bzh38kj1zB5ugyNXurURNwuk7pxoaLnF",
	"D41IJRX+4svUIQxkFxBT6ULUnfTl8Z6OQvlYDHqmGA6DnsnDD+8h9jgJ5MDsDc0u6QryT6IAqb9bQmHc",
	"eDJ/GTDpcMzvHdfUq3lfOvAKMjLtyfWS2GFxhFzAxwGQUuJgYX4r8wgBj8wB4nN3LANgHrpHntlHzD8U",
	"zWAHdeadFjg5f3XRAu+Ors5b4OXV1cXVs45JFFUyXzKoxm9lOYarXNa8hTLoh4kzNLewVES6kKG2GGUd",
	"v6pOEgMZ2KbtOxOWwzWDJrb9wSNT6CXWRcwH0Rx/ZW6FDsP3aMIq5UDGt7JrRrax0HXkTHmO1TCAA06L",
	"dVEWIU4ncpjqwJhaEDefllJiCAUyzzH23u7eoLfP1VIdgNFgLQiCWSbCEKPrOVf240AYVt/nfLvR+rmE",
	"qkTAcZwY0mpHq1Y/3B3t79kHvf6Giy8QYpEgcttTQFQedBOtXvKOJ8GMmKK1EkwuquGUxEwLp0mLmC0g",
	"A0sEYIQU8Xkr4MOAi/h5mZS5kPYQM3DsuwViCxQJRpVDcxUZRnfIBZAf8vLDHDqlsCvrqDio3KryNEIO",
	"YgocuYneCngEunIHDaRTPacxYvUrikh7CjlFqFXVhIr0428j6qT4dwNKL6XPAv+OqnhRWHQfR4vpjupo",
	"b2URLg6ZiequhCFsJrsjKcUi0UV46xQRmqwdo6WTx7aS/3w8sMSBS5Z5aWCvw29IKJZjV7G+glWfNfko",
	"j/P+2r1kMGKVcbDmq+rZG+1jusQEgpbArWnrrpXtadi4zFAHDglmeB5H6+xVqMzdOkVOmMSPLWXbTlwv",
	"gJX27YvT8yMggoSJ22wWB47UfzBbNbNyk4nIMhDSIKqcbgqdu3kk/GVJ74J/lUrVSkTNdQdiUyAoi5CP",
	"SSUE17IdQNclAQgjwohDPEDjMCQRayS8OGwTBdskrM2nSBMATEuxRJxIBWBLqtoswihwvdXEbFyLjUv6",
	"yIQDF1M+mHTLOh7m2CxbXZdyPh8+JL6w3lDQfvLnrgGYBWPhRBLIJAmAFTSK40vAW8ReSoNT+aA1APbt",
	"A1s384fD3aHGdz0Th3tkPklEbsmkI/M07pK5MYTTq2Ux9MDyPgzxi2F1fIoKTf000dL1CV68fH7zg9Wy",
	"uMZutSyuslstS+js+QlVh7pQI/XIvHOqlOSaOKNH5l3eV4giDjCnKDQxn2WZipto8SoKLT6qOKt7tr43",
	"Pdu2n1jNTdx6xQCB+bwd7fXs/f2RUfNNgOz3BnuD/d3RQHeH7e4Oh4PBbt98XAjunwgHp/HY4DKCOiQU",
	"XHSHglQ/zQuOm6tTCpYLFBQcW1w3Uj7FjsgVge5F4K0KwkQzyKTUm0h2bWiiH8vO2ucsgs6dcnOZ8yyT",
	"HnI905WuTSlh0QEvobMAwuoHmCEfYPohIAFKPgYMo+j/OB3hwPFiFwE/9hgOPZQNr/Q0ygUS7976ECRB",
	"a97gS/HuEN+HNFHsIOCGl4fEpJ0PgU4G763YDQ+7XRl/xqhDovnh6GB0wHV10aKm7ngIOQsU0TafzcU0",
	"69rKdyQh5wjo3EWiR293d68qb2BnJ3bD/ywp/f4/XATS758ddrs7Hz68zxIKDm+//fDh9j/v/9k67H74",
	"QG+/fbZzyFtvv332/U73/T9b8sfvn+3wf/3jKUd89g9zIkNyrLSFx17QZfsOrbgELNKLyR1ZVmFWlCE/",
	"0T61WAJ03QhREY5/L86Iw26319/r2B270xPS3mqlvx/0O73RfqfX6dm2bLttWdMYe+7EhdzIsfq2PWrb",
	"vbbdF14+X7jdLNib9p1dl+93KP0X+yPhmLxHEZVE3uMzCtUzryxl4FU5Az1MGQpE5kPSuZMnv62W1TzF",
	"QUdA6YznTCOEDGcp0VPE7pwIQVbwAeaRV5o2wWbJu4IZkG1pErbml08xX/b6h2ZXkq7Tyj5cIlDkkMDN",
	"Y1ZtYkm4l4V2us91k0XIQ5AioDqDHYp8yMVy8gsO5s/yy5NUs86PlRFRbrNSlKa4yAC9reShM8Qi7NCy",
	"n3Kt16rS15rZ3waJXjRxyshN1PAJDZEpDqbcb0k3ILqlJzYIUaR2t2C47Q6Go71G2xuHDeaXnTaavcHk",
	"az1FBewUgDXt8/j6GDoLpCUmlc9jmYoBHN5RT2JUofqy1bdofoXik1+HKCJNwFaLCRkC2RQVWeAkj4tj",
	"GEIHs1UVi8ihHNVrC79qmUIvUy9qVQixVmm7znyGpZD3GQxT/yvAgYsdqagnP+ScOWZnJD0mccCa+njL",
	"Kn/VerNUiZKSHLgwSpxGnui2qc+sPOlVlutR6d8CHOcCHRQQKfDEdotM30YxrmvNk7YuFJtSWkoBeYwX",
	"EJUtwcwNNZ5jjROMG1/gAOVEdBv6hTfyBp+4Va5R4UcrOl7rDcQqEvo0vtaWdRlhEqWyIbsTY5o9VH3B",
	"zgLPOc4wBb6wjoXpDQOWVxd6GzkIT/hhkRJGtmNm0qhz72q08fW4eCUkf2EHb5RcF1rn3h1fVzt4ta2r",
	"9uiKQ/La6MYp+FBmJDkoPyJYmLKWAQGGxSkd48h1X2Fp8xVCVPKCginMp1oE2CSawwD/zu2sRLvKKyvq",
	"GoPJD6rmNes+4ppabqQdmcWTu8j2TA9hV2f5yIQbQyLT1alIBIMMgpurE3E+i64A+yWnrrDqhcNC/CJu",
	"Bsjend/CuTkoz0xLfCHduUA0Sxd5RQAsu4aoe3VFMqPm1+2t0+QEpm/ryIDTQHIjB3rexcw6fN/IYyWI",
	"57FVpB7s1l0R2+SsKSwFm5j1Vl9KEwU9TfmGAZwjX7tXaE47MNqojsqoTG5f6I5k6PJjwo1IaLWsuUhy",
	"8TBlwnHo513JsmvZrm/Gf5WUU813SeZM4d4lpGg0aKPAIa5wkWZMBtKs+HT0X1/MR7+8G8bT3bfxL/2b",
	"38/HYe/X10ej09WB7fivfoP9t6tT/2D567shhj9f2dPdN6tf3w3tU//8fjomg7Pj/e9MsCX2EAmQosHC",
	"eeeHbAXuoRcjeWlB5Fh08gxilwf+SiwsTqhekxuMN1eneYg+6b3DagF5qUlDUJCWHysdKRQm+cSd5rQ6",
	"U+rWNcyyeTjHcRCmkOqpUJqm20Ts5oF/Kf8FBNOsdxxJiVArUHXjeCOBKpOlzBRbJ72qrOopZpNIOSFr",
	"hUylnCg3rPEsvdjQpWT3B7Ztd/RcLJfEUw+ZzQJp+ApAVFh9otyQGrRZJxXUNaagXWd+CS5MEXRUgNpw",
	"f7mZFVo8Tw2O4U/t8zFEQaGL3DSi2MBkN0emx4WSCuurJXwZwaLuIG+yYPUJcifypkmzr6jSmMwtEwWR",
	"MViQJGU2nGlzkVa9JUmoaAP0FD25BSYryMeSb1WVetHpsJUU38htVnkjWumlbg2jOv4S3BTWtdahK3XG",
	"txgtkdtEZbzHaAkYnD+xoigToLlSqDTE2wpLaZJm1pW3J5EojY6tdDu0Uc1HWYKcBm5eDTtVB9HTLKIh",
	"7OQOBdqu5iGZRzBgE/NFmvECAdEu79CAM3Vn+Jvkts43+u6lV3hMu1Z9RYhPElMUfUNB0qnyalDKndpv",
	"G1zV0aZKOpmv6NSjXUOZNlvLhIDSLmTkU+QXB1FalbHBAX/zbgxkL5mykYccrd4spj84+AK/Obn5/aR3",
	"jk/oSXA1dI5PRid34c9vj98cdNDqTc/pv11N/Vfs1+uT0Yn/6m76zotP8BLDd6/sk9/Iw/n4Zf/st7Ph",
	"2YuT1eynzvXM+/FhefXm+gz9+OOr/k/jwWwZnqE3s93R5cXdaPXm7QS6P1G6HBqvTaGHEEeITnDFojw8",
	"Q4XwaeLiqlzr7siuyAW/Q0ENJfMWGVPkI4IjbwlXFHzzXFwD+yaPTvljA+VX27UcBGYSkFdPNtWCj1xX",
	"6MANut6EImxb9kHIoF+9Kz2tdEGztO20zIjQSbJkxkZedhXBn5iS2t4lAf/0Kj6kALrS3JbJNSKWXAz/",
	"9wdtu9fuDcc9+3DXPrTtXxte3JBysiZJQjSL27oQB6VYc3O1N+cLaqjwXr8+avcqS/WAnVKVhmefxUb/",
	"DPVCzJL6IsJzHEAvV2MqdcNExM8XKGiie2PkoImzSRAR1GTj9wa9faPuLKYx5ysWQorVgaH+qN8bNAva",
	"ynsd5vnkqsQ0ZAag5ykSN865u9frHQzt/cF+w3QGt5K1TyFl4qZVib994uIZLuf0ZEzdOxwMN2Bqs0Ik",
	"/UOZWi0ZP4esPEFUaMSZ+DXcggljmQUMXZHcDUHAtb6MVD53BOFvwZIXLIoIqpyLJdP6aZ2KGjLUwB8+",
	"5IbeeS8RZLcPBI7+8x62fz9q/9pv793+sdt/fPYVhW5UBvMW7jv53eNtK3NpWul9oNI9+iQESKLCdYIv",
	"HD6q0uT+jhd+HqLbhNT+DIHGXH575SbK5Mb8nanywaLqdkzcBTOuWd5/ej0GOy8wB3QaM+QCLmjBmLc9",
	"a3DvSElkVf9Mzfji9Vi4ndX8OLwfVQNwcnk/Wm8yGOfhn+oThaYrlck8ly9/BjuXCEXg5YOzgMF8+/Vd",
	"vvxZn5Y5YfW04+NLvk8BEl4luu2U4+NLfcqY1UwZjy/Bzhl2IgLGEQyouJV0qS56bb3om/FlLqgRQYYm",
	"FZUh0siGuPUgOhnDG8AGPoIBBXEgOpXLOtTnxiDK4NTDdIHcCUcynYQoStJXzaa+XyrLrA2i75SA0yQD",
	"chWYzTnFC+jNJiREwfZQ8SHafAiwkwAVzJ81ArCvXykbVt1bEheSJiFC0US5aidcXgtY+SzV2ThyGxkB",
	"03g2k1UVAR9HA07ecUIiZUvW8RNnwRTNRIKZcCRQoWUmZPGsA66QG3PbKlfpIMyNa06SSxebWEfGwMUM",
	"RRNZT2tCprOYyrx5U21VCbG4q05iNif8FNYQ/w1QZbnAFIFkqALpVt7SpKg2bZEA3gHAGT8sq5wqlYMn",
	"rn2OeTpZ4PlisoTGE5oTHW8Hol3cnE8PPs3Y5ePUMILOCaO6IiwKIo8s6wBSY5UAUGSDZjMuycRFf5ef",
	"z4BMuVYvsxZF100ZVZp9BXatZ1FWcAg0YFRujFCRhWFW5nr2ekhVmKZO6t6ETyBzd3uD4V6uupbdMFVO",
	"c26Zc5rSy26VprBXkS4rPq/Jlu0f9Ae9vWF/43xZs4vpOaTlEuYmPdBctL1lme9Ev4o9D/CmdQ8aGGbq",
	"1k94L0JQ9d5UORukwIOUAfnF9t6WIPZEgaOKi50FhddLEoHTeAhb1CnAfMOVw9rwhoF07wl5JZxN0sky",
	"a0Zj5r0RRYI32J+KHTB4WZDIxOFI4v8XghZShf4WEKJcb4iDbGcMZblzNRhk4Xo1cw02r9dmdchqLYkF",
	"KFz8mK0ADNwkGAsDB1XWGhKyt+4WdlYtRZUcSqV1mScFf09EOWy3ynMppZrsA9yYbwK4RxGeaeX1Grgq",
	"5VQRgmsmEjnVwrfsYnq38eCTilTCbGyha6j4AkdRDNOjIs0q3GzKmKJZ7FXMfCMalU5WWGG6M1vNxxsD",
	"F7n1Eye9ngqCZYQZM0ZHtU1UnURe3Ka7qL6tWNVY26mPmsxZxMFdPUHKLttRpDa82q/KHSpNs8mm6PMs",
	"ITVf1BG/5+bZcWN5nVVUHY2DAKGERp5tNvMaelCTbrlHyVWWRqGVtLcWODIU+uoP+vv7xtvA9fqL0jI5",
	"MBxZa4Rw0hmozmb5m2nDa8W6VM9xoCnBlPH901Vh8yw1RbfOi8G2hrW2+ptWqUthaLSVJWBSKOpCdVts",
	"agJTcmrX+Tj1yoHZp8J05pa8gwJmrJV4mbbxpfn5ezZZhQxMs3iQ3e7Zdt591O/kYpFZNqpWRGVNbmoS",
	"rJ3Uyr5U59PkRUN+DVHADegmxCw6Fl0ZFVxSVVjwSBQPUUFVmXmc8n5SMxNHCRWporSNMwhyF2mL+QNy",
	"lkl10TxdFOTFUt0aJy7m+p47mcKqq5F66b0pTNwXWyhkhRnnhDSZknfbfs6oyb1b9axAcoePKmdJxh+N",
	"t7Du/m1ajBFVlLLJux7uArIM6lTpbWtgasZOqyanomdvWnlws5yEAvvU3ZTdWMyaKx9IxBdskJydUNbr",
	"K9Xu9fpxUX81qpt5tdCoxRlVrpI2ZFIXysd9hUguCtKyuDHKCzNL5+m8pFMVa0PmTunC+Vh95qUyulTi",
	"VKPCWqs5jTI2D0dnOa8p/EmwT8snSEuvFr0I+Vw9g4eP/y6CPKbXWL5EpHlt1hwj0klT5UnZNHMuzWOs",
	"qi2WnYefKjodoGX7LxihLjCCCFY4cYTZ6prDq+5JQYqd5M0JsQ7D4wgcacJ4FrmySW/516tESr95N06e",
	"yhJDFPJqkzEcQu4wSsYQr27Jn7T37BClMmU/IYEQ/4hW8oUNrIoKCO+KfCMK+RB7/DtZ8/L/aXubDZqU",
	"igRjBPnPceRp5KAlG6U1LMvPeaRcmuXKao+TSH1QCoN27qzT5YmHHaTywhVkZyfjEjxcgMvHbTokmnfV",
	"R7TL+/KtRZFPL2bXKLrHThVZi07d9KaIhoKjyxPLWG6MTwtDbB1au6qWVAjZQhBKF4a4K2R0NzP05qjy",
	"McPUssrH/2DgymCGMYySVttThRSzxOC0UMqJax1aPyCmW0qFd9T6tt3gCZlmb7vkDLLyCy+yOV/ox/wI",
	"w2PLGti9qulS+Lu5h3AeW9ZQLqb+I9ObWILhY9+HfKs4xsA8V3k+X3Oewbkoepf9at3yEbRtTzap+wdX",
	"pB7r9l9ggAL5Hg9HRdE1DQENkcNV+0wxlTUYs4r1kmJaSl1sCdIJEFuS6C51aRtJI+cmb+Ve767IZsu6",
	"dEVi4uPtJySp/I1XwyNXJLMlmxBVA/rQXhb8/HTIvx2s/7bw6F2ZfFkJL+sJV8iP7gJBT543RoI9XiDn",
	"DmB1GUUT6JiCKA5kNcXAzb8Ckqe612IGMVCFNKqu9IcpkACuOrlT2jp8f6vjQM4BHD6JvnJZia+86uSk",
	"rBXSKYviUrH/AjaMrKZV0vyEHKPNYuCX65QlsgcExVEs8ZAvL7Qt+Q/6B0+2nOrn7QgBZzBYAcWsFLTB",
	"VRb+Rw+OcKF3nvhcyJF8oULbGhrziKwTVEtjMHvcdYGAT6h8+jFgejVnI3md8uE/krAaGSTpgzvlGmoG",
	"NTBZTg78r+CAV1jV95NvUJON9LNCnrV7GSHoiZyBhLvUh8DDd8gccU7ObHElmdaIkaSY6CeXJMlEJmGS",
	"X9VXrM3l8V+7x/e9LrdoxEXrtcwaAH83Bkl/YZxm5k5ajlVuhnEzL5OpNlW9zpCL4Tk3ijbUvx7afojm",
	"N1enVa9P/s/Ln8dnuzcfAv6Pk/NXh+1eSxrWH4ImD3zmMDJHAZJvVn8xZWzQRKFKH4d9SrqTSwewgkB0",
	"Mrzv5UmQanXlag2H1HKElQ+KcLmil6ArS5Rksk8pTJI5THJEtX3NEkRHr47M3AYKF4CzqHJeVu9RB1wT",
	"fkwkiPDhCigXPYBcUxMVDxkBDN6JZFDkGOSJnCW3m4J1nhN39Vk28hwtszWICly0Y+nBBhbF6LFEZQNj",
	"6pgcRd2o/DPacjkaMlBAJRnpckAIi3VeBPmCs/bimHDMT1cAM/0Jdy4IRItM9ItUpT2hQeMIUfl0i3jn",
	"OMldl8G+MP9ms1mIyOeht3MhtNb2u4SsUb8TUfCjQUf5nLPh8Byt32611q/5EBv0Rp/eBpOkck4YuIYM",
	"0xmWBv+X8oBkvoA/cq7z97ePOeeAkV0MwnxhzMcQ0AIIXr88epFe8RBXntXRnotRbcSJJleJ+3Ux1m0T",
	"j81b7CKSPTmPHjBltJXG6+T1Fxwkd0mav/a+2dvuNY+5l59fNz20/hdUUT8He23MIHUnoP4qxhrPSShf",
	"S0Zu6nTIxUuy7LUk4KReQlKRE3AtY2KUw8SQSKyeZneDT14YtOfcq9Obsmhy41WGpDGiTfhQfcTZe6MP",
	"uK3YqP+puGHToOOFfJv5k/r/c/g1+pfKm56F8v98aqLIHyheliraGMRUh+7IdbUTTRULSougZrTtZ1Vk",
	"aSs7khAVh5LOlQZyP3LdpFzTptaFcjDknjTJ1s2hv8dQL8kReCurZQkrIvtmk8obaSKClnSiorsqUSBf",
	"EKMMjYYrHZTkk6cujqFyNtZXBdhkZZMlZgt5vTWOcO06RSAgTQ1R4DRdt+vu94dD5LjOngOHw9nUnk5n",
	"+73d/q67v2eP+u60Nxu5PSdd93M8//Z57Nx9+zwOgpW+fg7CochH6YbB/P+moux0C799fnG1tH/8YU6O",
	"jo6Ozq9vFi9v5vyfL/l/nh8f/XR0dHTce320POY/HNvey5/eXg36/vndL/yHo1+Ojn47fm4f74u/rm/e",
	"Xlz9ODz+5eTkOw2Bz/EccLCABEvInI1ilaIu2WMrxwTEYYi15elnOMHgMq8vKlYCO/wvcRmPLkjsuWAq",
	"bgEmSswLTJOkTKVKiRTlDNq1ZSw4lYhX/GDEurx3O7nlsemSZWGv6gCtICsmXlDsgOMFIRQBEiBAZocf",
	"gjZ4c31xrnJC8lWuU4HAe50lsIqHP1VOsY44LsJIqF7wT9RN4bZc54PoPXXIug4ZsqBb3qWRU4FPSdUN",
	"bZHAJYNDAVp6q+Q9OD0hykAAnPVbX1jHPVj/0TEJZh6WqYhfNoguj9NC8ap1Omp3Cp27OKxUVZ+L5rxW",
	"Ku4ZCskn8gXT5zATvTh/AMsRNI1zA82rKISakbOc0UTNajUS0C+sNylYTFhttHEREq/jikuyRvXqSnYw",
	"75tIE4dgqiOkuHNqgNzWVelPa2VyuWxuU3FfTHR8bOSOVcD/+d2wddvYiFAyT6yLzDdNrpBPhP2bK8yo",
	"25njBaZgiT0PQI8SMIsQP7lW5StIKZzfUO2ySp6uXggwMq38aTK4BjU3PZG8PfM0IZovFZ2TaMtfli/Y",
	"WfVxt5pkoHLCXskDWJeL9/Wm4dXpNF9B2t2fw41mzNPTrzJsFFL09YoQMJC+Vi37oAMuAm+lSowKx9sM",
	"I8+lwIEBNydUfK0qmPgEJPn0IchCVedqmkyRk17EaBKO/Kxs88Xjm19KACv6XcsA6SHczw5hKGvPmjW1",
	"Y+KHkOEp9jBbARS4IcFBfVHaPOX/9Bwzlhq2TfxdG+pr273bVfVIB80l7jWoXFm8KxRHnukGaOpP1T2G",
	"iQm/rW5Z5C2GHlg39CAOqtKRLu46TbKO6kzr/5rM75LRCnb+nRGzuPnMOUOVt0zYTOui+E08NLkVh9U8",
	"69wB6WWXtCWmSWCooDCVuVK9KP2JsloKL3cbCOy45sHuz3iiFN7Vbgbof5NmVlKxSs+L7+hEamaJrIfi",
	"COQsqu8HNOMHRe/iSgIO5hk7fLAufvxgATwDVPbMrlKY2OAlB+UpBOuPTeTqdRmkL2zCG9C51ZYSDl03",
	"fVrGLOouZJVFKN6ZEX1BTIV6vUDgKklwuFgGKAKX6qEbcBwhFwUMQ4+CHyJYkTA1Vs+jNBNnD+3lctkW",
	"6kUceeoJzk00Ue21I8M231COOQ1ucT1aLF5qTOmDM59Te9bfBjKe+Xw/JJR/Xt9UxQ2mMuXp1MwBUHQc",
	"enCl3FLdP0Qe0eM2kqoybx24OEIO81YmYXTpwdUnS00aX1cmHf2dpLdhkl5AGKB/wiS9IjFuI+n1ZPqP",
	"0WhpPimZmhjiE2dfaxNUGEGGN+c/n8hulOX/F0vpTqliK9JU+d1JoP8jRTeJgHod0yTIRbz8HkaYxFSF",
	"yc00vF3G6fj6FAd3Gwj2n2IkbhE26H8pi0w06SnX36yzen+3Qc9X2EPbXLfalL2Lb0OLTJLYxaT7j/ww",
	"TYJ999hFW3xYZl0pi0lUMCvjKPjb3//EB17GwpkTZwvBkjz+JGunf5y3tJiqW5QXqT9eTPVRjtJGzFGT",
	"brQ+R+hzZwMZOPrvvKCv2WO6PbN9tIJpeLV/B7puC0Qip6AlXPLPaljw06mdKRVXuhDGZeA/mYuUBKjJ",
	"e2tl3mv9seEr/dqnhcDJrQEHF8m2aFVG/z4em7HimaCbLDNnG0bMXiL4GDZMXio3KsfyxfNPxmf51+ZN",
	"5nzyRA/hlocUCS2uNURJ3lEC/tOzXUPWKTwK36BMSEO++XK2Xp44MwrZnEqLKqFWVPD9LZdPeuFAqSOq",
	"gUoR2ssTwBeLApZcKU4oWlCuKpknXIV84CasIB2/etDw6PJEG0yPFZbHVBXe9IskmsFgAk6rRGUCMUJ8",
	"/gJ05VNSG/C+t+Fatf3LL1XbtvKI14ZySemXqqbI4+3j/w8AAP//yyFgBh3JAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
